// Bổ sung kịch bản video AI (14 / ngành) – phần 2.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Thời trang',
    prompts: [
      v('Outfit đi làm 5 ngày trong tuần', 'Kling, VEO3', 'Gợi ý phối đồ công sở theo từng ngày – rất được lưu lại.', {
        info: '25 giây · dọc 9:16 · Kling',
        character: 'THU: a 27-year-old Vietnamese office woman, shoulder-length straight hair, slim, natural makeup.',
        scenes: [
          sc('0–3s', 'HOOK', 'VEO3', `THU stands in front of her wardrobe, looks at the camera. ${N}`, 'Thu: "Outfit đi làm cả tuần không lặp lại nè!"'),
          sc('3–20s', 'THỨ 2 → THỨ 6', 'Kling', 'THU walks into a modern office lobby 5 times, each time in a different outfit: Monday navy blazer set, Tuesday white shirt + beige skirt, Wednesday knit vest + trousers, Thursday shirt dress, Friday smart jeans + blouse. Quick transitions.'),
          sc('20–25s', 'KẾT', 'VEO3', `THU at her desk waves. ${N}`, '"Bạn thích ngày nào nhất?"'),
        ],
        audio: 'nhạc trend nhịp nhanh; SFX: whoosh mỗi lần đổi đồ.',
        text: 'Thứ 2 → Thứ 6 · giá từng món.',
        cta: '"Comment ngày bạn thích, mình gửi link."',
      }),
      v('Lookbook đồ đôi (couple)', 'Kling', 'Video đồ đôi lãng mạn cho shop thời trang cặp.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'COUPLE: a Vietnamese couple in their mid-20s wearing matching [sản phẩm: cream knit sweaters and light jeans].',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'COUPLE walk hand in hand through a park with autumn leaves, slow motion, golden hour.'),
          sc('5–11s', 'TƯƠNG TÁC', 'Kling', 'The guy puts his scarf around her, they laugh, close-up of matching sleeves.'),
          sc('11–15s', 'KẾT', 'Kling', 'COUPLE take a selfie together on a bench.'),
        ],
        audio: 'nhạc acoustic lãng mạn.',
        text: 'Set đồ đôi · giá combo.',
        cta: '"Mua set đôi giảm [x]%."',
      }),
      v('Thời trang trẻ em', 'Kling, VEO3', 'Video dễ thương cho shop quần áo trẻ em.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'KID: a 5-year-old Vietnamese girl with two pigtails wearing [sản phẩm: a yellow dinosaur hoodie].',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'KID jumps on a bed playfully, the hoodie\'s dinosaur spikes bounce, bright bedroom.'),
          sc('5–11s', 'VUI CHƠI', 'Kling', 'KID runs in a park, pretends to roar like a dinosaur, laughing.'),
          sc('11–15s', 'KẾT', 'VEO3', `KID faces the camera and roars cutely. ${N}`, 'Bé: "Gào!"'),
        ],
        audio: 'nhạc thiếu nhi.',
        text: 'Chất liệu cotton · size theo tuổi · giá.',
        cta: '"Chọn size cho bé trong giỏ hàng."',
      }),
      v('Đồ thể thao – năng động', 'Kling', 'Video activewear chuyển động mạnh.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'RUNNER: a 25-year-old Vietnamese woman, high ponytail, wearing [sản phẩm: a lavender sports bra and leggings set].',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'RUNNER jogs along a riverside path at sunrise, slow motion, fabric stretch visible.'),
          sc('5–11s', 'CO GIÃN', 'Kling', 'RUNNER does a deep lunge and stretch, close-up of the fabric moving smoothly.'),
          sc('11–15s', 'KẾT', 'Kling', 'RUNNER stops, smiles, sunlight behind.'),
        ],
        audio: 'beat năng động.',
        text: 'Co giãn 4 chiều · thấm hút (đúng chất liệu).',
        cta: '"Mua set tập trong giỏ hàng."',
      }),
      v('Giày sneaker – cận cảnh chi tiết', 'Kling', 'Video sản phẩm giày phong cách streetwear.', {
        info: '12 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh giày thật] The sneaker drops onto a concrete floor in slow motion, dust puff, dramatic light. Keep the shoe design exactly the same as the input image.'),
          sc('4–9s', 'CHI TIẾT', 'Kling', 'Macro orbit over the sole, stitching and logo.'),
          sc('9–12s', 'KẾT', 'Kling', 'A person laces up the sneakers and walks away on a city street.'),
        ],
        audio: 'hip-hop beat; SFX: tiếng đế giày.',
        text: 'Tên mẫu · size · giá.',
        cta: '"Chọn size ngay."',
      }),
      v('Túi xách – phụ kiện sang trọng', 'Kling', 'Video túi xách cao cấp, ánh sáng sang trọng.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh túi thật] The handbag on a velvet pedestal under a spotlight, slow orbit. Keep the bag exactly the same as the input image.'),
          sc('5–10s', 'CHI TIẾT', 'Kling', 'Close-ups: leather texture, gold buckle, interior pockets.'),
          sc('10–15s', 'PHỐI ĐỒ', 'Kling', 'A stylish woman carries the bag walking out of a café.'),
        ],
        audio: 'nhạc sang trọng.',
        text: 'Chất liệu · kích thước · giá.',
        cta: '"Đặt túi – tặng kèm hộp quà."',
      }),
      v('Size cho người mũm mĩm (plus size)', 'VEO3, Kling', 'Video tự tin, tôn vinh mọi vóc dáng.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'LY: a confident 28-year-old curvy Vietnamese woman, long wavy hair, warm smile.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LY in front of a mirror, smiles at the camera. ${N}`, 'Ly: "Ai bảo người mũm mĩm không mặc đẹp được?"'),
          sc('4–15s', 'PHỐI ĐỒ', 'Kling', 'LY in [sản phẩm: a wrap dress], then a high-waist trouser set, turning confidently, flattering fit.'),
          sc('15–20s', 'KẾT', 'VEO3', `LY strikes a pose. ${N}`, '"Size tới [size], form chuẩn, mặc là tự tin!"'),
        ],
        audio: 'nhạc tự tin.',
        text: 'Bảng size · tư vấn chọn size.',
        cta: '"Inbox số đo để được tư vấn size."',
      }),
      v('Mẹo bảo quản quần áo', 'VEO3, Kling', 'Video kiến thức giúp khách giữ đồ bền – tăng thiện cảm.', {
        info: '25 giây · dọc 9:16 · VEO3 + Kling',
        character: 'STYLIST: a 30-year-old Vietnamese female stylist, glasses, black turtleneck.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `STYLIST holds a faded shirt. ${N}`, 'Stylist: "Áo mau phai màu vì 3 thói quen này!"'),
          sc('4–20s', 'MẸO', 'Kling', 'Close-ups: turning a shirt inside out before washing, using cold water, drying in shade instead of direct sun.'),
          sc('20–25s', 'KẾT', 'VEO3', `STYLIST smiles. ${N}`, '"Lưu lại để đồ bền như mới nha!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '1. Lộn trái · 2. Nước lạnh · 3. Phơi trong bóng râm.',
        cta: '"Theo dõi để xem thêm mẹo thời trang."',
      }),
      v('Thời trang công sở nam', 'Kling, VEO3', 'Video vest / sơ mi nam lịch lãm.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'DUY: a 30-year-old Vietnamese man, short side-parted hair, wearing [sản phẩm: a slim-fit navy suit].',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'DUY buttons his suit jacket in front of a mirror, close-up on cufflinks.'),
          sc('5–11s', 'BƯỚC ĐI', 'Kling', 'DUY walks confidently through a glass office lobby, slow motion.'),
          sc('11–15s', 'KẾT', 'VEO3', `DUY adjusts his tie and nods at the camera. ${N}`),
        ],
        audio: 'nhạc lịch lãm.',
        text: 'Chất liệu · may đo / có sẵn · giá.',
        cta: '"Đặt lịch may đo tại cửa hàng."',
      }),
      v('Đồ ngủ – mặc nhà thoải mái', 'Kling', 'Video ấm cúng cho đồ ngủ, đồ mặc nhà.', {
        info: '12 giây · dọc 9:16 · Kling',
        character: 'MY: a 24-year-old Vietnamese woman wearing [sản phẩm: a silk pajama set in champagne color].',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'MY stretches on a white bed in the morning, silk fabric shines in sunlight.'),
          sc('4–9s', 'THƯ GIÃN', 'Kling', 'MY reads a book with a cup of tea on a cozy sofa.'),
          sc('9–12s', 'KẾT', 'Kling', 'Close-up of the silk fabric texture.'),
        ],
        audio: 'nhạc thư giãn.',
        text: 'Chất liệu lụa · màu · giá.',
        cta: '"Mua trong giỏ hàng."',
      }),
      v('Flash sale cuối mùa', 'Kling, VEO3', 'Video xả hàng cuối mùa tạo khẩn cấp.', {
        info: '12 giây · dọc 9:16 · Kling + VEO3',
        character: 'STAFF: a 23-year-old Vietnamese woman, shop apron, energetic.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Clothes racks spin quickly, price tags flip to lower prices with a sparkle effect.'),
          sc('4–9s', 'ƯU ĐÃI', 'VEO3', `STAFF holds up an armful of clothes. ${N}`, 'Nhân viên: "Xả hàng cuối mùa, đồng giá [giá]!"'),
          sc('9–12s', 'KẾT', 'Kling', 'Shoppers grabbing items happily.'),
        ],
        audio: 'nhạc sôi động.',
        text: '"SALE CUỐI MÙA – ĐỒNG GIÁ [giá]".',
        cta: '"Chỉ đến [ngày] – săn ngay."',
      }),
      v('Hậu trường chụp lookbook', 'Kling', 'Behind-the-scenes buổi chụp – tạo kết nối với thương hiệu.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A photo studio with lights, a model posing, photographer clicking, flash bursts.'),
          sc('5–14s', 'HẬU TRƯỜNG', 'Kling', 'Stylist adjusts the outfit, makeup artist touches up, team laughing.'),
          sc('14–20s', 'KẾT QUẢ', 'Kling', 'Final photos appear like a slideshow on a monitor.'),
        ],
        audio: 'nhạc vui; SFX: màn trập máy ảnh.',
        text: 'Tên BST · ngày ra mắt.',
        cta: '"Theo dõi để xem BST hoàn chỉnh."',
      }),
      v('Khách hàng mặc thử thật', 'VEO3', 'UGC khách mặc thử, nhận xét form – tăng tin tưởng.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'CUSTOMER: a 26-year-old Vietnamese woman, medium height, bob hair, casual.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `CUSTOMER opens a package at home and holds up [sản phẩm]. ${N}`, 'Khách: "Mình cao 1m58 nặng 50kg, mặc size M nè."'),
          sc('4–14s', 'MẶC THỬ', 'VEO3', `CUSTOMER wearing the item in front of a mirror, turns around. ${N}`, '"Form vừa, vải mát, không bị nhăn."'),
          sc('14–20s', 'KẾT', 'VEO3', `CUSTOMER gives a thumbs up. ${N}`, '"Ưng lắm, sẽ mua thêm màu khác."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Chiều cao / cân nặng / size mặc.',
        cta: '"Xem bảng size và đặt hàng."',
      }),
      v('Phong cách vintage – hoài cổ', 'Kling', 'Video thời trang vintage màu phim xưa.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'MODEL: a 23-year-old Vietnamese woman, wavy bob, wearing [sản phẩm: a polka dot vintage dress and beret].',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'MODEL rides a vintage bicycle along an old Hanoi street, film grain, warm faded colors.'),
          sc('5–11s', 'CHI TIẾT', 'Kling', 'MODEL sits in an old café, sipping coffee, close-up of dress details.'),
          sc('11–15s', 'KẾT', 'Kling', 'MODEL laughs, holding her beret in the wind.'),
        ],
        audio: 'nhạc jazz cổ điển.',
        text: 'Tên BST vintage · giá.',
        cta: '"Săn đồ vintage – link ở bio."',
      }),
    ],
  },

  {
    name: 'Nhà hàng & F&B',
    prompts: [
      v('Bánh mì nóng giòn buổi sáng', 'Kling', 'Video món sáng hấp dẫn, âm thanh giòn rụm.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Golden baguettes come out of an oven, steam rising, warm morning light. Macro.'),
          sc('4–10s', 'LÀM BÁNH', 'Kling', 'Hands slice the bread, spread pâté, add grilled pork, pickles, cilantro, chili. Quick cuts.'),
          sc('10–15s', 'THƯỞNG THỨC', 'Kling', 'A customer takes a big crunchy bite on a street corner.'),
        ],
        audio: 'ASMR: giòn rụm, nhạc vui nhỏ.',
        text: 'Tên tiệm · giá · giờ mở cửa.',
        cta: '"Ghé ăn sáng hoặc đặt qua [app]."',
      }),
      v('Lẩu nghi ngút ngày mưa', 'Kling, VEO3', 'Video lẩu kéo khách nhóm đông, đặc biệt mùa mưa.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'FRIENDS: four Vietnamese friends in their 20s in casual clothes.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Rain pouring outside a restaurant window, inside a bubbling hot pot with red broth, steam.'),
          sc('4–12s', 'NHÚNG LẨU', 'Kling', 'Chopsticks dip beef slices, mushrooms and seafood into the broth, close-up.'),
          sc('12–20s', 'KẾT', 'VEO3', `FRIENDS toast with drinks around the hot pot, laughing. ${N}`, 'Cả nhóm: "Trời mưa phải đi lẩu!"'),
        ],
        audio: 'tiếng mưa, nước lẩu sôi, nhạc vui.',
        text: 'Combo lẩu 4 người · giá.',
        cta: '"Đặt bàn nhóm qua [số điện thoại]."',
      }),
      v('Cà phê pha phin truyền thống', 'Kling', 'Video chậm rãi, cảm xúc cho quán cà phê truyền thống.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Macro: coffee drips slowly from an aluminum phin filter into a glass with condensed milk, morning light.'),
          sc('5–10s', 'KHUẤY', 'Kling', 'A spoon stirs, ice cubes dropped in, swirl of milk and coffee.'),
          sc('10–15s', 'KẾT', 'Kling', 'An old Hanoi street corner, someone sips the coffee on a small plastic stool.'),
        ],
        audio: 'tiếng nhỏ giọt, đá viên, nhạc trịnh nhẹ.',
        text: 'Tên quán · giá.',
        cta: '"Một ly cà phê sáng nay?"',
      }),
      v('Món mới ra mắt – teaser', 'Kling, VEO3', 'Teaser giấu món, gây tò mò trước ngày ra mắt.', {
        info: '12 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A dish covered by a silver cloche on a dark table, smoke leaking from under it, dramatic spotlight.'),
          sc('5–9s', 'HÉ LỘ', 'Kling', 'The cloche lifts slightly, glimpses of [món mới], then closes.'),
          sc('9–12s', 'KẾT', 'Kling', 'Black screen with steam.'),
        ],
        audio: 'nhạc bí ẩn.',
        text: '"Món mới – [ngày ra mắt]".',
        cta: '"Đoán xem là món gì? Comment nhé!"',
      }),
      v('Đầu bếp nói về món signature', 'VEO3, Kling', 'Đầu bếp chia sẻ câu chuyện món ăn – tăng giá trị.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'CHEF: a 50-year-old Vietnamese female chef, white chef coat, hair under a black cap, kind eyes.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `CHEF holds a plate of [món], faces the camera in the kitchen. ${N}`, 'Đầu bếp: "Món này là công thức của mẹ tôi, 30 năm không đổi."'),
          sc('5–20s', 'CHẾ BIẾN', 'Kling', 'Close-ups of CHEF cooking: marinating, grilling over charcoal, plating carefully.'),
          sc('20–30s', 'KẾT', 'VEO3', `CHEF serves the dish to a customer and smiles. ${N}`, '"Mời bạn đến thưởng thức."'),
        ],
        audio: 'nhạc ấm; SFX: than hồng, xèo xèo.',
        text: 'Tên món · giá.',
        cta: '"Đặt bàn để thưởng thức món signature."',
      }),
      v('Giao hàng tận nơi', 'Kling, VEO3', 'Video dịch vụ giao đồ ăn nhanh, nóng hổi.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'CUSTOMER: a 28-year-old Vietnamese man in office clothes at his desk.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `CUSTOMER at his office desk, stomach growls, looks at the camera. ${N}`, 'Khách: "Đói mà không muốn ra ngoài…"'),
          sc('4–10s', 'GIAO HÀNG', 'Kling', 'A delivery rider zooms through the city with a thermal bag, then hands over a hot meal box.'),
          sc('10–15s', 'KẾT', 'Kling', 'CUSTOMER opens the box, steam rises, he smiles.'),
        ],
        audio: 'nhạc vui; SFX: chuông cửa.',
        text: 'Giao trong [x] phút · khu vực giao.',
        cta: '"Đặt qua [app] hoặc gọi [số]."',
      }),
      v('Combo trưa văn phòng', 'Kling, VEO3', 'Video combo cơm trưa giá tốt cho dân văn phòng.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'OFFICE: three Vietnamese office workers in their late 20s with lanyards.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Top-down: a bento-style lunch tray with rice, braised pork, vegetables, soup, steam.'),
          sc('4–10s', 'KHÔNG KHÍ', 'VEO3', `OFFICE eat together at the restaurant, chatting happily. ${N}`, 'Một người: "Cơm ngon mà có 45 nghìn!"'),
          sc('10–15s', 'KẾT', 'Kling', 'Menu board with daily dishes, quick pan.'),
        ],
        audio: 'nhạc vui.',
        text: 'Combo trưa · giá · đổi món mỗi ngày.',
        cta: '"Đặt trước 11h để không phải chờ."',
      }),
      v('Tiệc sinh nhật tại nhà hàng', 'Kling, VEO3', 'Video gói tiệc sinh nhật / sự kiện.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'BIRTHDAY: a 30-year-old Vietnamese woman in a red dress. FRIENDS: a group of friends around her.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A decorated private room with balloons and fairy lights, staff bring a cake with sparklers.'),
          sc('5–12s', 'BẤT NGỜ', 'VEO3', `BIRTHDAY covers her mouth in surprise as FRIENDS sing. ${N}`, 'Bạn bè: "Chúc mừng sinh nhật!"'),
          sc('12–20s', 'TIỆC', 'Kling', 'Shared dishes on the table, toasting, laughing.'),
        ],
        audio: 'nhạc sinh nhật vui.',
        text: 'Gói tiệc · trang trí miễn phí.',
        cta: '"Inbox đặt tiệc sinh nhật."',
      }),
      v('Món chay thanh đạm', 'Kling', 'Video quán chay: thanh tịnh, tươi xanh.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Fresh vegetables, tofu and mushrooms arranged on a wooden table, soft natural light.'),
          sc('5–11s', 'CHẾ BIẾN', 'Kling', 'Colorful vegetarian dishes being plated beautifully, steam.'),
          sc('11–15s', 'KHÔNG GIAN', 'Kling', 'A peaceful restaurant with bamboo decor and a small fountain.'),
        ],
        audio: 'nhạc thiền nhẹ.',
        text: 'Tên quán · ngày rằm có ưu đãi.',
        cta: '"Ghé thưởng thức bữa chay thanh đạm."',
      }),
      v('Bánh ngọt – tiệm bánh', 'Kling', 'Video bánh kem / bánh ngọt bắt mắt.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Macro: cream piped onto a cake in a spiral, strawberries placed on top, pastel background.'),
          sc('5–10s', 'CẮT BÁNH', 'Kling', 'A knife cuts the cake revealing soft layers, slow motion.'),
          sc('10–15s', 'KẾT', 'Kling', 'A display case full of pastries in a cozy bakery.'),
        ],
        audio: 'nhạc ngọt ngào.',
        text: 'Đặt bánh sinh nhật · giá từ [giá].',
        cta: '"Đặt bánh trước 1 ngày."',
      }),
      v('Review quán của food blogger', 'VEO3', 'UGC review món ăn tự nhiên.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'BLOGGER: a 26-year-old Vietnamese man, round glasses, graphic T-shirt, expressive.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `BLOGGER at a restaurant table, points at a dish. ${N}`, 'Blogger: "Quán này đông nghẹt, xem có đáng không nha!"'),
          sc('4–18s', 'THỬ MÓN', 'VEO3', `BLOGGER tastes the dish, eyes widen, nods. ${N}`, '"Nước dùng đậm, thịt mềm, rau tươi… chấm 9 điểm!"'),
          sc('18–25s', 'KẾT', 'VEO3', `BLOGGER gives a thumbs up. ${N}`, '"Địa chỉ mình để ở bình luận."'),
        ],
        audio: 'nhạc vui.',
        text: 'Điểm đánh giá · giá · địa chỉ.',
        cta: '"Lưu lại và rủ bạn đi ăn!"',
      }),
      v('Trà sữa topping – tự chọn', 'Kling', 'Video quá trình chọn topping vui mắt.', {
        info: '12 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Rows of toppings: pearls, jelly, pudding, cheese foam, colorful, close-up.'),
          sc('4–9s', 'PHA', 'Kling', 'Scoops of each topping drop into a cup, milk tea poured, cheese foam on top.'),
          sc('9–12s', 'KẾT', 'Kling', 'A straw pierces the cup, pearls sucked up.'),
        ],
        audio: 'nhạc trend; SFX: "pop".',
        text: 'Tên món · giá.',
        cta: '"Bạn chọn topping gì? Comment nhé!"',
      }),
      v('Nguyên liệu tươi mỗi sáng', 'Kling, VEO3', 'Video chợ sáng – chứng minh nguyên liệu tươi.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'OWNER: a 40-year-old Vietnamese restaurant owner, short hair, apron, market basket.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '5am at a busy wet market, OWNER selects fresh fish and vegetables, morning light.'),
          sc('6–14s', 'CHỌN LỰA', 'Kling', 'Close-ups of fresh herbs, shrimp jumping, ripe tomatoes.'),
          sc('14–20s', 'KẾT', 'VEO3', `OWNER back at the kitchen, faces the camera. ${N}`, 'Chủ quán: "Nguyên liệu mua mỗi sáng, hết là nghỉ bán."'),
        ],
        audio: 'tiếng chợ, nhạc nhẹ.',
        text: '"Tươi mỗi ngày".',
        cta: '"Ghé quán để cảm nhận độ tươi."',
      }),
      v('Đồ ăn vặt giao nhanh', 'Kling, VEO3', 'Video món ăn vặt cho sinh viên.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'STUDENTS: two Vietnamese university students in a dorm room.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'A box of crispy fried chicken skin, fish balls and mango salad opened on a desk, steam.'),
          sc('4–10s', 'ĂN', 'VEO3', `STUDENTS share the snacks, laughing while studying. ${N}`, 'Sinh viên: "Ôn thi phải có đồ ăn vặt!"'),
          sc('10–15s', 'KẾT', 'Kling', 'Close-up of a crunchy bite.'),
        ],
        audio: 'nhạc vui; ASMR: giòn.',
        text: 'Combo sinh viên · giá.',
        cta: '"Freeship bán kính [x] km."',
      }),
    ],
  },

  {
    name: 'Bất động sản',
    prompts: [
      v('Căn hộ studio cho người trẻ', 'Kling, VEO3', 'Video căn hộ nhỏ tiện nghi cho người độc thân.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'YOUNG: a 26-year-old Vietnamese woman, casual hoodie, AirPods.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `YOUNG opens the door of a cozy studio apartment, turns to the camera. ${N}`, 'Cô gái: "Căn hộ đầu tiên của mình – 35m² mà đủ hết!"'),
          sc('4–14s', 'KHÔNG GIAN', 'Kling', '[Ảnh thật] Smooth walk through the studio: compact kitchen, loft bed, work desk by the window.'),
          sc('14–20s', 'KẾT', 'Kling', 'YOUNG relaxes by the window at night with city lights.'),
        ],
        audio: 'lo-fi.',
        text: 'Diện tích · giá thuê / bán · vị trí.',
        cta: '"Inbox xem căn thực tế."',
      }),
      v('Nhà phố thương mại (shophouse)', 'Kling', 'Video shophouse nhấn tiềm năng kinh doanh.', {
        info: '20 giây · ngang 16:9 hoặc dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Drone shot of a row of modern shophouses on a busy boulevard at dusk, shop lights glowing.'),
          sc('5–12s', 'KINH DOANH', 'Kling', 'Ground floor café busy with customers, people walking by.'),
          sc('12–20s', 'Ở TRÊN', 'Kling', 'Upper floors: a modern family living space with balcony.'),
        ],
        audio: 'nhạc hiện đại.',
        text: 'Mặt tiền · số tầng · giá · "Hình ảnh minh họa".',
        cta: '"Đăng ký nhận bảng giá."',
      }),
      v('Đất nền – tiềm năng khu vực', 'Kling, VEO3', 'Video vị trí đất nền và hạ tầng (không cam kết lợi nhuận).', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'BROKER: a 36-year-old Vietnamese man, white shirt, sunglasses, holding a map.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Drone shot over planned land plots with new roads, green parks nearby, sunny.'),
          sc('6–15s', 'HẠ TẦNG', 'Kling', 'Aerial view of a new highway and a bridge connecting to the area.'),
          sc('15–25s', 'TƯ VẤN', 'VEO3', `BROKER stands on site, faces the camera. ${N}`, 'Môi giới: "Sổ riêng từng nền, đường đã nhựa. Kiểm tra pháp lý kỹ trước khi mua nha."'),
        ],
        audio: 'nhạc hùng tráng nhẹ.',
        text: 'Diện tích · pháp lý · giá · "Thông tin tham khảo".',
        cta: '"Đặt lịch xem đất thực tế."',
      }),
      v('Biệt thự nghỉ dưỡng', 'Kling', 'Video biệt thự cao cấp, sang trọng.', {
        info: '30 giây · ngang 16:9 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Drone reveals a luxury villa with a private pool by the sea at sunset.'),
          sc('6–16s', 'NỘI THẤT', 'Kling', 'Gimbal glide through a double-height living room, marble floor, ocean view.'),
          sc('16–24s', 'HỒ BƠI', 'Kling', 'Infinity pool at blue hour with lights glowing.'),
          sc('24–30s', 'KẾT', 'Kling', 'Night aerial view of the villa lit up.'),
        ],
        audio: 'nhạc sang trọng.',
        text: 'Tên dự án · "Hình ảnh minh họa".',
        cta: '"Liên hệ để nhận thông tin độc quyền."',
      }),
      v('Cho thuê văn phòng', 'Kling, VEO3', 'Video văn phòng cho doanh nghiệp.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'MANAGER: a 35-year-old Vietnamese woman, black blazer, building manager badge.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Glass office tower lobby with reception, people walking in.'),
          sc('5–12s', 'VĂN PHÒNG', 'Kling', '[Ảnh thật] Open-plan office floor with city view, meeting rooms.'),
          sc('12–20s', 'TƯ VẤN', 'VEO3', `MANAGER faces the camera in a meeting room. ${N}`, 'Quản lý: "Diện tích từ 50m², có sẵn nội thất, vào làm ngay."'),
        ],
        audio: 'nhạc doanh nghiệp.',
        text: 'Diện tích · giá thuê · vị trí.',
        cta: '"Đặt lịch xem văn phòng."',
      }),
      v('Nhà mẫu – trải nghiệm', 'Kling', 'Video nhà mẫu dự án mới.', {
        info: '25 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Doors of a model apartment open, light floods in.'),
          sc('5–20s', 'THAM QUAN', 'Kling', 'Smooth walkthrough of the model unit: living room, kitchen, bedroom, kids room.'),
          sc('20–25s', 'KẾT', 'Kling', 'Balcony view of the project at sunset.'),
        ],
        audio: 'piano thanh lịch.',
        text: 'Loại căn · diện tích · "Nhà mẫu – nội thất tham khảo".',
        cta: '"Đăng ký tham quan nhà mẫu."',
      }),
      v('Kinh nghiệm thuê nhà lần đầu', 'VEO3', 'Video kiến thức xây thương hiệu môi giới cho thuê.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'AGENT: a 28-year-old Vietnamese woman, ponytail, denim jacket, clipboard.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `AGENT in an empty apartment, faces the camera. ${N}`, 'Môi giới: "Thuê nhà lần đầu, nhớ kiểm tra 4 thứ này!"'),
          sc('4–24s', '4 ĐIỀU', 'VEO3', `AGENT checks the water tap, electricity meter, door lock and window, explaining each. ${N}`, '"Nước, điện, khóa cửa, và hợp đồng ghi rõ tiền cọc."'),
          sc('24–30s', 'CTA', 'VEO3', `AGENT smiles. ${N}`, '"Cần tìm phòng, inbox mình nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '4 điều cần kiểm tra.',
        cta: '"Theo dõi để xem thêm kinh nghiệm thuê nhà."',
      }),
      v('Tiến độ xây dựng dự án', 'Kling', 'Cập nhật tiến độ minh bạch cho khách đã mua.', {
        info: '20 giây · ngang 16:9 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Drone shot of a residential tower under construction with cranes, morning.'),
          sc('6–14s', 'CÔNG TRƯỜNG', 'Kling', 'Workers on site, concrete pouring, safety gear.'),
          sc('14–20s', 'KẾT', 'Kling', 'Timelapse of the tower rising floor by floor.'),
        ],
        audio: 'nhạc mạnh mẽ.',
        text: 'Tiến độ tháng [tháng] (đúng thực tế).',
        cta: '"Theo dõi cập nhật hàng tháng."',
      }),
      v('Căn hộ cho gia đình có trẻ nhỏ', 'Kling, VEO3', 'Nhấn tiện ích an toàn, trường học, khu vui chơi.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'MOM: a 32-year-old Vietnamese mother, ponytail, light dress. KID: her 6-year-old son.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'KID rides a scooter safely in a car-free internal park.'),
          sc('6–15s', 'TIỆN ÍCH', 'Kling', 'Kids playground, kids pool, a school inside the complex.'),
          sc('15–25s', 'MẸ CHIA SẺ', 'VEO3', `MOM sits on a bench watching KID, speaks to the camera. ${N}`, 'Mẹ: "Điều mình cần nhất là con được chơi an toàn."'),
        ],
        audio: 'nhạc ấm.',
        text: 'Tiện ích cho trẻ (đúng thực tế).',
        cta: '"Đặt lịch tham quan cùng gia đình."',
      }),
      v('Bán nhà gấp – thông tin rõ ràng', 'VEO3, Kling', 'Video tin bán nhà nhanh, minh bạch.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'SELLER: a 45-year-old Vietnamese man, polo shirt, standing in front of a house.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `SELLER in front of a townhouse gate. ${N}`, 'Chủ nhà: "Cần bán gấp nhà 4 tầng, giá thương lượng."'),
          sc('4–16s', 'THAM QUAN', 'Kling', '[Ảnh thật] Quick tour: living room, kitchen, bedrooms, rooftop.'),
          sc('16–20s', 'KẾT', 'VEO3', `SELLER nods. ${N}`, '"Sổ hồng chính chủ, gọi tôi để xem nhà."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Diện tích · số tầng · giá · pháp lý.',
        cta: '"Gọi [số] để xem nhà."',
      }),
      v('So sánh 2 căn hộ', 'VEO3, Kling', 'Giúp khách chọn căn phù hợp.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'ADVISOR: a 30-year-old Vietnamese woman, glasses, navy blazer.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `ADVISOR faces the camera. ${N}`, 'Tư vấn: "Căn góc hay căn giữa – chọn căn nào?"'),
          sc('4–14s', 'CĂN GÓC', 'Kling', '[Ảnh thật] Corner unit with two-side windows, lots of light.'),
          sc('14–24s', 'CĂN GIỮA', 'Kling', '[Ảnh thật] Middle unit, quieter, better price.'),
          sc('24–30s', 'KẾT', 'VEO3', `ADVISOR smiles. ${N}`, '"Tùy nhu cầu, inbox để mình tư vấn kỹ nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Bảng so sánh ngắn.',
        cta: '"Nhận tư vấn chọn căn."',
      }),
      v('Khách hàng nhận nhà', 'Kling, VEO3', 'Khoảnh khắc bàn giao – cảm xúc thật.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'COUPLE: a young Vietnamese couple in their early 30s, casual neat clothes.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'COUPLE receive a key with a red ribbon from a staff member, smiling.'),
          sc('6–14s', 'VÀO NHÀ', 'Kling', 'COUPLE open the door of their empty new apartment, walk in amazed.'),
          sc('14–20s', 'KẾT', 'VEO3', `COUPLE hug by the window and look at the camera. ${N}`, 'Cặp đôi: "Tổ ấm đầu tiên của tụi mình!"'),
        ],
        audio: 'nhạc ấm áp.',
        text: 'Tên dự án · "Chúc mừng gia chủ".',
        cta: '"Bạn cũng muốn có tổ ấm? Inbox ngay."',
      }),
      v('Cho thuê căn hộ dịch vụ', 'Kling', 'Video căn hộ dịch vụ đầy đủ nội thất.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh thật] A serviced apartment with a made bed and welcome flowers.'),
          sc('4–11s', 'TIỆN NGHI', 'Kling', 'Washing machine, kitchen, gym and housekeeping staff cleaning.'),
          sc('11–15s', 'KẾT', 'Kling', 'Night view from the window.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Giá thuê/tháng · dịch vụ bao gồm.',
        cta: '"Inbox xem phòng."',
      }),
      v('Phong thủy khi chọn nhà', 'VEO3', 'Video kiến thức phổ thông, tăng tương tác.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'EXPERT: a 50-year-old Vietnamese man, glasses, traditional-style shirt.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `EXPERT in a living room. ${N}`, 'Chuyên gia: "3 điều nhiều người quan tâm khi chọn nhà."'),
          sc('5–24s', 'NỘI DUNG', 'VEO3', `EXPERT points at a window, main door, kitchen. ${N}`, '"Nhà thoáng, nhiều ánh sáng; cửa chính không bị chắn; bếp gọn gàng, sạch sẽ."'),
          sc('24–30s', 'KẾT', 'VEO3', `EXPERT smiles. ${N}`, '"Quan trọng nhất vẫn là phù hợp với gia đình bạn."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Bạn quan tâm điều gì khi chọn nhà?"',
      }),
    ],
  },
];
