// Bổ sung kịch bản video AI (14 / ngành) – phần 3.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Nội thất & Xây dựng',
    prompts: [
      v('Bếp hiện đại – trước & sau cải tạo', 'Kling', 'Biến hình căn bếp cũ thành bếp mới.', {
        info: '15 giây · dọc 9:16 · Kling (start frame + end frame)',
        scenes: [
          sc('0–4s', 'TRƯỚC', 'Kling', '[Ảnh bếp cũ thật] An old cramped kitchen with worn cabinets, dim light.'),
          sc('4–11s', 'BIẾN HÌNH', 'Kling', 'Start frame: old kitchen. End frame: modern white kitchen with wood accents and an island. Cabinets transform, lights turn on, smooth.'),
          sc('11–15s', 'SAU', 'Kling', 'Slow push into the new kitchen, warm light, a family cooking.'),
        ],
        audio: 'nhạc dâng; SFX: whoosh.',
        text: '"Trước" / "Sau" · thời gian thi công.',
        cta: '"Nhận báo giá cải tạo bếp."',
      }),
      v('Phòng ngủ cho bé', 'Kling', 'Video phòng trẻ em màu sắc, an toàn.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A pastel kids bedroom with a house-shaped bed, fairy lights, toys, soft daylight.'),
          sc('5–11s', 'CHI TIẾT', 'Kling', 'Close-ups: rounded furniture corners, reading nook, storage drawers.'),
          sc('11–15s', 'KẾT', 'Kling', 'A little girl jumps onto the bed happily.'),
        ],
        audio: 'nhạc thiếu nhi nhẹ.',
        text: 'Thiết kế phòng bé · vật liệu an toàn.',
        cta: '"Nhận phối cảnh phòng bé miễn phí."',
      }),
      v('Thiết kế quán cà phê', 'Kling, VEO3', 'Video giới thiệu công trình quán cà phê đã thi công.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'OWNER: a 30-year-old Vietnamese café owner, beanie, apron.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '[Ảnh thật] Exterior of a stylish café with plants and a neon sign at dusk.'),
          sc('6–16s', 'KHÔNG GIAN', 'Kling', 'Walkthrough: exposed brick, wooden tables, hanging plants, customers chatting.'),
          sc('16–25s', 'CHỦ QUÁN', 'VEO3', `OWNER behind the bar, faces the camera. ${N}`, 'Chủ quán: "Thiết kế đẹp nên khách check-in liên tục."'),
        ],
        audio: 'nhạc chill.',
        text: 'Công trình · diện tích · thời gian thi công.',
        cta: '"Tư vấn thiết kế quán miễn phí."',
      }),
      v('Vật liệu gỗ – câu chuyện xưởng', 'Kling', 'Video xưởng mộc thủ công, tăng giá trị nội thất.', {
        info: '25 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Sawdust flies in sunlight beams in a carpentry workshop, slow motion.'),
          sc('6–18s', 'CHẾ TÁC', 'Kling', 'Craftsman hands sanding, joining wood pieces, applying oil finish, close-ups.'),
          sc('18–25s', 'THÀNH PHẨM', 'Kling', 'The finished oak dining table in a bright home.'),
        ],
        audio: 'nhạc mộc; SFX: tiếng bào gỗ.',
        text: 'Loại gỗ · bảo hành.',
        cta: '"Đặt đóng nội thất theo kích thước nhà bạn."',
      }),
      v('Mẹo làm nhà nhỏ rộng hơn', 'VEO3', 'Video kiến thức nội thất dễ áp dụng.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'DESIGNER: a 32-year-old Vietnamese male interior designer, beard, black T-shirt, measuring tape.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `DESIGNER in a small living room. ${N}`, 'Nhà thiết kế: "Nhà 40m² trông như 60m² – làm thế này!"'),
          sc('4–24s', 'MẸO', 'VEO3', `DESIGNER points at a large mirror, light curtains, wall shelves. ${N}`, '"Gương lớn, rèm sáng màu, kệ treo tường thay tủ to."'),
          sc('24–30s', 'KẾT', 'VEO3', `DESIGNER smiles. ${N}`, '"Lưu lại để áp dụng nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '3 mẹo chính.',
        cta: '"Gửi ảnh nhà bạn để được góp ý."',
      }),
      v('Chống thấm – vấn đề & giải pháp', 'Kling, VEO3', 'Video dịch vụ chống thấm.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'WORKER: a 40-year-old Vietnamese technician, blue uniform, helmet.',
        scenes: [
          sc('0–5s', 'VẤN ĐỀ', 'Kling', 'A damp wall with peeling paint and mold, water dripping from the ceiling.'),
          sc('5–14s', 'XỬ LÝ', 'Kling', 'WORKER applies waterproof coating on a rooftop with a roller.'),
          sc('14–20s', 'KẾT', 'VEO3', `WORKER faces the camera. ${N}`, 'Kỹ thuật viên: "Bảo hành [x] năm, thấm lại làm lại miễn phí."'),
        ],
        audio: 'tiếng mưa → nhạc nhẹ.',
        text: 'Dịch vụ chống thấm · bảo hành.',
        cta: '"Gọi khảo sát miễn phí."',
      }),
      v('Showroom gạch & thiết bị vệ sinh', 'Kling', 'Video showroom vật liệu.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Glide into a bright showroom with tiles displayed on walls.'),
          sc('5–15s', 'SẢN PHẨM', 'Kling', 'Close-ups: marble-look tiles, a modern bathroom set, a rain shower.'),
          sc('15–20s', 'KẾT', 'Kling', 'A complete bathroom display with warm light.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Thương hiệu · ưu đãi.',
        cta: '"Ghé showroom để xem mẫu thật."',
      }),
      v('Nhà phố 3 tầng – hoàn thiện', 'Kling', 'Video công trình nhà phố đã bàn giao.', {
        info: '30 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '[Ảnh thật] Facade of a modern 3-story townhouse at dusk, lights on.'),
          sc('6–20s', 'TỪNG TẦNG', 'Kling', 'Walkthrough: ground floor living room, stairs with skylight, bedrooms, rooftop garden.'),
          sc('20–30s', 'KẾT', 'Kling', 'Aerial view of the rooftop garden at sunset.'),
        ],
        audio: 'piano.',
        text: 'Diện tích · chi phí tham khảo · thời gian thi công.',
        cta: '"Nhận báo giá xây nhà trọn gói."',
      }),
      v('Đèn trang trí – không khí ấm', 'Kling', 'Video đèn decor tạo không khí.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A dark living room, pendant lights turn on one by one, warm glow.'),
          sc('5–11s', 'SẢN PHẨM', 'Kling', '[Ảnh thật] Close-up of the rattan pendant light casting patterned shadows.'),
          sc('11–15s', 'KẾT', 'Kling', 'A couple relaxes on the sofa under the warm light.'),
        ],
        audio: 'nhạc ấm.',
        text: 'Mẫu đèn · giá.',
        cta: '"Mua đèn – giao lắp tận nơi."',
      }),
      v('Kiến trúc sư phỏng vấn khách hàng', 'VEO3', 'Testimonial chủ nhà về dịch vụ thiết kế.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'HOMEOWNER: a 40-year-old Vietnamese woman, linen shirt, in her finished living room.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `HOMEOWNER sits on her sofa. ${N}`, 'Chủ nhà: "Mình từng lo nhất là phát sinh chi phí."'),
          sc('5–18s', 'TRẢI NGHIỆM', 'VEO3', `HOMEOWNER explains with a calm smile. ${N}`, '"Nhưng báo giá rõ từ đầu, đúng tiến độ, nhà đẹp hơn bản vẽ."'),
          sc('18–25s', 'KẾT', 'VEO3', `HOMEOWNER gestures around the room. ${N}`, '"Rất hài lòng!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Tên công trình.',
        cta: '"Đặt lịch tư vấn."',
      }),
      v('Ban công – vườn nhỏ trên cao', 'Kling', 'Video thiết kế ban công xanh.', {
        info: '15 giây · dọc 9:16 · Kling (start + end frame)',
        scenes: [
          sc('0–4s', 'TRƯỚC', 'Kling', 'An empty bare apartment balcony with concrete floor.'),
          sc('4–11s', 'BIẾN HÌNH', 'Kling', 'Start: bare balcony. End: green balcony garden with wooden deck, plants, a small table. Smooth transformation.'),
          sc('11–15s', 'SAU', 'Kling', 'Someone sips tea on the new balcony at sunset.'),
        ],
        audio: 'nhạc thư giãn.',
        text: 'Gói thiết kế ban công · giá.',
        cta: '"Inbox nhận ý tưởng ban công."',
      }),
      v('Sơn nhà – chọn màu', 'Kling', 'So sánh màu sơn cho cùng một căn phòng.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'A living room with white walls, static wide shot.'),
          sc('4–12s', 'ĐỔI MÀU', 'Kling', 'The walls change color smoothly: sage green, warm beige, soft blue.'),
          sc('12–15s', 'KẾT', 'Kling', 'Close-up of a paint roller on the wall.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Tên mã màu.',
        cta: '"Bạn thích màu nào? Comment nhé!"',
      }),
      v('An toàn lao động tại công trình', 'Kling, VEO3', 'Video thể hiện sự chuyên nghiệp của nhà thầu.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'SUPERVISOR: a 45-year-old Vietnamese site supervisor, white helmet, reflective vest.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Workers wearing harnesses and helmets at a construction site, morning briefing.'),
          sc('6–14s', 'QUY TRÌNH', 'Kling', 'Safety checks: scaffolding, fire extinguishers, signage.'),
          sc('14–20s', 'KẾT', 'VEO3', `SUPERVISOR faces the camera. ${N}`, 'Giám sát: "An toàn là ưu tiên số một ở mọi công trình."'),
        ],
        audio: 'nhạc mạnh mẽ.',
        text: 'Cam kết an toàn.',
        cta: '"Chọn nhà thầu uy tín – liên hệ ngay."',
      }),
      v('Nội thất thông minh cho nhà nhỏ', 'Kling', 'Video đồ đa năng: giường gấp, bàn xếp.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A wall cabinet folds down into a bed smoothly in a small studio.'),
          sc('5–11s', 'ĐA NĂNG', 'Kling', 'A wall-mounted table folds out, a sofa slides into a guest bed.'),
          sc('11–15s', 'KẾT', 'Kling', 'The room is spacious again, someone does yoga.'),
        ],
        audio: 'nhạc vui; SFX: "click".',
        text: 'Tiết kiệm diện tích · giá.',
        cta: '"Xem mẫu tại showroom."',
      }),
    ],
  },

  {
    name: 'Giáo dục & Đào tạo',
    prompts: [
      v('Mẹo học từ vựng tiếng Anh', 'VEO3', 'Video kiến thức ngắn, giáo viên hướng dẫn.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'TEACHER: a 27-year-old Vietnamese female English teacher, curly hair, yellow cardigan.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `TEACHER holds a small notebook. ${N}`, 'Giáo viên: "Học 10 từ mỗi ngày mà không quên – thử cách này!"'),
          sc('4–24s', 'MẸO', 'VEO3', `TEACHER writes on sticky notes and puts them on objects around a room. ${N}`, '"Dán từ vựng lên đồ vật, đặt câu với từ mới, ôn lại sau 1 ngày, 3 ngày, 7 ngày."'),
          sc('24–30s', 'KẾT', 'VEO3', `TEACHER smiles. ${N}`, '"Thử ngay hôm nay nhé!"'),
        ],
        audio: 'nhạc vui.',
        text: '3 bước học từ vựng.',
        cta: '"Theo dõi để học tiếng Anh mỗi ngày."',
      }),
      v('Toán vui cho bé (hoạt hình)', 'Kling, ElevenLabs', 'Hoạt hình dạy phép cộng cho trẻ.', {
        info: '30 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '3D animation: a cute monkey holds 2 bananas, bright jungle.', 'Lời kể: "Khỉ con có 2 quả chuối…"'),
          sc('6–16s', 'PHÉP TÍNH', 'Kling', '3D animation: a parrot brings 3 more bananas, they line up with glowing numbers.', '"Bạn vẹt cho thêm 3 quả. Vậy khỉ có tất cả mấy quả?"'),
          sc('16–24s', 'ĐÁP ÁN', 'Kling', '3D animation: the bananas count 1 to 5 with sparkles.', '"Một, hai, ba, bốn, năm! 2 cộng 3 bằng 5!"'),
          sc('24–30s', 'KẾT', 'Kling', '3D animation: monkey and parrot dance happily.'),
        ],
        audio: 'nhạc thiếu nhi.',
        text: '2 + 3 = 5',
        cta: '"Cho bé xem thêm tập khác nhé!"',
      }),
      v('Giới thiệu giáo viên', 'VEO3', 'Giáo viên tự giới thiệu – tạo kết nối với phụ huynh / học viên.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'TEACHER: a 30-year-old Vietnamese male math teacher, glasses, light blue shirt.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `TEACHER at a whiteboard with equations. ${N}`, 'Giáo viên: "Chào các em, thầy là [tên], 8 năm dạy Toán."'),
          sc('5–18s', 'PHƯƠNG PHÁP', 'VEO3', `TEACHER explains with a marker. ${N}`, '"Thầy dạy bằng ví dụ đời thường, để các em hiểu chứ không học thuộc."'),
          sc('18–25s', 'KẾT', 'VEO3', `TEACHER smiles. ${N}`, '"Hẹn gặp các em trong lớp!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Kinh nghiệm · thành tích (đúng thực tế).',
        cta: '"Đăng ký học thử với thầy."',
      }),
      v('Ôn thi cấp tốc', 'VEO3, Kling', 'Video khóa ôn thi trước kỳ thi.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'STUDENT: a 17-year-old Vietnamese high school girl, ponytail, white uniform.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `STUDENT stressed at a desk piled with books at night. ${N}`, 'Học sinh: "Còn 30 ngày nữa là thi rồi…"'),
          sc('4–14s', 'KHÓA HỌC', 'Kling', 'Classroom with focused students, teacher explaining exam tips on the board.'),
          sc('14–20s', 'KẾT', 'Kling', 'STUDENT walks out of an exam room smiling.'),
        ],
        audio: 'nhạc hồi hộp → tươi sáng.',
        text: 'Lịch ôn · số buổi · học phí.',
        cta: '"Đăng ký lớp ôn cấp tốc."',
      }),
      v('Kỹ năng mềm: Thuyết trình tự tin', 'VEO3', 'Video tuyển sinh khóa kỹ năng.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'TRAINER: a 35-year-old Vietnamese woman, short hair, red blazer, confident.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `TRAINER on a small stage. ${N}`, 'Giảng viên: "Run khi đứng trước đám đông? 3 mẹo này giúp bạn."'),
          sc('4–20s', 'MẸO', 'VEO3', `TRAINER demonstrates breathing, eye contact, pausing. ${N}`, '"Hít thở sâu, nhìn vào 3 điểm trong phòng, và dám dừng lại 2 giây."'),
          sc('20–25s', 'KẾT', 'VEO3', `TRAINER smiles at the camera. ${N}`, '"Khóa thuyết trình khai giảng [ngày]."'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: '3 mẹo thuyết trình.',
        cta: '"Đăng ký giữ chỗ."',
      }),
      v('Du học – hành trình', 'Kling, VEO3', 'Video tư vấn du học cảm xúc.', {
        info: '30 giây · dọc 9:16 · Kling + VEO3',
        character: 'STUDENT: a 19-year-old Vietnamese woman, long hair, beige coat, suitcase.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'STUDENT hugs her parents at the airport, holding a passport.'),
          sc('6–18s', 'DU HỌC', 'Kling', 'STUDENT walks across a university campus abroad in autumn, studying in a library.'),
          sc('18–30s', 'KẾT', 'VEO3', `STUDENT video calls her parents from her dorm, smiling. ${N}`, 'Du học sinh: "Con ổn lắm, ba mẹ yên tâm nha!"'),
        ],
        audio: 'nhạc cảm động.',
        text: 'Quốc gia · học bổng.',
        cta: '"Nhận tư vấn du học miễn phí."',
      }),
      v('Lớp vẽ cho trẻ em', 'Kling', 'Video lớp năng khiếu nghệ thuật.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Kids with paint on their hands laughing in a bright art studio.'),
          sc('5–11s', 'VẼ', 'Kling', 'Close-ups of colorful brush strokes, a child painting a sunflower.'),
          sc('11–15s', 'KẾT', 'Kling', 'Kids hold up their paintings proudly.'),
        ],
        audio: 'nhạc vui.',
        text: 'Lịch học · độ tuổi.',
        cta: '"Đăng ký buổi vẽ thử miễn phí."',
      }),
      v('Học online tại nhà', 'Kling, VEO3', 'Video khóa học online linh hoạt cho người đi làm.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'WORKER: a 30-year-old Vietnamese office worker, casual home clothes, laptop.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `WORKER on the sofa at night with a laptop. ${N}`, 'Người đi làm: "Đi làm cả ngày, tối học 30 phút là đủ."'),
          sc('5–14s', 'HỌC', 'Kling', 'Screen showing a video lesson, WORKER taking notes, cup of tea.'),
          sc('14–20s', 'KẾT', 'Kling', 'WORKER receives a certificate email, smiles.'),
        ],
        audio: 'lo-fi.',
        text: 'Học mọi lúc · chứng chỉ.',
        cta: '"Học thử bài đầu tiên miễn phí."',
      }),
      v('Lịch sử Việt Nam 60 giây', 'Kling, ElevenLabs', 'Video kể chuyện lịch sử bằng hình ảnh điện ảnh.', {
        info: '45 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–8s', 'MỞ ĐẦU', 'Kling', 'Cinematic: the Bach Dang river at dawn, mist, wooden stakes hidden under water.', 'Lời kể: "Năm 938, trên sông Bạch Đằng…"'),
          sc('8–25s', 'TRẬN ĐÁNH', 'Kling', 'Cinematic: the tide goes out, enemy warships get stuck on the stakes, small Vietnamese boats attack.', '"Ngô Quyền cho cắm cọc gỗ, chờ thủy triều rút để đánh tan quân Nam Hán."'),
          sc('25–45s', 'KẾT', 'Kling', 'Cinematic: sunrise over the river, victory flags.', '"Chiến thắng mở ra thời kỳ độc lập lâu dài cho dân tộc."'),
        ],
        audio: 'nhạc sử thi, trống trận.',
        text: 'Năm · nhân vật · sự kiện (kiểm tra tư liệu trước khi đăng).',
        cta: '"Theo dõi để xem thêm câu chuyện lịch sử."',
      }),
      v('Hỏi nhanh đáp gọn (quiz)', 'VEO3', 'Video đố vui kiến thức có tương tác.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'HOST: a 25-year-old Vietnamese man, bright shirt, energetic quiz host.',
        scenes: [
          sc('0–5s', 'CÂU HỎI', 'VEO3', `HOST in a colorful studio. ${N}`, 'MC: "Con vật nào ngủ nhiều nhất thế giới?"'),
          sc('5–12s', 'ĐÁP ÁN GỢI Ý', 'VEO3', `HOST shows three cards. ${N}`, '"A: Mèo. B: Gấu túi Koala. C: Lười."'),
          sc('12–20s', 'ĐÁP ÁN', 'VEO3', `HOST flips the card. ${N}`, '"Đáp án B – Koala ngủ tới khoảng 20 tiếng mỗi ngày!"'),
        ],
        audio: 'nhạc đố vui; SFX: tích tắc.',
        text: 'Câu hỏi + 3 đáp án.',
        cta: '"Bạn trả lời đúng không? Comment nhé!"',
      }),
      v('Ngày khai giảng', 'Kling', 'Video không khí khai giảng của trường / trung tâm.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Students in uniforms gather in a school yard, balloons released into the sky.'),
          sc('5–14s', 'KHÔNG KHÍ', 'Kling', 'Teachers welcome students, friends hugging, flag ceremony.'),
          sc('14–20s', 'KẾT', 'Kling', 'Students run into classrooms laughing.'),
        ],
        audio: 'nhạc tươi vui.',
        text: '"Chào năm học mới [năm]".',
        cta: '"Tuyển sinh năm học mới – đăng ký ngay."',
      }),
      v('Phụ huynh chia sẻ', 'VEO3', 'Testimonial của phụ huynh về sự tiến bộ của con.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'PARENT: a 38-year-old Vietnamese mother, neat bob hair, cream blouse.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `PARENT sits in a living room. ${N}`, 'Phụ huynh: "Trước đây bé nhà mình rất ngại nói tiếng Anh."'),
          sc('5–18s', 'CHIA SẺ', 'VEO3', `PARENT smiles proudly. ${N}`, '"Sau 6 tháng, bé tự tin giới thiệu bản thân với khách nước ngoài."'),
          sc('18–25s', 'KẾT', 'VEO3', `PARENT nods. ${N}`, '"Cảm ơn thầy cô rất nhiều."'),
        ],
        audio: 'nhạc ấm.',
        text: 'Tên trung tâm.',
        cta: '"Đăng ký kiểm tra trình độ miễn phí."',
      }),
      v('Thí nghiệm khoa học vui', 'Kling, VEO3', 'Video STEM cho trẻ em.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'SCIENTIST: a 28-year-old Vietnamese female teacher in a white lab coat and safety goggles.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `SCIENTIST holds a bottle and baking soda. ${N}`, 'Cô giáo: "Làm núi lửa phun trào tại nhà nè!"'),
          sc('4–16s', 'THÍ NGHIỆM', 'Kling', 'Vinegar poured into a clay volcano with baking soda, red foam erupts, kids cheering.'),
          sc('16–25s', 'GIẢI THÍCH', 'VEO3', `SCIENTIST explains. ${N}`, '"Giấm gặp baking soda tạo ra khí CO2 nên bọt trào lên."'),
        ],
        audio: 'nhạc vui; SFX: sủi bọt.',
        text: 'Nguyên liệu · lưu ý có người lớn đi cùng.',
        cta: '"Đăng ký lớp STEM cuối tuần."',
      }),
      v('Lộ trình học rõ ràng', 'Kling, VEO3', 'Video minh họa lộ trình từ cơ bản đến nâng cao.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'ADVISOR: a 29-year-old Vietnamese woman, glasses, school polo shirt.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '3D animation: a path with milestones climbing up a mountain, a student character walking.'),
          sc('5–14s', 'LỘ TRÌNH', 'Kling', '3D animation: milestones light up – Cơ bản, Trung cấp, Nâng cao, Chứng chỉ.'),
          sc('14–20s', 'TƯ VẤN', 'VEO3', `ADVISOR faces the camera. ${N}`, 'Tư vấn viên: "Kiểm tra đầu vào miễn phí để biết bạn bắt đầu từ đâu."'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: 'Các cấp độ.',
        cta: '"Đặt lịch kiểm tra đầu vào."',
      }),
    ],
  },

  {
    name: 'Du lịch & Khách sạn',
    prompts: [
      v('Tour Sapa mùa lúa chín', 'Kling, VEO3', 'Video tour theo mùa – thời điểm vàng.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'TRAVELER: a 27-year-old Vietnamese woman, colorful H\'Mong-inspired scarf, backpack.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Drone over golden rice terraces in Sapa in September, clouds rolling.'),
          sc('6–15s', 'TRẢI NGHIỆM', 'Kling', 'TRAVELER trekking with a local guide, children waving, wooden houses.'),
          sc('15–25s', 'KẾT', 'VEO3', `TRAVELER on a hilltop overlooking the terraces. ${N}`, 'Du khách: "Mùa vàng chỉ có một lần trong năm!"'),
        ],
        audio: 'nhạc dân tộc hiện đại.',
        text: 'Tour 3N2Đ · tháng 9–10 · giá.',
        cta: '"Đặt tour mùa lúa chín."',
      }),
      v('Khách sạn – check-in nhanh', 'Kling, VEO3', 'Video trải nghiệm dịch vụ khách sạn.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'RECEPTIONIST: a 25-year-old Vietnamese woman, hotel uniform, neat bun. GUEST: a businessman with a suitcase.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh thật] Grand hotel lobby with chandelier, GUEST walks in.'),
          sc('5–12s', 'CHECK-IN', 'VEO3', `RECEPTIONIST hands GUEST a key card with a welcome drink. ${N}`, 'Lễ tân: "Chào mừng anh, phòng đã sẵn sàng."'),
          sc('12–20s', 'PHÒNG', 'Kling', '[Ảnh thật] The guest room with city view, GUEST relaxes.'),
        ],
        audio: 'nhạc sang trọng.',
        text: 'Hạng phòng · giá ưu đãi.',
        cta: '"Đặt trực tiếp nhận ưu đãi tốt nhất."',
      }),
      v('Du lịch biển mùa hè', 'Kling', 'Video mùa hè sôi động.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Friends run into turquoise water at Phu Quoc, splashing, slow motion.'),
          sc('5–14s', 'HOẠT ĐỘNG', 'Kling', 'Snorkeling with colorful fish, jet ski, beach volleyball.'),
          sc('14–20s', 'KẾT', 'Kling', 'Sunset beach party with lanterns.'),
        ],
        audio: 'nhạc hè sôi động.',
        text: 'Combo vé máy bay + khách sạn · giá.',
        cta: '"Săn combo hè ngay."',
      }),
      v('Glamping – cắm trại sang trọng', 'Kling', 'Video glamping giữa thiên nhiên.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A white bell tent glowing among pine trees at dusk.'),
          sc('5–14s', 'TRẢI NGHIỆM', 'Kling', 'Inside the tent: cozy bed, fairy lights; outside: BBQ and campfire with friends.'),
          sc('14–20s', 'KẾT', 'Kling', 'Starry sky timelapse above the tents.'),
        ],
        audio: 'guitar; SFX: lửa trại.',
        text: 'Gói glamping · giá.',
        cta: '"Đặt chỗ cuối tuần."',
      }),
      v('Tour Hội An đêm đèn lồng', 'Kling, VEO3', 'Video không khí phố cổ.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'COUPLE: a Vietnamese couple in their late 20s, she wears an áo dài, he wears a linen shirt.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Hoi An ancient town at night, colorful lanterns reflecting on the Hoai river.'),
          sc('6–14s', 'TRẢI NGHIỆM', 'VEO3', `COUPLE release a paper lantern on the river from a small boat. ${N}`, 'Cô gái: "Ước gì mình được quay lại đây mỗi năm."'),
          sc('14–20s', 'KẾT', 'Kling', 'Lanterns float down the river, camera rises.'),
        ],
        audio: 'nhạc truyền thống nhẹ.',
        text: 'Tour Hội An · giá.',
        cta: '"Đặt tour Đà Nẵng – Hội An."',
      }),
      v('Kinh nghiệm du lịch tiết kiệm', 'VEO3', 'Video mẹo du lịch – tăng follow cho kênh / công ty du lịch.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'TRAVELER: a 25-year-old Vietnamese man, backpack, cap, sunglasses.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `TRAVELER at a train station. ${N}`, 'Du khách: "Đi Đà Lạt 3 ngày chỉ 2 triệu – làm sao?"'),
          sc('4–24s', 'MẸO', 'VEO3', `TRAVELER counts tips on fingers in different locations. ${N}`, '"Đi xe giường nằm đêm, ở homestay, ăn chợ đêm, thuê xe máy theo ngày."'),
          sc('24–30s', 'KẾT', 'VEO3', `TRAVELER waves. ${N}`, '"Lưu lại cho chuyến đi tới nha!"'),
        ],
        audio: 'nhạc vui.',
        text: 'Bảng chi phí ước tính.',
        cta: '"Theo dõi để xem thêm mẹo du lịch."',
      }),
      v('Ẩm thực đường phố Sài Gòn', 'Kling, VEO3', 'Food tour đêm Sài Gòn.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'GUIDE: a 26-year-old Vietnamese woman, short hair, yellow shirt, energetic.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Saigon night street full of motorbikes and food stalls, neon lights.'),
          sc('5–18s', 'MÓN ĂN', 'Kling', 'Quick shots: broken rice, bánh tráng nướng, ốc, chè.'),
          sc('18–25s', 'KẾT', 'VEO3', `GUIDE eats and smiles at the camera. ${N}`, 'Hướng dẫn viên: "Food tour 4 món, 3 tiếng, đi xe máy!"'),
        ],
        audio: 'tiếng phố đêm, nhạc vui.',
        text: 'Giá tour · giờ khởi hành.',
        cta: '"Đặt food tour tối nay."',
      }),
      v('Resort cho gia đình', 'Kling', 'Video resort có khu vui chơi trẻ em.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Kids slide down a water slide into a pool, laughing.'),
          sc('6–14s', 'GIA ĐÌNH', 'Kling', 'Parents relax on sunbeds, kids club activities, family dinner.'),
          sc('14–20s', 'KẾT', 'Kling', 'Family walks on the beach at sunset.'),
        ],
        audio: 'nhạc vui.',
        text: 'Gói gia đình · trẻ em miễn phí (nếu có).',
        cta: '"Đặt kỳ nghỉ gia đình."',
      }),
      v('Du thuyền ngắm hoàng hôn', 'Kling', 'Video trải nghiệm du thuyền.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A cruise yacht sails on a calm bay at sunset, golden reflections.'),
          sc('5–11s', 'TRÊN TÀU', 'Kling', 'Guests toast drinks on the deck, live music.'),
          sc('11–15s', 'KẾT', 'Kling', 'Drone pulls away as the sun sets.'),
        ],
        audio: 'nhạc lãng mạn.',
        text: 'Giờ khởi hành · giá vé.',
        cta: '"Đặt vé du thuyền."',
      }),
      v('Hướng dẫn viên kể chuyện điểm đến', 'VEO3', 'Video kể chuyện văn hóa – xây thương hiệu tour.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'GUIDE: a 40-year-old Vietnamese male tour guide, hat, khaki shirt, warm voice.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `GUIDE stands in front of the Hue Imperial City gate. ${N}`, 'Hướng dẫn viên: "Bạn có biết Đại Nội Huế được xây trong bao lâu?"'),
          sc('5–24s', 'KỂ CHUYỆN', 'VEO3', `GUIDE walks through the palace courtyard while talking. ${N}`, '"Kinh thành được xây dựng trong nhiều năm dưới triều Nguyễn, đầu thế kỷ 19…"'),
          sc('24–30s', 'KẾT', 'VEO3', `GUIDE smiles. ${N}`, '"Đến Huế, mình kể tiếp nhé!"'),
        ],
        audio: 'nhạc cung đình nhẹ.',
        text: 'Thông tin lịch sử (kiểm tra trước khi đăng).',
        cta: '"Đặt tour Huế 1 ngày."',
      }),
      v('Nhà hàng trong khách sạn', 'Kling', 'Video buffet / nhà hàng khách sạn.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A luxurious buffet spread with seafood, sushi, desserts, warm lights.'),
          sc('5–11s', 'MÓN', 'Kling', 'Chef slices roast beef, lobster grilled.'),
          sc('11–15s', 'KẾT', 'Kling', 'Guests dine by a window with city view.'),
        ],
        audio: 'nhạc jazz nhẹ.',
        text: 'Buffet tối · giá · ưu đãi nhóm.',
        cta: '"Đặt bàn buffet cuối tuần."',
      }),
      v('Trekking – chinh phục đỉnh núi', 'Kling, VEO3', 'Video tour mạo hiểm.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'HIKER: a 28-year-old Vietnamese man, trekking poles, red jacket.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'HIKER climbs a rocky trail in fog, breathing hard.'),
          sc('6–16s', 'HÀNH TRÌNH', 'Kling', 'Camp at night under stars, morning climb through bamboo forest.'),
          sc('16–25s', 'ĐỈNH', 'VEO3', `HIKER reaches the summit above a sea of clouds, raises arms. ${N}`, 'Người leo núi: "Đã chinh phục được rồi!"'),
        ],
        audio: 'nhạc hùng tráng.',
        text: 'Độ khó · thời gian · giá.',
        cta: '"Đăng ký đoàn leo núi tháng tới."',
      }),
      v('Đánh giá của khách lưu trú', 'VEO3', 'Testimonial khách nước ngoài / trong nước.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'GUEST: a 35-year-old foreign woman tourist, sun hat, linen shirt.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `GUEST on a hotel balcony with sea view. ${N}`, 'Guest (English): "This is the best stay of my trip in Vietnam!"'),
          sc('5–15s', 'CHIA SẺ', 'VEO3', `GUEST smiles. ${N}`, '"The staff are so kind, and breakfast is amazing."'),
          sc('15–20s', 'KẾT', 'VEO3', `GUEST waves. ${N}`, '"Cảm ơn!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Phụ đề tiếng Việt · điểm đánh giá.',
        cta: '"Đặt phòng ngay."',
      }),
      v('Lễ hội địa phương', 'Kling', 'Video quảng bá lễ hội, sự kiện du lịch.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Colorful festival parade with dragon dance and drums.'),
          sc('5–14s', 'KHÔNG KHÍ', 'Kling', 'Crowds cheering, traditional performances, street food.'),
          sc('14–20s', 'KẾT', 'Kling', 'Fireworks over the festival at night.'),
        ],
        audio: 'trống hội, nhạc lễ hội.',
        text: 'Tên lễ hội · thời gian · địa điểm.',
        cta: '"Lên kế hoạch tham dự ngay."',
      }),
    ],
  },
];
