// Bổ sung kịch bản video AI (14 / ngành) – phần 1.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Giải trí & Kể chuyện',
    prompts: [
      v('Hài POV: "Làm con út trong nhà"', 'VEO3', 'Video hài đời thường, dễ đồng cảm, nhiều người tag nhau.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'KID: a 15-year-old Vietnamese boy, bowl haircut, oversized school uniform. SIS: his 22-year-old sister, long hair, office outfit. BRO: his 19-year-old brother, gym tank top.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `KID sits on the sofa scrolling his phone, looks at the camera with a tired face. Living room, daylight, handheld. ${N}`, 'Út: "Làm con út sướng lắm… sướng bị sai vặt."'),
          sc('4–9s', 'SAI VẶT 1', 'VEO3', `SIS shouts from her room, KID sighs and gets up. Comedic, static medium shot. ${N}`, 'Chị: "Út ơi lấy chị ly nước!"'),
          sc('9–14s', 'SAI VẶT 2', 'VEO3', `BRO in the kitchen points at the trash bag, KID walks in carrying a glass of water. ${N}`, 'Anh: "Tiện đổ rác luôn nha Út!"'),
          sc('14–20s', 'TWIST', 'VEO3', `The family sits at dinner, MOM gives the biggest piece of chicken to KID, SIS and BRO stare jealously, KID smirks at the camera. ${N}`, 'Út: "Nhưng mà… miếng ngon nhất luôn là của Út."'),
        ],
        audio: 'nhạc hài sitcom; SFX: "boing", tiếng thở dài, "ting" ở twist.',
        cta: '"Tag anh chị em nhà bạn vào xem!"',
      }),
      v('Kinh dị ngắn: Thang máy lúc nửa đêm', 'VEO3, Kling', 'Truyện ngắn rùng rợn 20 giây có twist – giữ chân rất tốt.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'GIRL: a 24-year-old Vietnamese office worker, long black hair, white shirt, tired eyes, holding a laptop bag.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'GIRL enters an empty apartment elevator at midnight, flickering fluorescent light, cold blue tone, slow push in. Horror atmosphere.'),
          sc('5–11s', 'BẤT THƯỜNG', 'VEO3', `The elevator stops at floor 13 although she pressed 8, doors open to a pitch-dark hallway, silence. GIRL looks scared. ${N}`, 'Cô gái (thì thầm): "Tòa này… làm gì có tầng 13?"'),
          sc('11–16s', 'CĂNG THẲNG', 'Kling', 'GIRL repeatedly presses the close button, the doors slowly close, a faint shadow appears in the dark hallway.'),
          sc('16–20s', 'TWIST', 'VEO3', `Inside the elevator mirror, GIRL sees a reflection standing behind her, she slowly turns around – the elevator is empty. Freeze. ${N}`),
        ],
        audio: 'ù trầm đáng sợ, tiếng thang máy, tiếng tim đập; im lặng 1 giây trước cú twist.',
        text: '"Chuyện xảy ra lúc 00:13"',
        cta: '"Muốn xem phần 2 thì comment \'13\'."',
      }),
      v('Cổ tích hiện đại: Cây khế 4.0 (3D)', 'Kling, VEO3, ElevenLabs', 'Kể lại truyện cổ tích quen thuộc theo bối cảnh hiện đại, hoạt hình 3D.', {
        info: '45 giây · dọc 9:16 · Kling (3D) + lời kể',
        character: 'YOUNGER: a kind young Vietnamese man in 3D Pixar style, simple white T-shirt, straw hat. ELDER: his greedy older brother, gold chains, sunglasses, flashy suit. BIRD: a giant golden phoenix-like bird.',
        scenes: [
          sc('0–8s', 'MỞ ĐẦU', 'Kling', '3D Pixar-style animation: ELDER lives in a luxury villa, YOUNGER lives in a tiny hut with one star-fruit tree. Bright colors.', 'Lời kể: "Ngày xửa ngày xưa… à không, năm 2025, có hai anh em."'),
          sc('8–20s', 'CHIM THẦN', 'Kling', '3D animation: BIRD lands on the star-fruit tree, YOUNGER smiles kindly, BIRD gives him a tiny bag, he flies on its back to a glowing island full of gold coins.', '"Chim ăn khế, trả vàng. Em chỉ lấy đúng túi ba gang."'),
          sc('20–34s', 'THAM LAM', 'Kling', '3D animation: ELDER trades houses, then sews a giant bag, stuffs it with gold until the BIRD struggles to fly over the sea. Comedic.', '"Anh may túi… mười hai gang, còn mang theo cả két sắt."'),
          sc('34–45s', 'KẾT', 'Kling', '3D animation: the bag rips, gold falls into the sea, ELDER floats on an inflatable duck ring looking regretful, YOUNGER waves from the beach.', '"Tham thì thâm – đúng ở mọi thời đại."'),
        ],
        audio: 'nhạc cổ tích vui nhộn; SFX: tiếng chim, sóng biển, tiếng vàng rơi.',
        cta: '"Muốn xem cổ tích nào phiên bản 4.0 tiếp theo?"',
      }),
      v('Đồ vật biết nói: Chiếc điện thoại than thở', 'VEO3', 'Nhân hóa đồ vật quen thuộc, hài và gần gũi.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'PHONE: a smartphone with cartoon eyes and mouth on its screen, cracked screen protector, 3% battery icon.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `PHONE lies on a messy bed at night, its cartoon face looks exhausted. Close-up, realistic room with cartoon face on screen. ${N}`, 'Điện thoại: "Chủ ơi, tui còn 3% pin thôi…"'),
          sc('5–12s', 'THAN THỞ', 'VEO3', `PHONE is picked up by a hand that keeps scrolling videos, its face sweating. ${N}`, '"Lướt từ 10 giờ tới 2 giờ sáng, mắt chủ thâm, tui thì nóng ran!"'),
          sc('12–20s', 'KẾT', 'VEO3', `PHONE finally connected to a charger, sighs with relief, then the screen lights up with another notification and its face panics. ${N}`, '"Ơ… lại 1 tin nhắn nữa à?!"'),
        ],
        audio: 'giọng hoạt hình; SFX: thông báo "ting" liên tục.',
        cta: '"Bạn lướt điện thoại tới mấy giờ đêm qua?"',
      }),
      v('Thế giới thu nhỏ: Người tí hon nấu phở', 'Kling', 'Video miniature tilt-shift đã mắt, rất dễ viral.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Tilt-shift miniature: tiny people climb a giant bowl on a kitchen table using ladders, top-down view, bright daylight.'),
          sc('4–9s', 'NẤU', 'Kling', 'Tiny chefs pour broth with a giant ladle, others carry huge rice noodles and herbs like logs. Playful, highly detailed.'),
          sc('9–15s', 'KẾT', 'Kling', 'A real human hand lifts the finished pho bowl, tiny people cheer and wave. Slow pull back.'),
        ],
        audio: 'nhạc vui nhộn; SFX: tiếng người tí hon lao xao.',
        cta: '"Muốn xem người tí hon làm món gì tiếp theo?"',
      }),
      v('Plot twist tình cảm: Người lạ trên xe buýt', 'VEO3', 'Phim ngắn lãng mạn 30 giây có cú twist ngọt ngào.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'HE: a 25-year-old Vietnamese man, short hair, beige trench coat, holding a book. SHE: a 24-year-old Vietnamese woman, bob haircut, red scarf, earphones.',
        scenes: [
          sc('0–6s', 'GẶP GỠ', 'VEO3', `On a rainy evening city bus, HE and SHE sit side by side, she drops her earphone, he picks it up. Warm interior light, rain on windows. ${N}`, 'Anh: "Của bạn này." – Cô: "Cảm ơn."'),
          sc('6–14s', 'MỖI NGÀY', 'VEO3', `Montage of several days: same bus, they exchange small smiles, he lends her his umbrella. Soft, romantic. ${N}`),
          sc('14–22s', 'MẤT HÚT', 'VEO3', `HE sits alone on the bus, looking at the empty seat, disappointed. Cool tone. ${N}`),
          sc('22–30s', 'TWIST', 'VEO3', `At his new office first day, the door opens: SHE is his new team leader, both freeze then laugh. ${N}`, 'Cô: "Chào mừng em đến team… người ở xe buýt."'),
        ],
        audio: 'nhạc lãng mạn piano; SFX: mưa, tiếng xe buýt.',
        cta: '"Bạn đã từng gặp duyên trên xe buýt chưa?"',
      }),
      v('Kỳ vọng vs Thực tế: Đi du lịch', 'VEO3, Kling', 'So sánh hài hước, chia đôi màn hình.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling (ghép chia đôi bằng CapCut)',
        character: 'TRAVELER: a 26-year-old Vietnamese woman, sun hat, white flowy dress.',
        scenes: [
          sc('0–5s', 'KỲ VỌNG 1', 'Kling', 'TRAVELER poses elegantly on an empty pristine beach at sunset, dress flowing, cinematic.'),
          sc('5–10s', 'THỰC TẾ 1', 'VEO3', `TRAVELER on a crowded beach, people walking into her photo, wind blows her hat away, she chases it. ${N}`, 'Cô gái: "Ủa nón tui!"'),
          sc('10–15s', 'KỲ VỌNG 2', 'Kling', 'TRAVELER sips coffee on a dreamy balcony with misty mountains.'),
          sc('15–20s', 'THỰC TẾ 2', 'VEO3', `TRAVELER in heavy rain fog, sees nothing but white, holding a cold coffee, deadpan face at the camera. ${N}`, '"View triệu đô… đây."'),
        ],
        audio: 'nhạc đẹp (kỳ vọng) ↔ nhạc hài (thực tế), record scratch khi chuyển.',
        text: 'Nhãn "Kỳ vọng" / "Thực tế".',
        cta: '"Chuyến đi nào của bạn \'kỳ vọng vs thực tế\' nhất?"',
      }),
      v('Nếu động vật đi làm văn phòng', 'Kling, VEO3', 'Series hài nhân hóa động vật trong công sở.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'BOSS: a serious owl in a tiny suit and glasses. SLOTH: a sloth employee in a cardigan. CAT: a cat employee in a hoodie. Photorealistic animals in a modern office.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Photorealistic office: BOSS owl sits at the head of a meeting table, turns its head 180 degrees to stare at the team.'),
          sc('5–12s', 'HỌP', 'VEO3', `BOSS speaks seriously in a meeting. ${N}`, 'Cú: "Deadline là sáng mai. Ai làm được?"'),
          sc('12–18s', 'PHẢN ỨNG', 'Kling', 'SLOTH slowly, very slowly raises its hand; CAT is asleep on the keyboard.'),
          sc('18–25s', 'KẾT', 'VEO3', `CAT wakes up, yawns and looks at the camera. ${N}`, 'Mèo: "Em làm… sau giấc ngủ trưa."'),
        ],
        audio: 'nhạc văn phòng hài; SFX: tiếng gõ phím, ngáy.',
        cta: '"Đồng nghiệp bạn giống con vật nào?"',
      }),
      v('Ông bà 4.0 học dùng smartphone', 'VEO3', 'Series ấm áp – hài hước về người lớn tuổi và công nghệ.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'GRANDMA: a 72-year-old Vietnamese grandmother, white hair bun, áo bà ba, reading glasses. GRANDSON: a 16-year-old Vietnamese boy, school T-shirt.',
        scenes: [
          sc('0–6s', 'HOOK', 'VEO3', `GRANDMA holds a smartphone far from her face, squinting, on a wooden bench in the yard. ${N}`, 'Bà: "Cháu ơi, sao bà gọi video mà chỉ thấy cái trần nhà?"'),
          sc('6–16s', 'HƯỚNG DẪN', 'VEO3', `GRANDSON sits beside her, patiently turns the phone around, shows the screen. ${N}`, 'Cháu: "Bà để camera trước nè, thấy mặt bà chưa?"'),
          sc('16–24s', 'THÀNH CÔNG', 'VEO3', `GRANDMA video calls a relative, laughing happily and waving. ${N}`, 'Bà: "Ơ thấy rồi! Út ơi, bà đây nè!"'),
          sc('24–30s', 'TWIST', 'VEO3', `GRANDMA turns to the camera with a proud look holding the phone. ${N}`, 'Bà: "Mai bà học… livestream bán rau."'),
        ],
        audio: 'nhạc vui ấm áp.',
        cta: '"Ông bà bạn đã dùng được smartphone chưa?"',
      }),
      v('Phim ngắn cảm động: Lá thư gửi mẹ', 'Kling, VEO3, ElevenLabs', 'Video cảm xúc dịp Vu Lan / 8-3 / 20-10.', {
        info: '40 giây · dọc 9:16 · Kling + VEO3 + lời kể',
        character: 'MOM: a 55-year-old Vietnamese mother, grey-streaked hair, simple floral blouse. DAUGHTER: a 28-year-old Vietnamese woman, office outfit.',
        scenes: [
          sc('0–8s', 'KÝ ỨC', 'Kling', 'Warm flashback: MOM carrying a little girl on a bicycle through rice fields at sunset, soft film grain.', 'Lời kể: "Mẹ ơi, hồi nhỏ con nghĩ mẹ không bao giờ biết mệt."'),
          sc('8–18s', 'HIỆN TẠI', 'Kling', 'DAUGHTER in a busy city office at night, sees a missed call from "Mẹ" on her phone, hesitates.', '"Lớn lên, con bận đến mức quên cả gọi về."'),
          sc('18–30s', 'VỀ NHÀ', 'VEO3', `DAUGHTER surprises MOM at the old house gate, MOM drops her basket and hugs her, both teary. ${N}`, 'Mẹ: "Sao về mà không báo mẹ?"'),
          sc('30–40s', 'KẾT', 'Kling', 'Mother and daughter cook together in a small kitchen, laughing, warm light.', '"Hôm nay, gọi cho mẹ nhé."'),
        ],
        audio: 'piano cảm động.',
        cta: '"Gọi cho mẹ ngay sau khi xem video này."',
      }),
      v('ASMR cắt trái cây pha lê', 'Kling', 'Video thỏa mãn thị giác – thính giác, không thoại.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Extreme close-up: a sharp knife slowly slices a glass-like crystal apple on a wooden board, revealing sparkling layered insides. Macro, slow motion.'),
          sc('5–10s', 'TIẾP', 'Kling', 'Same knife slices a crystal kiwi, green glowing slices fall gently.'),
          sc('10–15s', 'KẾT', 'Kling', 'All crystal fruit slices arranged on the board glittering under studio light, slow pull back.'),
        ],
        audio: 'ASMR: tiếng cắt thủy tinh giòn tan, không nhạc.',
        cta: '"Bạn muốn xem cắt món gì tiếp theo?"',
      }),
      v('Hoạt hình giáo dục vui: Khủng long đi học', 'Kling, VEO3', 'Hoạt hình 3D cho trẻ em, có bài học nhỏ.', {
        info: '35 giây · dọc 9:16 · Kling + VEO3',
        character: 'DINO: a cute small green T-rex in 3D Pixar style with a red backpack. TEACHER: a kind giraffe teacher wearing glasses.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '3D animation: DINO runs late to a jungle school, backpack bouncing, other baby animals already seated.'),
          sc('6–16s', 'VẤN ĐỀ', 'VEO3', `3D animation: DINO tries to raise his tiny arms to answer but can\'t reach, looks sad. ${N}`, 'Khủng long: "Tay tớ ngắn quá, không giơ lên được…"'),
          sc('16–28s', 'GIẢI QUYẾT', 'VEO3', `3D animation: TEACHER smiles and lowers her long neck to DINO. ${N}`, 'Cô Hươu: "Không sao, con hãy gọi to tên cô nhé. Ai cũng có cách riêng!"'),
          sc('28–35s', 'KẾT', 'Kling', '3D animation: DINO answers proudly, classmates clap.'),
        ],
        audio: 'nhạc thiếu nhi.',
        cta: '"Theo dõi để xem tập tiếp theo của Khủng long đi học."',
      }),
      v('Một ngày ở năm 2050 (sci-fi)', 'Kling, VEO3', 'Video tưởng tượng tương lai Việt Nam – chủ đề gây tò mò.', {
        info: '30 giây · dọc 9:16 · Kling + VEO3',
        character: 'MINH: a 30-year-old Vietnamese man in 2050, sleek grey jacket with glowing seams, smart glasses.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Futuristic Saigon skyline in 2050 with flying taxis, vertical gardens, holographic billboards, sunrise. Cinematic drone shot.'),
          sc('6–14s', 'BUỔI SÁNG', 'VEO3', `MINH wakes up, a robot arm serves phở in a smart kitchen. ${N}`, 'Minh: "Robot nấu phở vẫn không ngon bằng mẹ nấu."'),
          sc('14–22s', 'ĐI LÀM', 'Kling', 'MINH rides a quiet flying motorbike above green canals of the city.'),
          sc('22–30s', 'KẾT', 'VEO3', `MINH at a rooftop café with friends, toasting iced coffee, looks at the camera. ${N}`, '"Có những thứ 2050 vẫn giữ: cà phê sữa đá và bạn bè."'),
        ],
        audio: 'nhạc synth tương lai.',
        cta: '"Bạn nghĩ năm 2050 Việt Nam sẽ thế nào?"',
      }),
      v('Đố vui hình ảnh: Đoán món ăn', 'Kling', 'Video tương tác đố vui – tăng bình luận mạnh.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'CÂU 1', 'Kling', 'Extreme macro close-up of a mystery food texture: crispy golden rice paper with shrimp, blurry, slowly revealing.', 'Lời kể: "Câu 1: Đây là món gì?"'),
          sc('4–8s', 'ĐÁP ÁN 1', 'Kling', 'Camera pulls back revealing a plate of bánh tráng nướng on a charcoal grill.'),
          sc('8–12s', 'CÂU 2', 'Kling', 'Macro close-up of purple sticky rice texture with coconut shreds.', '"Câu 2: Dễ hơn nè!"'),
          sc('12–20s', 'ĐÁP ÁN 2 + THỬ THÁCH', 'Kling', 'Pull back revealing xôi lá cẩm, then a third macro of a mysterious brown jelly texture freezes.', '"Câu 3 đáp án ở phần bình luận!"'),
        ],
        audio: 'nhạc đố vui, tiếng đồng hồ tích tắc, "ting".',
        cta: '"Comment đáp án câu 3!"',
      }),
    ],
  },

  {
    name: 'Bán hàng online & TMĐT',
    prompts: [
      v('Trailer nhắc lịch livestream', 'VEO3, Kling', 'Video ngắn kéo người xem vào phiên live bán hàng.', {
        info: '15 giây · dọc 9:16 · VEO3 + Kling',
        character: 'HOST: a 27-year-old Vietnamese woman, glossy straight hair, pink blazer, microphone clip.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `HOST in a livestream studio with ring lights and product shelves, points at the camera. ${N}`, 'Host: "8 giờ tối nay, săn deal 1 nghìn đồng!"'),
          sc('4–10s', 'SẢN PHẨM', 'Kling', '[Ảnh sản phẩm] Products pop onto a table one after another with sparkles, quick cuts.'),
          sc('10–15s', 'CTA', 'VEO3', `HOST makes a heart with her hands. ${N}`, '"Bấm nhắc lịch ngay nha cả nhà!"'),
        ],
        audio: 'nhạc sôi động; SFX: "cha-ching".',
        text: '"LIVE 20:00 hôm nay" · "Deal 1K".',
        cta: '"Bấm \'Nhắc tôi\' để không lỡ live."',
      }),
      v('Tổng hợp feedback khách hàng', 'VEO3', 'Montage nhiều khách khác nhau khen sản phẩm – bằng chứng xã hội.', {
        info: '20 giây · dọc 9:16 · VEO3 (3 nhân vật, mỗi người 1 câu)',
        character: 'A: a 25-year-old Vietnamese woman in a café. B: a 40-year-old Vietnamese man in his car. C: a 33-year-old Vietnamese mother in her kitchen.',
        scenes: [
          sc('0–6s', 'KHÁCH 1', 'VEO3', `A holds [sản phẩm] in a café, selfie style. ${N}`, 'Khách 1: "Dùng 2 tuần rồi, ưng lắm luôn!"'),
          sc('6–12s', 'KHÁCH 2', 'VEO3', `B in the driver seat holds [sản phẩm]. ${N}`, 'Khách 2: "Giao nhanh, đóng gói kỹ, mua lần thứ ba rồi."'),
          sc('12–20s', 'KHÁCH 3', 'VEO3', `C in the kitchen gives a thumbs up with [sản phẩm]. ${N}`, 'Khách 3: "Giá này mà chất lượng vậy là quá ổn!"'),
        ],
        audio: 'nhạc tươi vui.',
        text: '⭐⭐⭐⭐⭐ · "Hơn [số] đánh giá 5 sao" (đúng thực tế; nên dùng feedback thật).',
        cta: '"Xem thêm đánh giá và đặt hàng trong giỏ."',
      }),
      v('"3 lý do nên mua" – nói trước camera', 'VEO3', 'Talking head ngắn gọn, đếm số – dễ xem hết.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'SELLER: a 29-year-old Vietnamese man, neat short hair, black T-shirt with shop logo.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `SELLER holds [sản phẩm] in a tidy shop. ${N}`, 'Người bán: "3 lý do em này cháy hàng tuần qua!"'),
          sc('4–9s', 'LÝ DO 1', 'VEO3', `SELLER holds up one finger. ${N}`, '"Một: [lợi ích 1]."'),
          sc('9–14s', 'LÝ DO 2', 'VEO3', `Two fingers. ${N}`, '"Hai: [lợi ích 2]."'),
          sc('14–20s', 'LÝ DO 3 + CTA', 'VEO3', `Three fingers, then points down. ${N}`, '"Ba: [lợi ích 3]. Bấm giỏ hàng trước khi hết nha!"'),
        ],
        audio: 'nhạc nền nhẹ; SFX: "ding".',
        cta: '"Bấm giỏ hàng."',
      }),
      v('Combo quà tặng ngày lễ (8/3, 20/10)', 'Kling, VEO3', 'Video quà tặng cảm xúc cho dịp lễ phụ nữ.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'BOYFRIEND: a 27-year-old Vietnamese man, white shirt. GIRLFRIEND: a 25-year-old Vietnamese woman, long hair, pastel dress.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh hộp quà] A pastel gift box with roses and a ribbon on a table, soft light, petals falling.'),
          sc('5–12s', 'TRAO QUÀ', 'VEO3', `BOYFRIEND hides the box behind his back, surprises GIRLFRIEND in a café. ${N}`, 'Bạn trai: "Tặng em nè, chúc mừng ngày của em!"'),
          sc('12–20s', 'MỞ QUÀ', 'Kling', 'GIRLFRIEND opens the box revealing [sản phẩm combo], smiles and hugs him.'),
        ],
        audio: 'nhạc lãng mạn.',
        text: 'Combo quà [ngày lễ] · giá · tặng thiệp viết tay.',
        cta: '"Đặt trước [ngày] – giao đúng giờ hẹn."',
      }),
      v('Đóng gói đơn hàng ASMR', 'Kling', 'Video "packing orders" – tạo niềm tin và rất dễ xem.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Top-down: hands place [sản phẩm] into a branded box with crinkle paper, adding a thank-you card and a small gift. Aesthetic desk, daylight.'),
          sc('5–10s', 'ĐÓNG GÓI', 'Kling', 'Hands wrap the box with bubble wrap, seal with branded tape, stick the shipping label. Satisfying.'),
          sc('10–15s', 'KẾT', 'Kling', 'A stack of packed orders ready for pickup, camera slowly rises.'),
        ],
        audio: 'ASMR: băng keo, giấy, bubble wrap; lo-fi nhỏ.',
        text: '"Gói hàng cho bạn ở [tỉnh/thành]" · "Đóng gói 3 lớp".',
        cta: '"Đặt đơn để nhận gói hàng xinh như thế này."',
      }),
      v('Hướng dẫn sử dụng sản phẩm', 'VEO3, Kling', 'Video how-to giảm hỏi đáp, tăng tỉ lệ mua.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'GUIDE: a 30-year-old Vietnamese woman, apron, friendly smile.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `GUIDE holds [sản phẩm] at a kitchen counter. ${N}`, 'Hướng dẫn: "Dùng em này đúng cách chỉ 3 bước!"'),
          sc('4–12s', 'BƯỚC 1', 'Kling', '[Ảnh sản phẩm] Close-up of hands doing step 1: [bước 1].'),
          sc('12–20s', 'BƯỚC 2', 'Kling', 'Close-up of step 2: [bước 2].'),
          sc('20–30s', 'BƯỚC 3 + KẾT', 'VEO3', `GUIDE shows the result and smiles. ${N}`, '"Xong! Lưu video lại để dùng nha."'),
        ],
        audio: 'nhạc nhẹ; SFX: "ding" mỗi bước.',
        text: 'Bước 1 · Bước 2 · Bước 3.',
        cta: '"Mua kèm phụ kiện trong giỏ hàng."',
      }),
      v('Mua 1 tặng 1', 'Kling, VEO3', 'Video ưu đãi nhân đôi, hiệu ứng vui mắt.', {
        info: '12 giây · dọc 9:16 · Kling + VEO3',
        character: 'HOST: a cheerful 24-year-old Vietnamese woman, yellow hoodie, twin buns hairstyle.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh sản phẩm] One product on a turntable suddenly duplicates into two with a magic sparkle effect.'),
          sc('4–9s', 'ƯU ĐÃI', 'VEO3', `HOST holds two products, one in each hand, excited. ${N}`, 'Host: "Mua một tặng một, chỉ trong 48 giờ!"'),
          sc('9–12s', 'KẾT', 'Kling', 'Countdown timer style light effects around the products.'),
        ],
        audio: 'nhạc sôi động; SFX: "pop".',
        text: '"MUA 1 TẶNG 1 – 48H".',
        cta: '"Bấm giỏ hàng ngay."',
      }),
      v('Hậu trường shop & kho hàng', 'Kling, VEO3', 'Cho khách thấy đội ngũ thật, kho hàng thật – tăng uy tín.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'OWNER: a 31-year-old Vietnamese woman, ponytail, shop T-shirt, tablet in hand.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A busy small warehouse with shelves of products, team members packing orders, bright light.'),
          sc('5–14s', 'ĐỘI NGŨ', 'Kling', 'Quick shots: checking product quality, labeling, laughing team.'),
          sc('14–25s', 'CHỦ SHOP', 'VEO3', `OWNER stands in the warehouse, speaks to the camera. ${N}`, 'Chủ shop: "Mỗi đơn đều được kiểm tra trước khi gửi – lỗi 1 đổi 1 trong 7 ngày."'),
        ],
        audio: 'nhạc vui.',
        text: 'Chính sách đổi trả (đúng thực tế).',
        cta: '"Theo dõi shop để xem hậu trường mỗi tuần."',
      }),
      v('Trả lời bình luận bằng video', 'VEO3', 'Chọn 1 câu hỏi của khách và trả lời – tăng tương tác.', {
        info: '20 giây · dọc 9:16 · VEO3 (chèn ảnh bình luận)',
        character: 'SELLER: a 28-year-old Vietnamese woman, round glasses, cream cardigan.',
        scenes: [
          sc('0–4s', 'CÂU HỎI', 'VEO3', `SELLER reads a comment on her phone, then looks at the camera. ${N}`, 'Người bán: "Bạn hỏi: sản phẩm có dùng cho [đối tượng] được không?"'),
          sc('4–16s', 'TRẢ LỜI', 'VEO3', `SELLER demonstrates [sản phẩm] while explaining. ${N}`, '"Được nha, vì [lý do]. Mình demo luôn cho bạn xem."'),
          sc('16–20s', 'CTA', 'VEO3', `SELLER smiles. ${N}`, '"Còn thắc mắc gì cứ comment nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Ảnh chụp bình luận của khách.',
        cta: '"Comment câu hỏi để được trả lời bằng video."',
      }),
      v('Hàng mới về (new arrival)', 'Kling', 'Video giới thiệu lô hàng mới nhanh, nhiều sản phẩm.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–3s', 'HOOK', 'Kling', 'A delivery box opens by itself, light bursts out, confetti.'),
          sc('3–12s', 'SẢN PHẨM', 'Kling', '[Ảnh từng sản phẩm] Products appear one by one on a pastel podium, rotating, quick rhythmic cuts.'),
          sc('12–15s', 'KẾT', 'Kling', 'All products lined up together, camera pulls back.'),
        ],
        audio: 'beat nhanh; SFX: whoosh.',
        text: '"HÀNG MỚI VỀ" · số mẫu · giá từ [giá].',
        cta: '"Xem toàn bộ trong giỏ hàng."',
      }),
      v('"Đừng mua nếu…" (tâm lý ngược)', 'VEO3', 'Hook ngược gây tò mò, lọc đúng khách hàng mục tiêu.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'REVIEWER: a 26-year-old Vietnamese man, stylish glasses, denim shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `REVIEWER holds [sản phẩm], serious face. ${N}`, 'Reviewer: "Đừng mua em này nếu…"'),
          sc('4–14s', 'LIỆT KÊ', 'VEO3', `REVIEWER counts on fingers with a playful smirk. ${N}`, '"…bạn thích [vấn đề 1], thích [vấn đề 2] và không ngại [vấn đề 3]."'),
          sc('14–20s', 'TWIST', 'VEO3', `REVIEWER laughs and points down. ${N}`, '"Còn nếu không thì… link ở giỏ hàng nha!"'),
        ],
        audio: 'nhạc hài nhẹ.',
        cta: '"Bấm giỏ hàng."',
      }),
      v('Test độ bền sản phẩm', 'Kling', 'Thử thách sản phẩm trực quan – chứng minh chất lượng.', {
        info: '15 giây · dọc 9:16 · Kling (quay test thật càng tốt)',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh sản phẩm] [sản phẩm: a phone case] placed on a table, a hammer rises above it, slow motion.'),
          sc('4–10s', 'THỬ', 'Kling', 'The hammer hits, then the case is dropped from a height onto concrete, slow motion impact.'),
          sc('10–15s', 'KẾT QUẢ', 'Kling', 'Close-up: the case and phone remain undamaged, a hand picks it up.'),
        ],
        audio: 'nhạc hồi hộp; SFX: va chạm mạnh, "ting".',
        text: '"Rơi từ 2m – vẫn nguyên" (chỉ ghi khi đã test thật).',
        cta: '"Bảo vệ điện thoại của bạn – link ở giỏ hàng."',
      }),
      v('Haul: Mua gì với 200 nghìn?', 'VEO3, Kling', 'Định dạng haul tiết kiệm – rất hợp shop đồ giá rẻ.', {
        info: '25 giây · dọc 9:16 · VEO3 + Kling',
        character: 'BUYER: a 21-year-old Vietnamese female student, bangs, oversized hoodie.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `BUYER sits on her bed with a pile of packages, holds up a 200k bill. ${N}`, 'Cô gái: "200 nghìn mua được những gì ở shop này?"'),
          sc('4–20s', 'MỞ HÀNG', 'Kling', 'BUYER unboxes item after item: [món 1], [món 2], [món 3], showing each to the camera, happy reactions.'),
          sc('20–25s', 'KẾT', 'VEO3', `BUYER surrounded by her items, gives a thumbs up. ${N}`, '"Tổng cộng 198 nghìn! Link mình để hết trong giỏ."'),
        ],
        audio: 'nhạc trend; SFX: "pop" mỗi món.',
        text: 'Giá từng món.',
        cta: '"Bấm giỏ hàng để săn deal."',
      }),
      v('Cam kết freeship & đổi trả', 'VEO3', 'Video ngắn xóa lo lắng trước khi mua.', {
        info: '15 giây · dọc 9:16 · VEO3',
        character: 'STAFF: a 25-year-old Vietnamese woman, headset, shop polo shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `STAFF at a customer service desk smiles. ${N}`, 'Nhân viên: "Mua online sợ không vừa, không ưng?"'),
          sc('4–12s', 'CAM KẾT', 'VEO3', `STAFF counts on fingers. ${N}`, '"Freeship đơn từ [số tiền], đổi size miễn phí, hoàn tiền nếu lỗi."'),
          sc('12–15s', 'CTA', 'VEO3', `STAFF waves. ${N}`, '"Yên tâm đặt hàng nha!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Chính sách (đúng thực tế).',
        cta: '"Đặt hàng không lo rủi ro."',
      }),
    ],
  },

  {
    name: 'Mỹ phẩm & Làm đẹp',
    prompts: [
      v('Câu chuyện thành phần (trà xanh)', 'Kling, VEO3', 'Từ nguyên liệu tự nhiên đến chai sản phẩm – tăng giá trị.', {
        info: '25 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–6s', 'NGUYÊN LIỆU', 'Kling', 'Misty green tea hills at sunrise, dew drops on fresh tea leaves, macro, cinematic.'),
          sc('6–14s', 'CHIẾT XUẤT', 'Kling', 'Clean lab: green tea extract drips through glass equipment, scientist hands in gloves, bright clean light.'),
          sc('14–20s', 'SẢN PHẨM', 'Kling', '[Ảnh sản phẩm] The product bottle stands among tea leaves and water droplets, slow orbit. Keep the label exactly the same as the input image.'),
          sc('20–25s', 'KẾT', 'Kling', 'A woman\'s hand applies the serum, fresh green light leaks.'),
        ],
        audio: 'nhạc thiên nhiên nhẹ; SFX: giọt nước.',
        text: 'Thành phần chính · công dụng đã công bố.',
        cta: '"Khám phá sức mạnh trà xanh – link ở bio."',
      }),
      v('Test kem chống nắng với nước', 'Kling, VEO3', 'Demo khả năng chống trôi trực quan (chỉ khi sản phẩm có công bố).', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh sản phẩm] Sunscreen squeezed onto the back of a hand in a line, close-up, bright sunlight.'),
          sc('4–10s', 'THỬ NƯỚC', 'Kling', 'Water poured over the hand, droplets bead and roll off the protected area. Slow motion macro.'),
          sc('10–15s', 'KẾT', 'Kling', 'A woman at the beach applies sunscreen on her face, smiling, summer vibe.'),
        ],
        audio: 'nhạc mùa hè; SFX: nước.',
        text: 'Chỉ số SPF / PA (đúng nhãn sản phẩm).',
        cta: '"Đi biển hè này đừng quên em này."',
      }),
      v('Nước hoa – cảm xúc mùi hương', 'Kling, VEO3', 'Quảng cáo nước hoa điện ảnh: biến mùi hương thành hình ảnh.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'MUSE: a 27-year-old Vietnamese woman, elegant updo, black silk dress.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh chai nước hoa] The perfume bottle on black glass, a mist spray in slow motion, golden light.'),
          sc('5–12s', 'MÙI HƯƠNG', 'Kling', 'Visual metaphor: white jasmine petals and vanilla pods swirl around MUSE as she walks through a dark garden at night.'),
          sc('12–20s', 'KẾT', 'VEO3', `MUSE turns back at the camera with a mysterious smile, petals falling. ${N}`),
        ],
        audio: 'nhạc sang trọng, bí ẩn.',
        text: 'Tên nước hoa · nhóm hương.',
        cta: '"Thử mùi hương tại [cửa hàng]."',
      }),
      v('So sánh tẩy trang', 'Kling', 'Demo làm sạch lớp trang điểm – trực quan, dễ hiểu.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Swatches of waterproof mascara, lipstick and foundation on the inner arm, close-up.'),
          sc('4–10s', 'LÀM SẠCH', 'Kling', '[Ảnh sản phẩm] A cotton pad soaked with the micellar water swipes once, makeup dissolves cleanly.'),
          sc('10–15s', 'KẾT', 'Kling', 'Clean skin, the cotton pad shows the removed makeup, product bottle beside it.'),
        ],
        audio: 'nhạc nhẹ; SFX: "swish".',
        text: '"1 lần lau – sạch lớp trang điểm" (đúng với test thật).',
        cta: '"Mua ngay trong giỏ hàng."',
      }),
      v('Morning routine 60 giây', 'VEO3, Kling', 'Video thói quen buổi sáng tự nhiên, lồng sản phẩm.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'NGOC: a 25-year-old Vietnamese woman, long hair in a towel turban, white bathrobe.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `NGOC opens curtains in a sunny bedroom, stretches, smiles at the camera. ${N}`, 'Ngọc: "Routine buổi sáng 5 phút của mình nè!"'),
          sc('5–20s', 'CÁC BƯỚC', 'Kling', 'Quick close-ups: washing face, applying toner, serum, moisturizer, sunscreen – each 3 seconds.'),
          sc('20–30s', 'KẾT', 'VEO3', `NGOC dressed for work, glowing skin, grabs her bag. ${N}`, '"Đi làm thôi! Sản phẩm mình để trong giỏ nha."'),
        ],
        audio: 'lo-fi buổi sáng.',
        text: 'Tên từng bước.',
        cta: '"Bấm giỏ hàng để xem từng sản phẩm."',
      }),
      v('Chuyên viên tư vấn da giải đáp', 'VEO3', 'Beauty advisor trả lời câu hỏi phổ biến – xây uy tín.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'ADVISOR: a 30-year-old Vietnamese female skincare advisor, white coat, hair in a neat bun.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `ADVISOR in a clean clinic-like room, faces the camera. ${N}`, 'Chuyên viên: "Da dầu có cần dưỡng ẩm không? Câu trả lời là CÓ!"'),
          sc('5–22s', 'GIẢI THÍCH', 'VEO3', `ADVISOR explains with hand gestures. ${N}`, '"Thiếu ẩm, da càng tiết dầu nhiều hơn. Chọn kem dưỡng dạng gel, không gây bít tắc."'),
          sc('22–30s', 'CTA', 'VEO3', `ADVISOR smiles. ${N}`, '"Bạn muốn hỏi gì về da, comment nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo – da có vấn đề hãy gặp bác sĩ da liễu".',
        cta: '"Nhận tư vấn chọn sản phẩm miễn phí."',
      }),
      v('Spa gội đầu dưỡng sinh ASMR', 'Kling', 'Video thư giãn kéo khách đến spa.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Warm water flows over a woman\'s long hair in a spa basin, candles around, steam. Slow motion.'),
          sc('5–14s', 'MASSAGE', 'Kling', 'Therapist\'s hands massage the scalp with herbal foam, close-up, relaxing.'),
          sc('14–20s', 'KẾT', 'Kling', 'The woman sits up with silky hair, smiling, warm light.'),
        ],
        audio: 'ASMR: nước chảy, bọt; nhạc thiền.',
        text: 'Gói gội đầu dưỡng sinh · giá · địa chỉ.',
        cta: '"Đặt lịch thư giãn cuối tuần."',
      }),
      v('Mẫu nail mới', 'Kling', 'Khoe mẫu nail theo mùa cho tiệm nail.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Close-up of a hand with glossy [màu] nails with delicate flower art, rotating slowly, soft light.'),
          sc('4–11s', 'CÁC MẪU', 'Kling', 'Quick transitions between 4 nail designs: chrome, french, pastel ombre, glitter.'),
          sc('11–15s', 'KẾT', 'Kling', 'Hand holding a coffee cup in a café showing the nails.'),
        ],
        audio: 'nhạc trend.',
        text: 'Tên mẫu · giá.',
        cta: '"Chọn mẫu bạn thích – inbox đặt lịch."',
      }),
      v('Trang điểm cô dâu', 'Kling, VEO3', 'Video cảm xúc ngày cưới cho tiệm makeup cô dâu.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'BRIDE: a 26-year-old Vietnamese bride, elegant updo, white lace wedding dress.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Early morning, BRIDE sits in front of a mirror with bulbs, makeup artist prepares brushes.'),
          sc('6–15s', 'TRANG ĐIỂM', 'Kling', 'Close-ups: brushes blending soft makeup, lashes, lipstick, a veil placed.'),
          sc('15–25s', 'KẾT', 'VEO3', `BRIDE turns to the camera, teary smile, her mother hugs her. ${N}`, 'Mẹ: "Con gái mẹ đẹp quá."'),
        ],
        audio: 'nhạc cưới nhẹ nhàng.',
        text: 'Gói makeup cô dâu · lịch trống tháng [tháng].',
        cta: '"Inbox giữ lịch ngày cưới."',
      }),
      v('Mặt nạ ngủ – quảng cáo buổi tối', 'Kling, VEO3', 'Sản phẩm dưỡng đêm, không khí thư giãn.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'SLEEPER: a 28-year-old Vietnamese woman, silk pajamas, hair down.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh sản phẩm] A jar of sleeping mask under moonlight on a bedside table, soft blue glow.'),
          sc('5–10s', 'SỬ DỤNG', 'Kling', 'SLEEPER applies the gel mask on her face, lies down on a fluffy pillow, closes her eyes.'),
          sc('10–15s', 'BUỔI SÁNG', 'VEO3', `Morning sunlight, SLEEPER wakes up touching her soft skin, smiles. ${N}`),
        ],
        audio: 'nhạc ru ngủ nhẹ.',
        text: '"Dưỡng trong lúc ngủ" · "Kết quả tùy cơ địa".',
        cta: '"Mua trong giỏ hàng."',
      }),
      v('Review son lì "ăn uống không trôi"', 'VEO3', 'UGC test son khi ăn uống – rất thuyết phục.', {
        info: '20 giây · dọc 9:16 · VEO3',
        character: 'HUONG: a 23-year-old Vietnamese woman, wolf-cut hair, striped T-shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `HUONG applies [màu] lipstick in a car mirror. ${N}`, 'Hương: "Test son lì: ăn bún bò có trôi không?"'),
          sc('4–14s', 'TEST', 'VEO3', `HUONG eats a bowl of spicy noodles at a street stall, wipes with a tissue. ${N}`, '"Ăn hết tô luôn nè…"'),
          sc('14–20s', 'KẾT QUẢ', 'VEO3', `Close-up: lipstick still mostly intact, HUONG smiles at the camera. ${N}`, '"Vẫn còn màu! Mã [màu] trong giỏ nha."'),
        ],
        audio: 'nhạc vui.',
        text: '"Trước khi ăn" / "Sau khi ăn".',
        cta: '"Bấm giỏ hàng chọn màu."',
      }),
      v('Unbox bộ quà tặng mỹ phẩm', 'Kling', 'ASMR mở hộp quà mỹ phẩm sang trọng.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh hộp quà] A luxury gift set box with a satin ribbon on marble, hands untie the ribbon.'),
          sc('5–11s', 'MỞ', 'Kling', 'The magnetic lid opens revealing 4 mini products in velvet slots, slow push in.'),
          sc('11–15s', 'KẾT', 'Kling', 'Hands lift one product toward the camera, sparkle light.'),
        ],
        audio: 'ASMR mở hộp; nhạc nhẹ.',
        text: 'Thành phần bộ quà · giá · tặng kèm túi.',
        cta: '"Quà tặng hoàn hảo – link ở giỏ hàng."',
      }),
      v('Sữa dưỡng thể – lifestyle', 'Kling', 'Video cảm giác mềm mịn, thơm mát cho body lotion.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Macro: creamy lotion swirls slowly, silky texture, soft pink background.'),
          sc('4–10s', 'SỬ DỤNG', 'Kling', 'A woman applies lotion on her arm after a shower, steam, sunlight from a window.'),
          sc('10–15s', 'KẾT', 'Kling', '[Ảnh sản phẩm] The bottle among fresh flowers, slow orbit.'),
        ],
        audio: 'nhạc thư giãn.',
        text: 'Mùi hương · dung tích · giá.',
        cta: '"Mua combo 2 chai tiết kiệm hơn."',
      }),
      v('3 sai lầm khi skincare (hoạt hình)', 'Kling, ElevenLabs', 'Video kiến thức dạng hoạt hình – xây kênh chuyên gia.', {
        info: '35 giây · dọc 9:16 · Kling (3D) + lời kể',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '3D animation: a cute cartoon face character looks in a mirror, confused, surrounded by too many skincare bottles.', 'Lời kể: "3 sai lầm khiến da bạn mãi không đẹp!"'),
          sc('5–14s', 'SAI LẦM 1', 'Kling', '3D animation: the character scrubs its face too hard, face turns red.', '"Một: tẩy tế bào chết quá nhiều."'),
          sc('14–23s', 'SAI LẦM 2', 'Kling', '3D animation: the character skips sunscreen, a cartoon sun burns it.', '"Hai: bỏ qua kem chống nắng."'),
          sc('23–35s', 'SAI LẦM 3', 'Kling', '3D animation: the character applies 10 products at once, then simplifies to 3 and smiles.', '"Ba: dùng quá nhiều sản phẩm. Đơn giản mà đều đặn mới hiệu quả!"'),
        ],
        audio: 'nhạc vui; SFX: "buzz" sai, "ting" đúng.',
        text: 'Sai lầm 1–2–3.',
        cta: '"Theo dõi để học skincare đúng cách."',
      }),
    ],
  },
];
