// Bổ sung kịch bản video AI (14 / ngành) – phần 4.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Gym & Thể hình',
    prompts: [
      v('Bài tập tại nhà 10 phút', 'VEO3, Kling', 'Video bài tập không dụng cụ – rất được lưu.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'COACH: a 28-year-old Vietnamese female trainer, high ponytail, black sports set.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `COACH in a living room with a yoga mat. ${N}`, 'HLV: "10 phút tại nhà, không cần dụng cụ!"'),
          sc('4–24s', 'BÀI TẬP', 'Kling', 'COACH demonstrates jumping jacks, squats, push-ups, plank, mountain climbers – each 4 seconds, side view.'),
          sc('24–30s', 'KẾT', 'VEO3', `COACH smiles, wiping sweat. ${N}`, '"Lặp lại 3 vòng nhé!"'),
        ],
        audio: 'beat năng động; SFX: tiếng đếm.',
        text: 'Tên bài + số giây mỗi bài.',
        cta: '"Lưu lại và tập ngay hôm nay."',
      }),
      v('Thực đơn ăn sạch 1 ngày', 'Kling, VEO3', 'Video dinh dưỡng cho người tập (không thay tư vấn chuyên gia).', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'FIT: a 30-year-old Vietnamese man, athletic, grey T-shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `FIT in a kitchen with meal prep boxes. ${N}`, 'Anh: "Một ngày ăn gì để giữ dáng?"'),
          sc('4–20s', 'BỮA ĂN', 'Kling', 'Top-down: oatmeal with banana, chicken breast with brown rice and broccoli, salmon salad, Greek yogurt with nuts.'),
          sc('20–25s', 'KẾT', 'VEO3', `FIT smiles. ${N}`, '"Ăn đủ, tập đều – không cần nhịn đói."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Bữa sáng · trưa · tối · phụ · "Tham khảo – nhu cầu mỗi người khác nhau".',
        cta: '"Đăng ký tư vấn dinh dưỡng cùng PT."',
      }),
      v('Lớp group (Zumba / Aerobic)', 'Kling', 'Video không khí lớp nhóm sôi động.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A group of Vietnamese women dance energetically in a bright studio, colorful lights.'),
          sc('5–11s', 'KHÔNG KHÍ', 'Kling', 'Instructor on stage leads, everyone smiling, sweat.'),
          sc('11–15s', 'KẾT', 'Kling', 'Group high-fives at the end.'),
        ],
        audio: 'nhạc dance sôi động.',
        text: 'Lịch lớp · giá.',
        cta: '"Tham gia lớp thử miễn phí."',
      }),
      v('PT 1 kèm 1', 'VEO3, Kling', 'Video dịch vụ huấn luyện cá nhân.', {
        info: '25 giây · dọc 9:16 · VEO3 + Kling',
        character: 'PT: a 32-year-old Vietnamese male trainer, muscular, black polo with "Coach" print. CLIENT: a 35-year-old Vietnamese woman, beginner.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `PT measures CLIENT\'s body with a tablet. ${N}`, 'PT: "Đầu tiên mình đo chỉ số để lên giáo án riêng."'),
          sc('5–18s', 'TẬP', 'Kling', 'PT guides CLIENT on a cable machine, correcting her posture.'),
          sc('18–25s', 'KẾT', 'VEO3', `CLIENT smiles at the camera. ${N}`, 'Khách: "Có người kèm nên tập đúng và không bỏ cuộc."'),
        ],
        audio: 'nhạc gym.',
        text: 'Gói PT · số buổi · giá.',
        cta: '"Đăng ký buổi PT thử miễn phí."',
      }),
      v('Thử thách 7 ngày', 'VEO3, Kling', 'Video thử thách tạo cộng đồng.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'HOST: a 26-year-old Vietnamese woman, sporty, headband.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `HOST points at the camera. ${N}`, 'Host: "Thử thách 7 ngày plank – bạn dám không?"'),
          sc('4–16s', 'LỊCH', 'Kling', 'Calendar days flip, HOST planks with increasing time: 30s, 45s, 60s…'),
          sc('16–20s', 'KẾT', 'VEO3', `HOST gives a thumbs up. ${N}`, '"Tag bạn bè cùng làm!"'),
        ],
        audio: 'beat mạnh.',
        text: 'Ngày 1 → 7: thời gian plank.',
        cta: '"Comment \'THAM GIA\' để nhận lịch tập."',
      }),
      v('Boxing – giải tỏa căng thẳng', 'Kling', 'Video lớp boxing / kickboxing.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'BOXER: a 27-year-old Vietnamese woman, braided hair, red boxing gloves.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'BOXER punches a heavy bag, slow motion sweat, dramatic light.'),
          sc('5–11s', 'TẬP', 'Kling', 'Pad work with a coach, fast combinations.'),
          sc('11–15s', 'KẾT', 'Kling', 'BOXER smiles, breathing hard.'),
        ],
        audio: 'beat mạnh; SFX: đấm bao.',
        text: '"Đốt [x] calo/buổi" (tham khảo).',
        cta: '"Thử lớp boxing miễn phí."',
      }),
      v('Hội viên lớn tuổi khỏe mạnh', 'VEO3, Kling', 'Video truyền cảm hứng cho người trung niên.', {
        info: '25 giây · dọc 9:16 · VEO3 + Kling',
        character: 'UNCLE: a 60-year-old Vietnamese man, grey hair, fit, white tank top.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `UNCLE in the gym, faces the camera. ${N}`, 'Chú: "60 tuổi, tôi mới bắt đầu tập gym."'),
          sc('5–18s', 'TẬP', 'Kling', 'UNCLE lifts light dumbbells, walks on a treadmill, stretches with a coach.'),
          sc('18–25s', 'KẾT', 'VEO3', `UNCLE smiles. ${N}`, '"Giờ leo cầu thang không còn mệt. Không bao giờ là muộn!"'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: '"Tập theo hướng dẫn của HLV".',
        cta: '"Lớp dành cho người trung niên – đăng ký ngay."',
      }),
      v('Cơ sở vật chất phòng gym', 'Kling', 'Tour nhanh phòng tập.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh thật] FPV fly-through of the gym entrance into rows of machines.'),
          sc('5–11s', 'KHU VỰC', 'Kling', 'Free weights zone, cardio zone, stretching zone, locker room.'),
          sc('11–15s', 'KẾT', 'Kling', 'Panoramic view of the gym with city lights.'),
        ],
        audio: 'EDM.',
        text: 'Diện tích · giờ mở cửa.',
        cta: '"Ghé tham quan miễn phí."',
      }),
      v('Stretching sau giờ làm', 'Kling', 'Video giãn cơ cho dân văn phòng.', {
        info: '20 giây · dọc 9:16 · Kling',
        character: 'WORKER: a 29-year-old Vietnamese office woman in office clothes at her desk.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'WORKER rubs her stiff neck at her desk.'),
          sc('4–16s', 'ĐỘNG TÁC', 'Kling', 'WORKER does neck rolls, shoulder stretches, seated twists – slow, clear.'),
          sc('16–20s', 'KẾT', 'Kling', 'WORKER relaxes and smiles.'),
        ],
        audio: 'nhạc thư giãn.',
        text: 'Tên động tác · số giây.',
        cta: '"Lưu lại tập mỗi ngày."',
      }),
      v('Ưu đãi gói năm', 'VEO3', 'Talking head ưu đãi nhanh.', {
        info: '12 giây · dọc 9:16 · VEO3',
        character: 'MANAGER: a 33-year-old Vietnamese male gym manager, polo shirt with logo.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `MANAGER at the gym front desk. ${N}`, 'Quản lý: "Tháng này duy nhất!"'),
          sc('4–12s', 'ƯU ĐÃI', 'VEO3', `MANAGER counts on fingers. ${N}`, '"Gói 12 tháng tặng thêm 3 tháng và 2 buổi PT."'),
        ],
        audio: 'nhạc sôi động.',
        text: 'Ưu đãi · hạn chót.',
        cta: '"Inbox giữ suất."',
      }),
      v('Calisthenics – kỹ năng nâng cao', 'Kling', 'Video kỹ năng ấn tượng thu hút người xem.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'ATHLETE: a 25-year-old Vietnamese man, lean muscular, black shorts.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'ATHLETE performs a muscle-up on outdoor bars at sunset, slow motion.'),
          sc('5–11s', 'KỸ NĂNG', 'Kling', 'ATHLETE holds a human flag, then a handstand.'),
          sc('11–15s', 'KẾT', 'Kling', 'ATHLETE lands and walks toward the camera.'),
        ],
        audio: 'beat hip-hop.',
        text: '"Khóa calisthenics cho người mới".',
        cta: '"Đăng ký lớp kỹ năng."',
      }),
      v('Câu chuyện HLV', 'VEO3, Kling', 'HLV kể hành trình của mình – xây thương hiệu cá nhân.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'COACH: a 31-year-old Vietnamese male coach, short hair, sleeveless shirt.',
        scenes: [
          sc('0–6s', 'HOOK', 'VEO3', `COACH in an empty gym at night. ${N}`, 'HLV: "5 năm trước tôi nặng 95 ký."'),
          sc('6–20s', 'HÀNH TRÌNH', 'Kling', 'Montage: running in rain, training alone, studying nutrition books, getting a coaching certificate.'),
          sc('20–30s', 'KẾT', 'VEO3', `COACH coaching a client, then faces the camera. ${N}`, '"Giờ tôi giúp người khác làm điều tôi đã làm được."'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: 'Chứng chỉ (đúng thực tế).',
        cta: '"Tập cùng tôi – inbox ngay."',
      }),
      v('Sai lầm khi tập gym', 'VEO3', 'Video kiến thức tránh chấn thương.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'COACH: a 29-year-old Vietnamese female coach, braid, white tank top.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `COACH in the gym. ${N}`, 'HLV: "3 sai lầm khiến bạn tập mãi không lên!"'),
          sc('4–24s', 'SAI LẦM', 'VEO3', `COACH demonstrates each mistake then the correct way. ${N}`, '"Bỏ khởi động, tạ quá nặng sai tư thế, và không ngủ đủ."'),
          sc('24–30s', 'KẾT', 'VEO3', `COACH smiles. ${N}`, '"Sửa ngay nhé!"'),
        ],
        audio: 'nhạc gym.',
        text: 'Sai lầm 1–2–3.',
        cta: '"Theo dõi để tập đúng cách."',
      }),
      v('Yoga đôi / gia đình', 'Kling', 'Video yoga cặp đôi vui vẻ.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'PAIR: a Vietnamese mother and her 10-year-old daughter in matching yoga outfits.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'PAIR do a tree pose side by side in a sunny garden.'),
          sc('5–11s', 'TƯ THẾ', 'Kling', 'PAIR do a partner boat pose, laughing when wobbling.'),
          sc('11–15s', 'KẾT', 'Kling', 'PAIR hug on the mat.'),
        ],
        audio: 'nhạc nhẹ vui.',
        text: 'Lớp yoga gia đình cuối tuần.',
        cta: '"Đăng ký lớp yoga gia đình."',
      }),
    ],
  },

  {
    name: 'Y tế & Nha khoa',
    prompts: [
      v('Chải răng đúng cách', 'Kling, VEO3', 'Hướng dẫn chải răng – nội dung giáo dục an toàn.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'DENTIST: a 35-year-old Vietnamese male dentist, white coat, mask down, friendly.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `DENTIST holds a toothbrush. ${N}`, 'Nha sĩ: "Bạn có đang chải răng sai cách không?"'),
          sc('4–20s', 'HƯỚNG DẪN', 'Kling', '3D close-up animation of teeth: brush at 45 degrees, small circular motions, inner surfaces, tongue.'),
          sc('20–25s', 'KẾT', 'VEO3', `DENTIST smiles. ${N}`, '"Chải 2 phút, 2 lần mỗi ngày nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Các bước chải răng.',
        cta: '"Khám răng định kỳ 6 tháng – đặt lịch ngay."',
      }),
      v('Tẩy trắng răng – giải đáp', 'VEO3', 'Bác sĩ giải đáp thắc mắc phổ biến, không cam kết kết quả.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'DENTIST: a 33-year-old Vietnamese female dentist, white coat, hair tied.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `DENTIST in the clinic. ${N}`, 'Nha sĩ: "Tẩy trắng răng có hại men răng không?"'),
          sc('5–24s', 'GIẢI ĐÁP', 'VEO3', `DENTIST explains calmly. ${N}`, '"Nếu được bác sĩ thăm khám và làm đúng quy trình thì an toàn. Có thể ê buốt nhẹ vài ngày."'),
          sc('24–30s', 'KẾT', 'VEO3', `DENTIST smiles. ${N}`, '"Hãy khám trước để biết bạn có phù hợp không."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Kết quả tùy tình trạng răng".',
        cta: '"Đặt lịch tư vấn tẩy trắng."',
      }),
      v('Trẻ em đi khám răng không sợ', 'Kling, VEO3', 'Video nha khoa trẻ em thân thiện.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'KID: a 6-year-old Vietnamese boy, nervous. DENTIST: a kind female dentist with colorful scrubs.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'KID hides behind his mother at a colorful kids dental clinic.'),
          sc('5–15s', 'LÀM QUEN', 'VEO3', `DENTIST shows KID a toy and a mirror, KID laughs. ${N}`, 'Bác sĩ: "Mình đếm răng cùng bạn khủng long nha!"'),
          sc('15–25s', 'KẾT', 'Kling', 'KID gets a sticker and a balloon, smiling.'),
        ],
        audio: 'nhạc thiếu nhi.',
        text: 'Khu khám riêng cho bé.',
        cta: '"Đặt lịch khám răng cho bé."',
      }),
      v('Khám mắt cho học sinh', 'Kling, VEO3', 'Video chương trình khám mắt.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'DOCTOR: a 40-year-old Vietnamese female ophthalmologist, white coat.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A student squints at the blackboard in class.'),
          sc('5–14s', 'KHÁM', 'Kling', 'DOCTOR checks the student\'s eyes with an eye chart and equipment.'),
          sc('14–20s', 'KẾT', 'VEO3', `DOCTOR faces the camera. ${N}`, 'Bác sĩ: "Nên kiểm tra mắt cho trẻ định kỳ mỗi năm."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Chương trình khám · thời gian.',
        cta: '"Đặt lịch khám mắt."',
      }),
      v('Vật lý trị liệu đau lưng', 'Kling, VEO3', 'Video dịch vụ vật lý trị liệu.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'THERAPIST: a 34-year-old Vietnamese male physiotherapist, navy scrubs. PATIENT: a 45-year-old office man.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'PATIENT holds his lower back in pain at his office desk.'),
          sc('5–18s', 'TRỊ LIỆU', 'Kling', 'THERAPIST guides stretching exercises and uses a therapy device in a bright clinic.'),
          sc('18–25s', 'KẾT', 'VEO3', `THERAPIST faces the camera. ${N}`, 'KTV: "Kết hợp tập luyện và tư thế ngồi đúng để cải thiện lâu dài."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thăm khám để có phác đồ phù hợp".',
        cta: '"Đặt lịch đánh giá miễn phí."',
      }),
      v('Tiêm chủng cho bé', 'Kling, VEO3', 'Video thông tin tiêm chủng an toàn.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'NURSE: a 30-year-old Vietnamese female nurse, light pink scrubs.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A clean bright vaccination center, parents waiting with babies.'),
          sc('5–13s', 'QUY TRÌNH', 'Kling', 'Doctor check-up before vaccination, NURSE gently comforts a baby.'),
          sc('13–20s', 'KẾT', 'VEO3', `NURSE faces the camera. ${N}`, 'Điều dưỡng: "Theo dõi 30 phút sau tiêm để đảm bảo an toàn."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Lịch tiêm · giờ làm việc.',
        cta: '"Đặt lịch tiêm cho bé."',
      }),
      v('Xét nghiệm tại nhà', 'Kling, VEO3', 'Video dịch vụ lấy mẫu tại nhà.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'TECH: a 28-year-old Vietnamese female lab technician, blue uniform, medical bag.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'TECH rides a scooter to a home, rings the bell.'),
          sc('5–13s', 'LẤY MẪU', 'Kling', 'TECH takes a blood sample from an elderly man at home, careful and gentle.'),
          sc('13–20s', 'KẾT', 'VEO3', `TECH faces the camera. ${N}`, 'Kỹ thuật viên: "Kết quả gửi qua điện thoại trong ngày."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Khu vực phục vụ · giá.',
        cta: '"Gọi đặt lịch lấy mẫu tại nhà."',
      }),
      v('Dinh dưỡng cho người tiểu đường', 'Kling, ElevenLabs', 'Video kiến thức tham khảo, khuyến khích hỏi bác sĩ.', {
        info: '35 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'A healthy plate divided: half vegetables, a quarter lean protein, a quarter whole grains.', 'Lời kể: "Đĩa ăn cân bằng cho người cần kiểm soát đường huyết."'),
          sc('6–25s', 'GIẢI THÍCH', 'Kling', 'Close-ups of vegetables, fish, brown rice, fruit portions.', '"Một nửa rau, một phần tư đạm, một phần tư tinh bột nguyên hạt."'),
          sc('25–35s', 'KẾT', 'Kling', 'An elderly couple eating together happily.', '"Hãy hỏi bác sĩ để có chế độ phù hợp với bạn."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Đặt lịch tư vấn dinh dưỡng."',
      }),
      v('Đội ngũ bác sĩ phòng khám', 'Kling, VEO3', 'Giới thiệu đội ngũ – tạo niềm tin.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'DIRECTOR: a 50-year-old Vietnamese male clinic director, white coat, glasses.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'A team of doctors and nurses walk together down a bright clinic corridor.'),
          sc('6–18s', 'ĐỘI NGŨ', 'Kling', 'Each specialist at work: pediatrics, internal medicine, ultrasound.'),
          sc('18–25s', 'KẾT', 'VEO3', `DIRECTOR faces the camera. ${N}`, 'Giám đốc: "Chúng tôi luôn lắng nghe và giải thích rõ cho từng bệnh nhân."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Chuyên khoa · giờ làm việc.',
        cta: '"Đặt lịch khám."',
      }),
      v('Răng sứ – quy trình', 'Kling, VEO3', 'Video quy trình làm răng sứ minh bạch.', {
        info: '30 giây · dọc 9:16 · Kling + VEO3',
        character: 'DENTIST: a 38-year-old Vietnamese male dentist, white coat.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `DENTIST holds a dental model. ${N}`, 'Nha sĩ: "Làm răng sứ gồm những bước nào?"'),
          sc('5–24s', 'QUY TRÌNH', 'Kling', '3D animation: digital scan, tooth preparation, crown design on computer, fitting.'),
          sc('24–30s', 'KẾT', 'VEO3', `DENTIST smiles. ${N}`, '"Thăm khám để biết bạn có cần làm hay không nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Kết quả tùy tình trạng răng".',
        cta: '"Đặt lịch chụp phim miễn phí."',
      }),
      v('Sức khỏe tinh thần – chăm sóc bản thân', 'Kling, ElevenLabs', 'Video kiến thức nhẹ nhàng về giảm căng thẳng.', {
        info: '30 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'A stressed young woman at her laptop late at night, cool tone.', 'Lời kể: "Căng thẳng kéo dài? Thử 3 thói quen nhỏ này."'),
          sc('6–24s', 'THÓI QUEN', 'Kling', 'She walks in a park, writes in a journal, puts her phone away before bed.', '"Đi bộ 15 phút, viết ra điều biết ơn, rời màn hình trước khi ngủ."'),
          sc('24–30s', 'KẾT', 'Kling', 'She sleeps peacefully, morning sunlight.', '"Nếu kéo dài, hãy tìm đến chuyên gia."'),
        ],
        audio: 'nhạc thư giãn.',
        text: '"Thông tin tham khảo".',
        cta: '"Đặt lịch tư vấn tâm lý."',
      }),
      v('Khám sức khỏe doanh nghiệp', 'Kling', 'Video dịch vụ khám định kỳ cho công ty.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A medical team sets up check-up stations inside a company office.'),
          sc('5–15s', 'QUY TRÌNH', 'Kling', 'Employees queue, measure blood pressure, eye test, consultation.'),
          sc('15–20s', 'KẾT', 'Kling', 'HR manager shakes hands with the medical team.'),
        ],
        audio: 'nhạc doanh nghiệp nhẹ.',
        text: 'Gói khám doanh nghiệp.',
        cta: '"Nhận báo giá khám sức khỏe doanh nghiệp."',
      }),
      v('Niềng răng trong suốt – giải đáp', 'VEO3', 'Bác sĩ trả lời câu hỏi về niềng trong suốt.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'DENTIST: a 36-year-old Vietnamese female orthodontist, white coat, glasses.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `DENTIST holds clear aligners. ${N}`, 'Bác sĩ: "Niềng trong suốt có thật sự hiệu quả?"'),
          sc('5–24s', 'GIẢI ĐÁP', 'VEO3', `DENTIST explains. ${N}`, '"Phù hợp với nhiều trường hợp, nhưng cần đeo đủ 20–22 giờ mỗi ngày và tái khám đúng hẹn."'),
          sc('24–30s', 'KẾT', 'VEO3', `DENTIST smiles. ${N}`, '"Khám để biết bạn có phù hợp không nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Kết quả tùy tình trạng răng".',
        cta: '"Đặt lịch tư vấn niềng răng."',
      }),
      v('Nhà thuốc – tư vấn tận tâm', 'VEO3, Kling', 'Video nhà thuốc thân thiện.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'PHARMACIST: a 32-year-old Vietnamese female pharmacist, white coat, name badge.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A clean pharmacy with organized shelves, bright light.'),
          sc('5–15s', 'TƯ VẤN', 'VEO3', `PHARMACIST explains to an elderly customer. ${N}`, 'Dược sĩ: "Bác uống sau ăn, ngày 2 lần, đúng theo đơn bác sĩ nha."'),
          sc('15–20s', 'KẾT', 'Kling', 'The elderly customer smiles and thanks her.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Giờ mở cửa · giao thuốc tận nơi.',
        cta: '"Gọi để được dược sĩ tư vấn."',
      }),
    ],
  },

  {
    name: 'Ô tô & Xe máy',
    prompts: [
      v('Rửa xe chi tiết (detailing) ASMR', 'Kling', 'Video chăm sóc xe đã mắt.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Thick snow foam covers a dark car, slow motion.'),
          sc('4–11s', 'RỬA', 'Kling', 'Pressure washer rinses foam, a microfiber towel dries, polish applied.'),
          sc('11–15s', 'KẾT', 'Kling', 'Glossy car paint reflects lights, slow orbit.'),
        ],
        audio: 'ASMR: nước, bọt.',
        text: 'Gói detailing · giá.',
        cta: '"Đặt lịch chăm sóc xe."',
      }),
      v('Dán phim cách nhiệt', 'Kling, VEO3', 'Video dịch vụ phụ kiện ô tô.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'TECH: a 30-year-old Vietnamese technician, black uniform, gloves.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A driver squints in harsh sunlight inside a hot car.'),
          sc('5–14s', 'THI CÔNG', 'Kling', 'TECH applies window tint film with a squeegee, precise.'),
          sc('14–20s', 'KẾT', 'VEO3', `TECH faces the camera. ${N}`, 'Kỹ thuật viên: "Giảm nóng, chống tia UV, bảo hành [x] năm."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Thương hiệu phim · bảo hành.',
        cta: '"Đặt lịch dán phim."',
      }),
      v('Mẹo lái xe an toàn mùa mưa', 'VEO3, Kling', 'Video kiến thức lái xe.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'INSTRUCTOR: a 45-year-old Vietnamese male driving instructor, polo shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'Car driving in heavy rain at night, wipers moving.'),
          sc('4–24s', 'MẸO', 'VEO3', `INSTRUCTOR in the driver seat explains. ${N}`, 'Thầy: "Giảm tốc, giữ khoảng cách gấp đôi, bật đèn, tránh phanh gấp."'),
          sc('24–30s', 'KẾT', 'VEO3', `INSTRUCTOR nods. ${N}`, '"An toàn là trên hết."'),
        ],
        audio: 'tiếng mưa, nhạc nhẹ.',
        text: '4 mẹo lái xe mùa mưa.',
        cta: '"Đăng ký khóa học lái xe."',
      }),
      v('Xe gia đình 7 chỗ', 'Kling, VEO3', 'Video xe cho chuyến đi gia đình.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'FAMILY: a Vietnamese family of 5 – parents in their 30s, two kids and a grandmother.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '[Ảnh xe thật] FAMILY loads luggage into a 7-seat SUV, kids excited.'),
          sc('6–16s', 'HÀNH TRÌNH', 'Kling', 'The SUV drives along a coastal road, kids watching the sea from the third row.'),
          sc('16–25s', 'KẾT', 'VEO3', `FAMILY at a beach, the father faces the camera. ${N}`, 'Người bố: "Đủ chỗ cho cả nhà, đi xa vẫn thoải mái."'),
        ],
        audio: 'nhạc vui.',
        text: 'Số chỗ · khoang hành lý · giá.',
        cta: '"Đặt lịch lái thử cùng gia đình."',
      }),
      v('Thay nhớt xe máy nhanh', 'Kling, VEO3', 'Video tiệm sửa xe máy.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'MECHANIC: a 35-year-old Vietnamese man, grey work shirt, gloves.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'A motorbike rolls into a small repair shop.'),
          sc('4–11s', 'THAY NHỚT', 'Kling', 'MECHANIC drains old oil, pours new oil, checks tire pressure.'),
          sc('11–15s', 'KẾT', 'VEO3', `MECHANIC gives a thumbs up. ${N}`, 'Thợ: "10 phút là xong, kiểm tra xe miễn phí."'),
        ],
        audio: 'nhạc vui.',
        text: 'Giá thay nhớt · giờ mở cửa.',
        cta: '"Ghé tiệm hoặc gọi [số]."',
      }),
      v('Mua xe trả góp', 'VEO3', 'Video tư vấn tài chính mua xe (thông tin minh bạch).', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'ADVISOR: a 28-year-old Vietnamese woman, showroom uniform.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `ADVISOR next to a car. ${N}`, 'Tư vấn: "Chưa đủ tiền vẫn có thể sở hữu xe?"'),
          sc('4–20s', 'GIẢI THÍCH', 'VEO3', `ADVISOR explains with a tablet showing a payment chart. ${N}`, '"Trả trước từ [x]%, góp hàng tháng, thủ tục nhanh. Đọc kỹ lãi suất và điều khoản trước khi ký."'),
          sc('20–25s', 'KẾT', 'VEO3', `ADVISOR smiles. ${N}`, '"Inbox để tính khoản góp phù hợp."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Ví dụ khoản góp (tham khảo).',
        cta: '"Nhận bảng tính trả góp."',
      }),
      v('Phụ kiện xe máy', 'Kling', 'Video phụ kiện: mũ bảo hiểm, áo mưa, giá đỡ điện thoại.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh sản phẩm] A stylish helmet rotates on a stand, glossy.'),
          sc('5–11s', 'SẢN PHẨM', 'Kling', 'Phone holder clips onto handlebars, a raincoat unfolds.'),
          sc('11–15s', 'KẾT', 'Kling', 'A rider wears the gear and rides away.'),
        ],
        audio: 'nhạc vui.',
        text: 'Giá từng món.',
        cta: '"Mua trong giỏ hàng."',
      }),
      v('Xe điện ô tô – sạc tại nhà', 'Kling, VEO3', 'Video ô tô điện tiết kiệm chi phí.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'OWNER: a 35-year-old Vietnamese man, casual shirt.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh xe thật] An electric car silently enters a home garage at night.'),
          sc('5–13s', 'SẠC', 'Kling', 'OWNER plugs in the home charger, dashboard shows charging.'),
          sc('13–20s', 'KẾT', 'VEO3', `OWNER faces the camera. ${N}`, 'Chủ xe: "Sạc qua đêm, sáng ra đầy pin đi làm."'),
        ],
        audio: 'nhạc hiện đại.',
        text: 'Quãng đường 1 lần sạc (đúng thông số hãng).',
        cta: '"Đặt lịch lái thử xe điện."',
      }),
      v('Đánh giá xe cũ trước khi mua', 'VEO3', 'Video kinh nghiệm mua xe cũ.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'EXPERT: a 40-year-old Vietnamese male mechanic, cap, flashlight.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `EXPERT next to a used car. ${N}`, 'Chuyên gia: "Mua xe cũ, kiểm tra 4 điểm này!"'),
          sc('4–24s', 'KIỂM TRA', 'VEO3', `EXPERT checks the engine bay, tires, under the car, and papers. ${N}`, '"Khoang máy, lốp, gầm xe, và giấy tờ chính chủ."'),
          sc('24–30s', 'KẾT', 'VEO3', `EXPERT nods. ${N}`, '"Cần kiểm tra giúp, inbox mình."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '4 điểm kiểm tra.',
        cta: '"Đặt dịch vụ kiểm tra xe cũ."',
      }),
      v('Chạy thử xe phân khối lớn', 'Kling', 'Video mô tô mạnh mẽ.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'RIDER: a Vietnamese rider in full black leather gear and helmet.',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', '[Ảnh xe thật] Close-up of the exhaust and engine as it revs, dramatic light.'),
          sc('4–11s', 'CHẠY', 'Kling', 'RIDER leans into a curve on a mountain road, low tracking shot.'),
          sc('11–15s', 'KẾT', 'Kling', 'RIDER stops at a viewpoint, removes helmet.'),
        ],
        audio: 'tiếng động cơ, nhạc rock.',
        text: 'Tên mẫu xe · giá.',
        cta: '"Đăng ký lái thử."',
      }),
      v('Cứu hộ xe 24/7', 'Kling, VEO3', 'Video dịch vụ cứu hộ.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'DRIVER: a 30-year-old Vietnamese woman standing beside a broken car at night.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'DRIVER beside a car with hazard lights on a dark road, worried, calling on her phone.'),
          sc('5–14s', 'CỨU HỘ', 'Kling', 'A tow truck arrives, technicians help quickly.'),
          sc('14–20s', 'KẾT', 'VEO3', `DRIVER relieved, thanks the technician. ${N}`, 'Tài xế: "May quá, có mặt chỉ sau 20 phút!"'),
        ],
        audio: 'nhạc hồi hộp → yên tâm.',
        text: 'Hotline 24/7 · khu vực.',
        cta: '"Lưu số hotline cứu hộ."',
      }),
      v('Xe cho người mới lái', 'VEO3, Kling', 'Video tư vấn chọn xe đầu tiên.', {
        info: '25 giây · dọc 9:16 · VEO3 + Kling',
        character: 'ADVISOR: a 30-year-old Vietnamese man, showroom polo.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `ADVISOR in a showroom. ${N}`, 'Tư vấn: "Mới lái nên chọn xe thế nào?"'),
          sc('4–18s', 'TIÊU CHÍ', 'Kling', 'Shots of a compact car: easy parking, rear camera, sensors, fuel gauge.'),
          sc('18–25s', 'KẾT', 'VEO3', `ADVISOR smiles. ${N}`, '"Nhỏ gọn, nhiều cảm biến, tiết kiệm nhiên liệu."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Tiêu chí chọn xe.',
        cta: '"Đặt lịch lái thử."',
      }),
      v('Độ đèn xe – trước & sau', 'Kling', 'Video dịch vụ độ đèn.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–4s', 'TRƯỚC', 'Kling', 'Dim yellow headlights on a dark road.'),
          sc('4–11s', 'LẮP ĐẶT', 'Kling', 'Technician installs new LED headlights.'),
          sc('11–15s', 'SAU', 'Kling', 'Bright white headlights illuminate the road clearly.'),
        ],
        audio: 'nhạc mạnh; SFX: "click".',
        text: '"Trước" / "Sau" · bảo hành.',
        cta: '"Đặt lịch độ đèn."',
      }),
      v('Showroom khai trương', 'Kling, VEO3', 'Video sự kiện khai trương showroom.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'DIRECTOR: a 45-year-old Vietnamese man in a navy suit.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Lion dance in front of a new car showroom, confetti.'),
          sc('5–13s', 'SỰ KIỆN', 'Kling', 'Cars unveiled under covers, guests taking photos.'),
          sc('13–20s', 'KẾT', 'VEO3', `DIRECTOR faces the camera. ${N}`, 'Giám đốc: "Ưu đãi khai trương chỉ trong tuần này!"'),
        ],
        audio: 'trống lân, nhạc sôi động.',
        text: 'Ưu đãi khai trương.',
        cta: '"Ghé showroom nhận quà."',
      }),
    ],
  },
];
