// Bổ sung kịch bản video AI (14 / ngành) – phần 5.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Nông nghiệp & Đặc sản',
    prompts: [
      v('Rau sạch thủy canh', 'Kling, VEO3', 'Video trang trại rau sạch công nghệ cao.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'FARMER: a 30-year-old Vietnamese man, green farm shirt, cap.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Rows of green lettuce in a hydroponic greenhouse, misting system, morning light.'),
          sc('5–13s', 'QUY TRÌNH', 'Kling', 'FARMER checks water pipes, harvests lettuce with roots, packs into eco boxes.'),
          sc('13–20s', 'KẾT', 'VEO3', `FARMER holds fresh lettuce. ${N}`, 'Nông dân: "Không thuốc trừ sâu, hái sáng giao chiều."'),
        ],
        audio: 'nhạc tươi mát.',
        text: 'Giao trong ngày · giá.',
        cta: '"Đặt rau sạch giao tận nhà."',
      }),
      v('Mật ong rừng', 'Kling', 'Video sản phẩm mật ong tự nhiên.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Golden honey drips slowly from a honeycomb, macro, warm backlight.'),
          sc('5–11s', 'NGUỒN GỐC', 'Kling', 'Bees on wild forest flowers, a beekeeper in protective gear.'),
          sc('11–15s', 'SẢN PHẨM', 'Kling', '[Ảnh thật] Honey jar with label on a wooden table, a spoon of honey poured into tea.'),
        ],
        audio: 'nhạc mộc; SFX: tiếng ong.',
        text: 'Nguồn gốc · dung tích · giá.',
        cta: '"Đặt mật ong nguyên chất."',
      }),
      v('Gạo đặc sản', 'Kling, VEO3', 'Video gạo từ cánh đồng đến bữa cơm.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'MOM: a 45-year-old Vietnamese mother, apron, in a home kitchen.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Golden rice fields swaying, farmers harvesting.'),
          sc('6–14s', 'CHẾ BIẾN', 'Kling', 'Rice grains poured into a bag, close-up of long fragrant grains.'),
          sc('14–25s', 'BỮA CƠM', 'VEO3', `MOM opens a rice cooker, steam rises, the family gathers. ${N}`, 'Mẹ: "Cơm dẻo thơm, cả nhà ăn thêm bát nữa!"'),
        ],
        audio: 'nhạc ấm.',
        text: 'Tên gạo · vùng trồng · giá/kg.',
        cta: '"Đặt gạo giao tận nhà."',
      }),
      v('Cà phê từ nông trại', 'Kling, VEO3', 'Video cà phê nguyên chất Tây Nguyên.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'GROWER: a 50-year-old Vietnamese Ede man, traditional shirt, kind face.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Red coffee cherries on branches in the Central Highlands, sunrise.'),
          sc('6–16s', 'CHẾ BIẾN', 'Kling', 'Hand-picking, sun-drying beans, roasting in a drum, smoke.'),
          sc('16–25s', 'KẾT', 'VEO3', `GROWER pours a cup of coffee and smiles. ${N}`, 'Người trồng: "Cà phê nguyên chất, rang mộc."'),
        ],
        audio: 'nhạc cồng chiêng nhẹ.',
        text: 'Nguồn gốc · loại hạt · giá.',
        cta: '"Đặt cà phê rang xay."',
      }),
      v('Hải sản tươi sống', 'Kling, VEO3', 'Video hải sản từ tàu cá đến bàn ăn.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'FISHER: a 45-year-old Vietnamese fisherman, tanned, raincoat.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Fishing boats return at dawn, nets full of shrimp and fish.'),
          sc('5–13s', 'PHÂN LOẠI', 'Kling', 'Live crabs and squid sorted into ice boxes.'),
          sc('13–20s', 'KẾT', 'VEO3', `FISHER holds a live crab. ${N}`, 'Ngư dân: "Hải sản mới đánh bắt, đóng đá giao liền."'),
        ],
        audio: 'tiếng sóng, nhạc vui.',
        text: 'Giao hàng · giá.',
        cta: '"Đặt hải sản tươi."',
      }),
      v('Trái cây sấy dẻo', 'Kling', 'Video đặc sản sấy – quà vặt.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Slices of mango and jackfruit arranged on drying trays, sunlight.'),
          sc('5–11s', 'THÀNH PHẨM', 'Kling', 'Chewy dried mango pieces, a hand bends one, macro.'),
          sc('11–15s', 'KẾT', 'Kling', '[Ảnh thật] Product bags on a table with fresh fruit.'),
        ],
        audio: 'nhạc vui.',
        text: 'Không đường / ít đường (đúng thực tế).',
        cta: '"Mua ngay trong giỏ hàng."',
      }),
      v('Nước mắm truyền thống', 'Kling, VEO3', 'Video câu chuyện làng nghề nước mắm.', {
        info: '30 giây · dọc 9:16 · Kling + VEO3',
        character: 'ARTISAN: a 60-year-old Vietnamese fish sauce maker, white beard, rolled sleeves.',
        scenes: [
          sc('0–8s', 'HOOK', 'Kling', 'Rows of wooden barrels in a traditional fish sauce house by the sea.'),
          sc('8–20s', 'Ủ CHƯỢP', 'Kling', 'Anchovies and salt layered, amber fish sauce drips from a barrel tap.'),
          sc('20–30s', 'KẾT', 'VEO3', `ARTISAN tastes a drop and nods. ${N}`, 'Nghệ nhân: "Ủ đủ 12 tháng mới có giọt nước mắm ngon."'),
        ],
        audio: 'nhạc mộc, tiếng biển.',
        text: 'Độ đạm · thời gian ủ.',
        cta: '"Đặt nước mắm truyền thống."',
      }),
      v('Hạt dinh dưỡng – quà sức khỏe', 'Kling', 'Video hộp hạt dinh dưỡng.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Macadamia, cashews and almonds pour into a bowl in slow motion.'),
          sc('5–11s', 'SẢN PHẨM', 'Kling', '[Ảnh thật] Gift box of nuts opened on a table.'),
          sc('11–15s', 'KẾT', 'Kling', 'Someone adds nuts to yogurt for breakfast.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Thành phần · giá.',
        cta: '"Đặt hộp quà hạt."',
      }),
      v('Trải nghiệm hái dâu', 'Kling, VEO3', 'Video du lịch nông trại.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'KIDS: two Vietnamese children with small baskets.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Rows of strawberry plants in a Da Lat greenhouse.'),
          sc('5–13s', 'HÁI DÂU', 'Kling', 'KIDS pick red strawberries, giggling.'),
          sc('13–20s', 'KẾT', 'VEO3', `One child holds a big strawberry to the camera. ${N}`, 'Bé: "Dâu to nè!"'),
        ],
        audio: 'nhạc vui.',
        text: 'Vé tham quan · giờ mở cửa.',
        cta: '"Đặt vé trải nghiệm vườn dâu."',
      }),
      v('Chứng nhận OCOP / VietGAP', 'VEO3, Kling', 'Video nhấn chứng nhận chất lượng (đúng thực tế).', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'OWNER: a 40-year-old Vietnamese woman, cooperative uniform.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `OWNER holds a certificate. ${N}`, 'Chủ cơ sở: "Sản phẩm vừa đạt chứng nhận [tên chứng nhận]!"'),
          sc('5–14s', 'QUY TRÌNH', 'Kling', 'Clean processing facility, workers in hygiene gear.'),
          sc('14–20s', 'KẾT', 'Kling', 'Product lineup on display.'),
        ],
        audio: 'nhạc tự hào.',
        text: 'Tên chứng nhận (chỉ ghi khi đã đạt).',
        cta: '"Đặt mua sản phẩm đạt chuẩn."',
      }),
      v('Bánh truyền thống làng nghề', 'Kling', 'Video bánh đặc sản thủ công.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Hands wrap green banana leaves around sticky rice cakes.'),
          sc('5–14s', 'LÀM BÁNH', 'Kling', 'Cakes boiled in a big pot over firewood, steam.'),
          sc('14–20s', 'KẾT', 'Kling', 'A cake cut open showing the filling.'),
        ],
        audio: 'nhạc dân gian.',
        text: 'Tên bánh · làng nghề · giá.',
        cta: '"Đặt bánh giao tận nơi."',
      }),
      v('Livestream bán nông sản tại vườn', 'VEO3', 'Trailer livestream tại vườn.', {
        info: '15 giây · dọc 9:16 · VEO3',
        character: 'SELLER: a 28-year-old Vietnamese woman, conical hat, standing in a pomelo orchard.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `SELLER holds a big pomelo. ${N}`, 'Người bán: "Tối nay 8 giờ, live tại vườn bưởi!"'),
          sc('5–15s', 'ƯU ĐÃI', 'VEO3', `SELLER cuts the pomelo showing juicy segments. ${N}`, '"Cắt tại chỗ cho xem, giá tận vườn!"'),
        ],
        audio: 'nhạc vui.',
        text: '"LIVE 20:00".',
        cta: '"Theo dõi để nhận thông báo live."',
      }),
      v('Đóng gói xuất khẩu', 'Kling', 'Video năng lực sản xuất cho đối tác B2B.', {
        info: '25 giây · ngang 16:9 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Modern packing house with conveyor belts of fruit.'),
          sc('6–18s', 'QUY TRÌNH', 'Kling', 'Washing, sorting by size, packing into export boxes, cold storage.'),
          sc('18–25s', 'KẾT', 'Kling', 'Containers loaded at a port.'),
        ],
        audio: 'nhạc doanh nghiệp.',
        text: 'Sản lượng · thị trường (đúng thực tế).',
        cta: '"Liên hệ hợp tác phân phối."',
      }),
      v('Mẹo chọn trái cây ngon', 'VEO3', 'Video kiến thức tăng tương tác.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'SELLER: a 50-year-old Vietnamese fruit seller at a market stall.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `SELLER holds a watermelon. ${N}`, 'Người bán: "Chọn dưa hấu ngon, nhìn 3 điểm này!"'),
          sc('4–20s', 'MẸO', 'VEO3', `SELLER taps the watermelon and points at its spot. ${N}`, '"Vỏ bóng, cuống tươi, gõ nghe tiếng đục, có đốm vàng ở đáy."'),
          sc('20–25s', 'KẾT', 'VEO3', `SELLER smiles. ${N}`, '"Lưu lại đi chợ nha!"'),
        ],
        audio: 'tiếng chợ.',
        text: 'Mẹo chọn dưa.',
        cta: '"Theo dõi để xem thêm mẹo."',
      }),
    ],
  },

  {
    name: 'Công nghệ & Ứng dụng',
    prompts: [
      v('App học ngoại ngữ', 'VEO3 + quay màn hình', 'Video app học tiếng Anh.', {
        info: '20 giây · dọc 9:16 · VEO3 + quay màn hình',
        character: 'USER: a 22-year-old Vietnamese student on a bus with earphones.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `USER on a bus, looks at the camera. ${N}`, 'Sinh viên: "Mỗi ngày 10 phút trên xe buýt là đủ."'),
          sc('4–14s', 'APP', 'Quay màn hình', '(Quay màn hình thật) bài học ngắn, luyện phát âm với AI, chuỗi ngày học.'),
          sc('14–20s', 'KẾT', 'VEO3', `USER smiles. ${N}`, '"Đã học 60 ngày liên tục!"'),
        ],
        audio: 'nhạc vui.',
        text: 'Tên app · miễn phí.',
        cta: '"Tải app ngay."',
      }),
      v('Nhà thông minh (smart home)', 'Kling, VEO3', 'Video thiết bị nhà thông minh.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'OWNER: a 32-year-old Vietnamese man, casual, holding a phone.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'OWNER enters home, lights turn on automatically, curtains open.'),
          sc('5–15s', 'TÍNH NĂNG', 'Kling', 'Voice control turns on the AC, a smart lock opens with a fingerprint.'),
          sc('15–25s', 'KẾT', 'VEO3', `OWNER on the sofa. ${N}`, 'Chủ nhà: "Điều khiển cả nhà chỉ bằng giọng nói."'),
        ],
        audio: 'nhạc hiện đại; SFX: "beep".',
        text: 'Gói lắp đặt · giá.',
        cta: '"Đặt lịch khảo sát miễn phí."',
      }),
      v('Laptop cho sinh viên', 'Kling, VEO3', 'Video tư vấn laptop.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'SALES: a 25-year-old Vietnamese man, store uniform.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `SALES holds a laptop. ${N}`, 'Nhân viên: "Sinh viên nên chọn laptop thế nào?"'),
          sc('4–15s', 'TIÊU CHÍ', 'Kling', '[Ảnh thật] Close-ups: thin body, battery icon, keyboard.'),
          sc('15–20s', 'KẾT', 'VEO3', `SALES smiles. ${N}`, '"Nhẹ, pin lâu, RAM từ 16GB – có giá sinh viên."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Cấu hình · giá.',
        cta: '"Ghé cửa hàng nhận ưu đãi sinh viên."',
      }),
      v('Phần mềm bán hàng cho quán', 'VEO3 + quay màn hình', 'Video phần mềm POS.', {
        info: '25 giây · dọc 9:16 · VEO3 + quay màn hình',
        character: 'OWNER: a 30-year-old Vietnamese café owner at the counter.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `OWNER struggles with handwritten bills at a busy café. ${N}`, 'Chủ quán: "Giờ cao điểm ghi order không kịp!"'),
          sc('5–18s', 'GIẢI PHÁP', 'Quay màn hình', '(Quay màn hình thật) order trên tablet, in bill, báo cáo doanh thu.'),
          sc('18–25s', 'KẾT', 'VEO3', `OWNER relaxed. ${N}`, '"Order nhanh, cuối ngày biết ngay lãi lỗ."'),
        ],
        audio: 'nhạc vui.',
        text: 'Dùng thử miễn phí.',
        cta: '"Đăng ký dùng thử."',
      }),
      v('Tai nghe chống ồn', 'Kling', 'Video sản phẩm tai nghe.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'USER: a 26-year-old Vietnamese woman on a busy street.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'USER on a noisy street with traffic, puts on headphones.'),
          sc('5–11s', 'CHỐNG ỒN', 'Kling', 'The noise fades, the busy street becomes blurred and calm, she smiles.'),
          sc('11–15s', 'SẢN PHẨM', 'Kling', '[Ảnh thật] Headphones rotate on a stand.'),
        ],
        audio: 'tiếng ồn → im lặng → nhạc.',
        text: 'Thời lượng pin · giá.',
        cta: '"Mua ngay."',
      }),
      v('Bảo mật tài khoản', 'VEO3', 'Video kiến thức an toàn số.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'EXPERT: a 33-year-old Vietnamese male IT expert, hoodie, glasses.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `EXPERT at a desk with monitors. ${N}`, 'Chuyên gia: "3 cách để không bị hack Facebook!"'),
          sc('4–24s', 'MẸO', 'VEO3', `EXPERT explains. ${N}`, '"Bật xác thực 2 lớp, mật khẩu riêng cho từng tài khoản, không bấm link lạ."'),
          sc('24–30s', 'KẾT', 'VEO3', `EXPERT nods. ${N}`, '"Chia sẻ cho người thân nhé."'),
        ],
        audio: 'nhạc công nghệ.',
        text: '3 mẹo bảo mật.',
        cta: '"Theo dõi để an toàn trên mạng."',
      }),
      v('Đồng hồ thông minh', 'Kling', 'Video smartwatch.', {
        info: '15 giây · dọc 9:16 · Kling',
        character: 'RUNNER: a 30-year-old Vietnamese man jogging.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '[Ảnh thật] Smartwatch screen lights up on a wrist, close-up.'),
          sc('5–11s', 'SỬ DỤNG', 'Kling', 'RUNNER checks heart rate while jogging, receives a call notification.'),
          sc('11–15s', 'KẾT', 'Kling', 'Watch face rotating on a stand.'),
        ],
        audio: 'nhạc năng động.',
        text: 'Tính năng · giá.',
        cta: '"Đặt mua."',
      }),
      v('AI chatbot cho doanh nghiệp', 'VEO3 + quay màn hình', 'Video giải pháp chăm sóc khách tự động.', {
        info: '25 giây · dọc 9:16 · VEO3 + quay màn hình',
        character: 'OWNER: a 35-year-old Vietnamese woman, online shop owner.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `OWNER overwhelmed by hundreds of messages at night. ${N}`, 'Chủ shop: "Nửa đêm vẫn trả lời tin nhắn…"'),
          sc('5–18s', 'GIẢI PHÁP', 'Quay màn hình', '(Quay màn hình thật) chatbot trả lời giá, tư vấn size, chốt đơn.'),
          sc('18–25s', 'KẾT', 'VEO3', `OWNER sleeping peacefully. ${N}`),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Trả lời 24/7.',
        cta: '"Dùng thử chatbot miễn phí."',
      }),
      v('Sửa điện thoại lấy liền', 'Kling, VEO3', 'Video dịch vụ sửa chữa.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'TECH: a 28-year-old Vietnamese male technician, ESD wristband.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A cracked phone screen placed on a repair mat.'),
          sc('5–14s', 'SỬA', 'Kling', 'TECH replaces the screen with precision tools, macro.'),
          sc('14–20s', 'KẾT', 'VEO3', `TECH hands the phone back. ${N}`, 'Kỹ thuật viên: "30 phút là xong, bảo hành 6 tháng."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Giá thay màn · bảo hành.',
        cta: '"Ghé cửa hàng sửa lấy liền."',
      }),
      v('Camera an ninh gia đình', 'Kling, VEO3', 'Video camera giám sát.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'MOM: a 35-year-old Vietnamese mother at her office.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `MOM at work checks her phone. ${N}`, 'Mẹ: "Đi làm vẫn xem được con ở nhà."'),
          sc('5–14s', 'TÍNH NĂNG', 'Kling', 'Phone screen shows a live camera feed of a child playing with grandma.'),
          sc('14–20s', 'KẾT', 'Kling', 'Small camera installed in a living room corner.'),
        ],
        audio: 'nhạc ấm.',
        text: 'Lắp đặt · giá.',
        cta: '"Đặt lắp camera."',
      }),
      v('Ra mắt sản phẩm công nghệ', 'Kling', 'Teaser ra mắt.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Darkness, a silhouette of a device with light edges.'),
          sc('5–11s', 'HÉ LỘ', 'Kling', 'Fragments of the device revealed with light sweeps.'),
          sc('11–15s', 'KẾT', 'Kling', 'Launch date glow effect.'),
        ],
        audio: 'nhạc hồi hộp.',
        text: '"Ra mắt [ngày]".',
        cta: '"Đăng ký nhận thông báo."',
      }),
      v('Hướng dẫn mẹo dùng điện thoại', 'VEO3', 'Video tips & tricks.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'TECHIE: a 24-year-old Vietnamese woman, purple hair streak, oversized tee.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `TECHIE holds a phone. ${N}`, 'Cô gái: "3 mẹo điện thoại 90% người chưa biết!"'),
          sc('4–20s', 'MẸO', 'VEO3', `TECHIE demonstrates gestures on the phone screen. ${N}`, '"Quét văn bản bằng camera, chụp màn hình dài, khóa ứng dụng riêng."'),
          sc('20–25s', 'KẾT', 'VEO3', `TECHIE winks. ${N}`, '"Theo dõi để biết thêm!"'),
        ],
        audio: 'nhạc trend.',
        text: '3 mẹo.',
        cta: '"Lưu video lại."',
      }),
      v('Website cho doanh nghiệp nhỏ', 'VEO3', 'Video dịch vụ làm website.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'DEV: a 29-year-old Vietnamese male web developer, black tee, laptop.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `DEV in a co-working space. ${N}`, 'Lập trình viên: "Chưa có website, khách khó tin bạn!"'),
          sc('5–18s', 'GIẢI PHÁP', 'VEO3', `DEV shows a website on a laptop. ${N}`, '"Website chuẩn mobile, giới thiệu sản phẩm, nhận đơn online – xong trong 7 ngày."'),
          sc('18–25s', 'KẾT', 'VEO3', `DEV smiles. ${N}`, '"Inbox để xem mẫu."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Gói website · giá.',
        cta: '"Nhận báo giá website."',
      }),
      v('Game mobile – trailer', 'Kling', 'Trailer game di động.', {
        info: '20 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', '3D animated fantasy hero jumps from a cliff, epic.'),
          sc('5–14s', 'GAMEPLAY', 'Kling', 'Battle scenes with magic effects, dragons.'),
          sc('14–20s', 'KẾT', 'Kling', 'Game logo glows.'),
        ],
        audio: 'nhạc sử thi.',
        text: 'Tên game · nền tảng.',
        cta: '"Tải game ngay."',
      }),
    ],
  },

  {
    name: 'Tài chính & Bảo hiểm',
    prompts: [
      v('Quỹ dự phòng khẩn cấp', 'Kling, ElevenLabs', 'Video kiến thức tài chính cơ bản.', {
        info: '30 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '3D animation: a cartoon character\'s car breaks down, he looks at an empty wallet.', 'Lời kể: "Nếu ngày mai mất thu nhập, bạn trụ được bao lâu?"'),
          sc('6–22s', 'GIẢI THÍCH', 'Kling', '3D animation: a piggy bank fills up month by month to "6 tháng chi tiêu".', '"Quỹ dự phòng nên bằng 3–6 tháng chi tiêu, để riêng, dễ rút."'),
          sc('22–30s', 'KẾT', 'Kling', '3D animation: the character smiles calmly.', '"Bắt đầu từ 10% thu nhập mỗi tháng."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Theo dõi để học quản lý tài chính."',
      }),
      v('Bảo hiểm sức khỏe – câu chuyện', 'VEO3, Kling', 'Video cảm xúc không gây sợ hãi.', {
        info: '30 giây · dọc 9:16 · VEO3 + Kling',
        character: 'WIFE: a 34-year-old Vietnamese woman. HUSBAND: a 36-year-old Vietnamese man.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'HUSBAND in a hospital bed recovering, WIFE holds his hand.'),
          sc('6–18s', 'AN TÂM', 'VEO3', `WIFE speaks to the camera in a hospital corridor. ${N}`, 'Vợ: "May mà có bảo hiểm, mình chỉ cần lo chăm anh ấy."'),
          sc('18–30s', 'KẾT', 'Kling', 'The family walks in a park together after recovery.'),
        ],
        audio: 'piano ấm.',
        text: '"Đọc kỹ quy tắc, điều khoản".',
        cta: '"Nhận tư vấn gói bảo hiểm phù hợp."',
      }),
      v('Mở tài khoản online 5 phút', 'Kling + quay màn hình', 'Video hướng dẫn eKYC.', {
        info: '20 giây · dọc 9:16 · Kling + quay màn hình',
        scenes: [
          sc('0–4s', 'HOOK', 'Kling', 'A young person at home with phone and ID card.'),
          sc('4–16s', 'CÁC BƯỚC', 'Quay màn hình', '(Quay màn hình thật) tải app, chụp CCCD, xác thực khuôn mặt, nhận số tài khoản.'),
          sc('16–20s', 'KẾT', 'Kling', 'Phone shows success screen, confetti.'),
        ],
        audio: 'nhạc vui; SFX: "ting".',
        text: 'Bước 1 → 4.',
        cta: '"Mở tài khoản ngay."',
      }),
      v('Lãi kép – sức mạnh thời gian', 'Kling, ElevenLabs', 'Video kiến thức đầu tư cơ bản (không khuyến nghị cụ thể).', {
        info: '35 giây · dọc 9:16 · Kling + lời kể',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', '3D animation: a small seed planted, labeled with a coin.', 'Lời kể: "Vì sao bắt đầu sớm lại quan trọng?"'),
          sc('6–26s', 'GIẢI THÍCH', 'Kling', '3D animation: the seed grows into a big tree over years, coins multiplying on branches.', '"Lãi kép là khi tiền lãi được tái đầu tư và tiếp tục sinh lãi theo thời gian."'),
          sc('26–35s', 'KẾT', 'Kling', '3D animation: a young person and an old person comparing trees.', '"Bắt đầu sớm, dù số tiền nhỏ."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo – không phải khuyến nghị đầu tư".',
        cta: '"Theo dõi để học tài chính cá nhân."',
      }),
      v('Hồ sơ vay mua nhà', 'VEO3', 'Video tư vấn thủ tục vay.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'OFFICER: a 32-year-old Vietnamese female bank officer, uniform.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `OFFICER at a bank desk. ${N}`, 'Chuyên viên: "Vay mua nhà cần chuẩn bị gì?"'),
          sc('4–20s', 'HỒ SƠ', 'VEO3', `OFFICER lists on fingers. ${N}`, '"Giấy tờ cá nhân, chứng minh thu nhập, hồ sơ tài sản, mục đích vay."'),
          sc('20–25s', 'KẾT', 'VEO3', `OFFICER smiles. ${N}`, '"Tính khoản vay phù hợp trước khi quyết định."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Danh sách hồ sơ.',
        cta: '"Đặt lịch tư vấn vay."',
      }),
      v('Kế toán thuế cho hộ kinh doanh', 'VEO3', 'Video kiến thức thuế cơ bản.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'ACCOUNTANT: a 35-year-old Vietnamese female accountant, glasses.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `ACCOUNTANT at her desk. ${N}`, 'Kế toán: "Hộ kinh doanh online có phải đóng thuế không?"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `ACCOUNTANT explains. ${N}`, '"Có thể có, tùy doanh thu và quy định hiện hành. Hãy kê khai đúng để tránh rủi ro."'),
          sc('24–30s', 'KẾT', 'VEO3', `ACCOUNTANT smiles. ${N}`, '"Cần hỗ trợ kê khai, inbox mình."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Kiểm tra quy định hiện hành".',
        cta: '"Nhận tư vấn thuế."',
      }),
      v('Bảo hiểm xe', 'Kling, VEO3', 'Video bảo hiểm vật chất xe.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'DRIVER: a 33-year-old Vietnamese man beside his car.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A small fender scratch on a car in a parking lot.'),
          sc('5–14s', 'BỒI THƯỜNG', 'Kling', 'An inspector photographs the damage, the car repaired at a garage.'),
          sc('14–20s', 'KẾT', 'VEO3', `DRIVER faces the camera. ${N}`, 'Tài xế: "Có bảo hiểm, sửa xe không lo."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Quyền lợi chính (đúng điều khoản).',
        cta: '"Nhận báo giá bảo hiểm xe."',
      }),
      v('Thanh toán QR cho tiểu thương', 'Kling, VEO3', 'Video thanh toán không tiền mặt tại chợ.', {
        info: '15 giây · dọc 9:16 · Kling + VEO3',
        character: 'VENDOR: a 50-year-old Vietnamese woman selling fruit at a market.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A customer scans a QR sign at a fruit stall.'),
          sc('5–11s', 'NHẬN TIỀN', 'Kling', 'VENDOR\'s phone shows the payment notification.'),
          sc('11–15s', 'KẾT', 'VEO3', `VENDOR smiles. ${N}`, 'Cô bán hàng: "Khỏi lo thối tiền lẻ!"'),
        ],
        audio: 'tiếng chợ; SFX: "ting".',
        text: 'Đăng ký mã QR miễn phí.',
        cta: '"Đăng ký nhận mã QR."',
      }),
      v('Tiết kiệm mục tiêu (mua xe, du lịch)', 'Kling + quay màn hình', 'Video tính năng tiết kiệm theo mục tiêu.', {
        info: '20 giây · dọc 9:16 · Kling + quay màn hình',
        character: 'YOUNG: a 25-year-old Vietnamese woman dreaming of travel.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'YOUNG looks at a travel poster on her wall.'),
          sc('5–14s', 'APP', 'Quay màn hình', '(Quay màn hình thật) tạo mục tiêu, tự động trích tiền hàng tháng, thanh tiến độ.'),
          sc('14–20s', 'KẾT', 'Kling', 'YOUNG at the beach, phone shows "Goal reached".'),
        ],
        audio: 'nhạc vui.',
        text: 'Lãi suất (đúng thực tế).',
        cta: '"Tạo mục tiêu tiết kiệm ngay."',
      }),
      v('Báo cáo tài chính cho chủ doanh nghiệp', 'VEO3', 'Video dịch vụ CFO thuê ngoài.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'CFO: a 42-year-old Vietnamese man, grey suit.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `CFO in a meeting room. ${N}`, 'Chuyên gia: "Doanh thu tăng mà sao vẫn hết tiền?"'),
          sc('4–20s', 'GIẢI THÍCH', 'VEO3', `CFO points at a cash flow chart. ${N}`, '"Vì dòng tiền và lợi nhuận là hai chuyện khác nhau. Cần theo dõi công nợ và tồn kho."'),
          sc('20–25s', 'KẾT', 'VEO3', `CFO nods. ${N}`, '"Đặt lịch rà soát miễn phí."'),
        ],
        audio: 'nhạc doanh nghiệp.',
        text: 'Dịch vụ CFO thuê ngoài.',
        cta: '"Liên hệ tư vấn."',
      }),
      v('Thẻ tín dụng – dùng thông minh', 'VEO3', 'Video kiến thức dùng thẻ an toàn.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'ADVISOR: a 29-year-old Vietnamese woman, blazer.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `ADVISOR holds a credit card. ${N}`, 'Tư vấn: "Dùng thẻ tín dụng mà không mất phí lãi?"'),
          sc('4–24s', 'MẸO', 'VEO3', `ADVISOR explains. ${N}`, '"Thanh toán đủ dư nợ trước hạn, không rút tiền mặt, chi tiêu trong khả năng."'),
          sc('24–30s', 'KẾT', 'VEO3', `ADVISOR smiles. ${N}`, '"Lưu lại nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '3 nguyên tắc.',
        cta: '"Theo dõi để học thêm."',
      }),
      v('Bảo hiểm du lịch', 'Kling, VEO3', 'Video bảo hiểm cho chuyến đi.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'TRAVELER: a 30-year-old Vietnamese woman at an airport.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'TRAVELER at an airport sees "Flight delayed" on the board.'),
          sc('5–14s', 'HỖ TRỢ', 'Kling', 'TRAVELER opens an insurance app and files a claim.'),
          sc('14–20s', 'KẾT', 'VEO3', `TRAVELER relaxed at a café. ${N}`, 'Du khách: "May có bảo hiểm du lịch."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Quyền lợi (đúng điều khoản).',
        cta: '"Mua bảo hiểm du lịch online."',
      }),
      v('Ngày đầu tư vấn viên bảo hiểm', 'VEO3', 'Video tuyển dụng tư vấn viên.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'ADVISOR: a 27-year-old Vietnamese man, white shirt, tie.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `ADVISOR in an office. ${N}`, 'Tư vấn viên: "Mình chọn nghề tư vấn để giúp các gia đình an tâm."'),
          sc('5–18s', 'CÔNG VIỆC', 'VEO3', `ADVISOR meets a family at a café, explaining with a tablet. ${N}`),
          sc('18–25s', 'KẾT', 'VEO3', `ADVISOR smiles. ${N}`, '"Bạn muốn cùng đồng hành? Ứng tuyển ngay."'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: 'Quyền lợi · đào tạo.',
        cta: '"Đăng ký tham gia đội ngũ."',
      }),
      v('Phân biệt app tài chính thật – giả', 'VEO3', 'Video cảnh báo app vay giả mạo.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'EXPERT: a 35-year-old Vietnamese female security expert.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `EXPERT holds two phones. ${N}`, 'Chuyên gia: "App vay tiền giả – nhận biết thế nào?"'),
          sc('4–24s', 'DẤU HIỆU', 'VEO3', `EXPERT explains. ${N}`, '"Đòi phí trước khi giải ngân, đòi quyền truy cập danh bạ, không có thông tin công ty rõ ràng."'),
          sc('24–30s', 'KẾT', 'VEO3', `EXPERT nods. ${N}`, '"Chỉ dùng app chính thức, chia sẻ cho người thân nhé."'),
        ],
        audio: 'nhạc hồi hộp nhẹ.',
        text: '3 dấu hiệu lừa đảo.',
        cta: '"Chia sẻ để bảo vệ người thân."',
      }),
    ],
  },
];
