// Bổ sung kịch bản video AI (14 / ngành) – phần 6.
const { sc, v, NO_TEXT: N } = require('./format');

module.exports = [
  {
    name: 'Tuyển dụng & Doanh nghiệp',
    prompts: [
      v('Tuyển thực tập sinh', 'VEO3, Kling', 'Video tuyển intern trẻ trung.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'INTERN: a 21-year-old Vietnamese female student, ponytail, company T-shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `INTERN at a desk, waves. ${N}`, 'Thực tập sinh: "3 tháng thực tập ở đây, mình học được nhiều hơn 3 năm đại học!"'),
          sc('4–14s', 'TRẢI NGHIỆM', 'Kling', 'INTERN in meetings, presenting ideas, mentor giving feedback.'),
          sc('14–20s', 'KẾT', 'VEO3', `INTERN smiles. ${N}`, '"Đợt tuyển mới đang mở!"'),
        ],
        audio: 'nhạc trẻ trung.',
        text: 'Vị trí · hạn nộp · phụ cấp.',
        cta: '"Nộp CV qua [link]."',
      }),
      v('CEO chia sẻ tầm nhìn', 'VEO3', 'Video lãnh đạo nói về sứ mệnh công ty.', {
        info: '40 giây · ngang 16:9 · VEO3',
        character: 'CEO: a 48-year-old Vietnamese woman, short hair, navy suit, warm confident.',
        scenes: [
          sc('0–8s', 'HOOK', 'VEO3', `CEO in a bright office with plants. ${N}`, 'CEO: "Chúng tôi bắt đầu từ một câu hỏi: làm sao để…"'),
          sc('8–30s', 'TẦM NHÌN', 'VEO3', `CEO speaks calmly, medium close-up. ${N}`, '"…mỗi sản phẩm làm ra giúp cuộc sống của khách hàng tốt hơn. Đó là lý do chúng tôi tồn tại."'),
          sc('30–40s', 'KẾT', 'VEO3', `CEO smiles. ${N}`, '"Cảm ơn bạn đã đồng hành."'),
        ],
        audio: 'piano nhẹ.',
        text: 'Sứ mệnh · tầm nhìn.',
        cta: '"Tìm hiểu thêm về chúng tôi."',
      }),
      v('Phỏng vấn nhân viên lâu năm', 'VEO3', 'Testimonial nhân viên – employer branding.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'STAFF: a 38-year-old Vietnamese man, warehouse supervisor uniform.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `STAFF in a warehouse. ${N}`, 'Nhân viên: "10 năm, tôi chưa từng nghĩ sẽ nghỉ việc ở đây."'),
          sc('5–24s', 'CÂU CHUYỆN', 'VEO3', `STAFF talks with emotion. ${N}`, '"Từ công nhân lên trưởng kho, công ty luôn đào tạo và tin tưởng mình."'),
          sc('24–30s', 'KẾT', 'VEO3', `STAFF smiles. ${N}`, '"Đây như ngôi nhà thứ hai."'),
        ],
        audio: 'nhạc ấm.',
        text: 'Năm gắn bó · vị trí.',
        cta: '"Gia nhập đội ngũ."',
      }),
      v('Phúc lợi nhân viên', 'Kling', 'Video nhanh các phúc lợi nổi bật.', {
        info: '15 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Employees enjoy free lunch in a bright canteen.'),
          sc('5–11s', 'PHÚC LỢI', 'Kling', 'Gym corner, birthday party, company trip bus.'),
          sc('11–15s', 'KẾT', 'Kling', 'Team waving at the camera.'),
        ],
        audio: 'nhạc vui.',
        text: 'Danh sách phúc lợi (đúng thực tế).',
        cta: '"Xem vị trí đang tuyển."',
      }),
      v('Nhà máy – năng lực sản xuất', 'Kling', 'Video năng lực cho đối tác.', {
        info: '30 giây · ngang 16:9 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Drone over a large factory with solar panels.'),
          sc('6–22s', 'SẢN XUẤT', 'Kling', 'Automated production lines, robots, quality inspection lab.'),
          sc('22–30s', 'KẾT', 'Kling', 'Trucks departing with products, sunrise.'),
        ],
        audio: 'nhạc doanh nghiệp.',
        text: 'Công suất · chứng nhận (đúng thực tế).',
        cta: '"Liên hệ hợp tác sản xuất."',
      }),
      v('Hướng dẫn ứng tuyển', 'VEO3', 'Video HR hướng dẫn quy trình tuyển dụng.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'HR: a 30-year-old Vietnamese female HR manager, white blouse.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `HR at a desk. ${N}`, 'HR: "Ứng tuyển ở công ty mình gồm 3 bước thôi!"'),
          sc('4–20s', 'CÁC BƯỚC', 'VEO3', `HR counts on fingers. ${N}`, '"Nộp CV online, phỏng vấn với quản lý, nhận kết quả trong 5 ngày."'),
          sc('20–25s', 'KẾT', 'VEO3', `HR smiles. ${N}`, '"Chờ CV của bạn nhé!"'),
        ],
        audio: 'nhạc nhẹ.',
        text: '3 bước.',
        cta: '"Nộp CV ngay."',
      }),
      v('Hoạt động CSR – thiện nguyện', 'Kling', 'Video trách nhiệm xã hội.', {
        info: '25 giây · dọc 9:16 · Kling',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Employees in company T-shirts carry boxes of books to a rural school.'),
          sc('6–18s', 'HOẠT ĐỘNG', 'Kling', 'Children receive books and bicycles, smiling; employees plant trees.'),
          sc('18–25s', 'KẾT', 'Kling', 'Group photo with children.'),
        ],
        audio: 'nhạc ấm áp.',
        text: 'Chương trình · địa điểm.',
        cta: '"Cùng lan tỏa yêu thương."',
      }),
      v('Ra mắt văn phòng mới', 'Kling, VEO3', 'Video tour văn phòng mới.', {
        info: '25 giây · dọc 9:16 · Kling + VEO3',
        character: 'MANAGER: a 35-year-old Vietnamese man, smart casual.',
        scenes: [
          sc('0–6s', 'HOOK', 'Kling', 'Doors open to a modern new office with plants and glass rooms.'),
          sc('6–16s', 'TOUR', 'Kling', 'Meeting rooms, pantry, game corner, focus pods.'),
          sc('16–25s', 'KẾT', 'VEO3', `MANAGER faces the camera. ${N}`, 'Quản lý: "Không gian mới, sẵn sàng cho chặng đường mới!"'),
        ],
        audio: 'nhạc vui.',
        text: 'Địa chỉ mới.',
        cta: '"Ghé thăm chúng tôi."',
      }),
      v('Đào tạo nội bộ', 'Kling, VEO3', 'Video văn hóa học tập.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'TRAINER: a 40-year-old Vietnamese female trainer, blazer.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Employees in a workshop with sticky notes on a wall.'),
          sc('5–14s', 'HỌC', 'Kling', 'Group discussions, role-play, certificates handed out.'),
          sc('14–20s', 'KẾT', 'VEO3', `TRAINER faces the camera. ${N}`, 'Giảng viên: "Mỗi năm, mỗi người có ít nhất 40 giờ đào tạo."'),
        ],
        audio: 'nhạc truyền cảm hứng.',
        text: 'Chương trình đào tạo (đúng thực tế).',
        cta: '"Phát triển cùng chúng tôi."',
      }),
      v('Chúc mừng năm mới từ doanh nghiệp', 'Kling, VEO3', 'Video chúc Tết khách hàng / đối tác.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'Peach blossoms and red lanterns at the company entrance.'),
          sc('5–14s', 'LỜI CHÚC', 'VEO3', `The whole team in áo dài and suits waves in the lobby. ${N}`, 'Cả đội: "Chúc mừng năm mới – an khang thịnh vượng!"'),
          sc('14–20s', 'KẾT', 'Kling', 'Fireworks with company logo glow.'),
        ],
        audio: 'nhạc Tết.',
        text: 'Lời chúc · năm mới.',
        cta: '"Cảm ơn quý khách hàng."',
      }),
      v('Một ngày của nhân viên bán hàng', 'Kling, VEO3', 'Day-in-the-life cho vị trí sales.', {
        info: '30 giây · dọc 9:16 · Kling + VEO3',
        character: 'SALES: a 26-year-old Vietnamese man, white shirt, lanyard.',
        scenes: [
          sc('0–6s', 'SÁNG', 'Kling', 'SALES joins a morning huddle, team cheering.'),
          sc('6–18s', 'LÀM VIỆC', 'Kling', 'SALES meets clients, demos a product, signs a contract.'),
          sc('18–30s', 'TỐI', 'VEO3', `SALES celebrates with the team, faces the camera. ${N}`, 'Nhân viên: "Thu nhập theo năng lực, không giới hạn!"'),
        ],
        audio: 'nhạc năng động.',
        text: 'Mức thu nhập (đúng thực tế).',
        cta: '"Ứng tuyển vị trí sales."',
      }),
      v('Đối tác nói về chúng tôi', 'VEO3', 'Testimonial đối tác B2B.', {
        info: '25 giây · ngang 16:9 · VEO3',
        character: 'PARTNER: a 45-year-old Vietnamese businessman, grey suit.',
        scenes: [
          sc('0–5s', 'HOOK', 'VEO3', `PARTNER in his office. ${N}`, 'Đối tác: "5 năm hợp tác, chưa một lần trễ hẹn giao hàng."'),
          sc('5–20s', 'CHIA SẺ', 'VEO3', `PARTNER talks with sincerity. ${N}`, '"Chất lượng ổn định và đội ngũ hỗ trợ rất nhanh."'),
          sc('20–25s', 'KẾT', 'VEO3', `PARTNER smiles. ${N}`),
        ],
        audio: 'nhạc doanh nghiệp.',
        text: 'Tên đối tác (đã đồng ý).',
        cta: '"Liên hệ hợp tác."',
      }),
      v('Kỷ niệm thành lập công ty', 'Kling', 'Video hành trình các cột mốc.', {
        info: '40 giây · ngang 16:9 · Kling',
        scenes: [
          sc('0–8s', 'KHỞI ĐẦU', 'Kling', 'Old-style footage of a tiny office with 3 people, film grain.'),
          sc('8–28s', 'CỘT MỐC', 'Kling', 'Timeline montage: first product, new factory, expanding team, awards.'),
          sc('28–40s', 'HIỆN TẠI', 'Kling', 'Hundreds of employees gather for a group photo, confetti.'),
        ],
        audio: 'nhạc hùng tráng.',
        text: 'Các năm cột mốc.',
        cta: '"Cảm ơn [số] năm đồng hành."',
      }),
      v('Tuyển dụng gấp – nhiều vị trí', 'VEO3', 'Talking head ngắn thông báo tuyển gấp.', {
        info: '15 giây · dọc 9:16 · VEO3',
        character: 'HR: a 28-year-old Vietnamese woman, bright blazer, energetic.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `HR points at the camera. ${N}`, 'HR: "Tuyển gấp 10 vị trí, đi làm ngay!"'),
          sc('4–15s', 'VỊ TRÍ', 'VEO3', `HR counts. ${N}`, '"Bán hàng, kho vận, chăm sóc khách hàng – lương thỏa thuận, có đào tạo."'),
        ],
        audio: 'nhạc sôi động.',
        text: 'Danh sách vị trí · địa điểm.',
        cta: '"Inbox hoặc gọi [số]."',
      }),
    ],
  },

  {
    name: 'Dịch vụ pháp lý',
    prompts: [
      v('Đăng ký nhãn hiệu – vì sao cần?', 'VEO3', 'Video kiến thức sở hữu trí tuệ.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 36-year-old Vietnamese male lawyer, navy suit.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER in an office. ${N}`, 'Luật sư: "Thương hiệu bị người khác đăng ký trước – chuyện không hiếm!"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `LAWYER explains. ${N}`, '"Đăng ký nhãn hiệu giúp bạn được pháp luật bảo vệ quyền sử dụng tên và logo."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Tra cứu và đăng ký sớm nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Nhận tư vấn đăng ký nhãn hiệu."',
      }),
      v('Thủ tục sang tên sổ đỏ', 'VEO3', 'Video kiến thức nhà đất.', {
        info: '35 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 40-year-old Vietnamese female lawyer, white blouse, glasses.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER holds documents. ${N}`, 'Luật sư: "Mua đất xong, sang tên thế nào?"'),
          sc('4–28s', 'CÁC BƯỚC', 'VEO3', `LAWYER explains step by step. ${N}`, '"Công chứng hợp đồng, kê khai thuế phí, nộp hồ sơ tại cơ quan đăng ký đất đai, nhận sổ."'),
          sc('28–35s', 'KẾT', 'VEO3', `LAWYER smiles. ${N}`, '"Kiểm tra quy định hiện hành tại địa phương."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Các bước · "Thông tin tham khảo".',
        cta: '"Nhận hỗ trợ thủ tục."',
      }),
      v('Ly hôn thuận tình – quy trình', 'VEO3', 'Video kiến thức hôn nhân gia đình, giọng nhẹ nhàng.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 45-year-old Vietnamese female lawyer, calm, grey blazer.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER in a quiet office. ${N}`, 'Luật sư: "Thuận tình ly hôn cần chuẩn bị gì?"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `LAWYER explains gently. ${N}`, '"Đơn yêu cầu, giấy đăng ký kết hôn, thỏa thuận về con chung và tài sản."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Mỗi trường hợp khác nhau – hãy tham vấn luật sư."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Tư vấn bảo mật – liên hệ."',
      }),
      v('Hợp đồng lao động – quyền lợi', 'VEO3', 'Video quyền lợi người lao động.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 33-year-old Vietnamese man, light blue shirt.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER faces the camera. ${N}`, 'Luật sư: "Đi làm mà không ký hợp đồng – có sao không?"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `LAWYER explains. ${N}`, '"Hợp đồng giúp bảo vệ quyền lợi về lương, bảo hiểm, thời giờ làm việc. Hãy yêu cầu ký bằng văn bản."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER smiles. ${N}`, '"Có thắc mắc, comment nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Theo dõi để biết quyền lợi của bạn."',
      }),
      v('Tranh chấp hợp đồng mua bán', 'VEO3', 'Tình huống minh họa + phân tích.', {
        info: '35 giây · dọc 9:16 · VEO3',
        character: 'BUYER: a 30-year-old Vietnamese man. SELLER: a 40-year-old shop owner. LAWYER: a 38-year-old female lawyer.',
        scenes: [
          sc('0–10s', 'TÌNH HUỐNG', 'VEO3', `BUYER argues with SELLER over a defective machine in a shop. ${N}`, 'Người mua: "Máy hỏng sau 3 ngày!" – Người bán: "Hết bảo hành rồi!"'),
          sc('10–28s', 'PHÂN TÍCH', 'VEO3', `LAWYER explains in an office. ${N}`, '"Hãy xem lại thỏa thuận bảo hành, hóa đơn và tin nhắn trao đổi – đó là căn cứ quan trọng."'),
          sc('28–35s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Giữ đầy đủ giấy tờ khi mua bán."'),
        ],
        audio: 'nhạc hồi hộp nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Liên hệ tư vấn tranh chấp."',
      }),
      v('Di chúc – lập thế nào cho hợp lệ', 'VEO3', 'Video kiến thức thừa kế.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 50-year-old Vietnamese male lawyer, glasses, dark suit.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER at a desk. ${N}`, 'Luật sư: "Viết di chúc tay có giá trị không?"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `LAWYER explains. ${N}`, '"Di chúc cần đáp ứng điều kiện về hình thức và nội dung theo luật; công chứng giúp hạn chế tranh chấp."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Nên tham vấn luật sư khi lập di chúc."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Thông tin tham khảo".',
        cta: '"Đặt lịch tư vấn."',
      }),
      v('Thu hồi công nợ cho doanh nghiệp', 'VEO3', 'Video dịch vụ pháp lý doanh nghiệp.', {
        info: '25 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 42-year-old Vietnamese male lawyer, suit.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER in a meeting room. ${N}`, 'Luật sư: "Khách nợ tiền hàng mãi không trả?"'),
          sc('4–20s', 'GIẢI PHÁP', 'VEO3', `LAWYER explains. ${N}`, '"Thương lượng, gửi văn bản yêu cầu, và các biện pháp pháp lý phù hợp quy định."'),
          sc('20–25s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Liên hệ để được đánh giá hồ sơ."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Dịch vụ thu hồi nợ hợp pháp.',
        cta: '"Nhận tư vấn."',
      }),
      v('Giấy phép kinh doanh online', 'VEO3', 'Video kiến thức cho người bán online.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'CONSULTANT: a 30-year-old Vietnamese woman, cream blazer.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `CONSULTANT faces the camera. ${N}`, 'Tư vấn: "Bán hàng online cần đăng ký kinh doanh không?"'),
          sc('4–24s', 'GIẢI THÍCH', 'VEO3', `CONSULTANT explains. ${N}`, '"Tùy quy mô và hình thức, bạn có thể cần đăng ký hộ kinh doanh hoặc doanh nghiệp."'),
          sc('24–30s', 'KẾT', 'VEO3', `CONSULTANT smiles. ${N}`, '"Inbox để được hướng dẫn cụ thể."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '"Kiểm tra quy định hiện hành".',
        cta: '"Nhận hỗ trợ đăng ký."',
      }),
      v('Tư vấn pháp lý trực tuyến', 'VEO3, Kling', 'Video dịch vụ tư vấn online.', {
        info: '20 giây · dọc 9:16 · VEO3 + Kling',
        character: 'LAWYER: a 35-year-old Vietnamese female lawyer, headset.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A person at home video-calls a lawyer on a laptop.'),
          sc('5–14s', 'TƯ VẤN', 'VEO3', `LAWYER on video call, explains with documents. ${N}`, 'Luật sư: "Anh gửi giấy tờ, tôi xem và giải thích ngay."'),
          sc('14–20s', 'KẾT', 'Kling', 'The person nods relieved.'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Hình thức tư vấn · phí.',
        cta: '"Đặt lịch tư vấn online."',
      }),
      v('Văn phòng công chứng', 'Kling, VEO3', 'Video giới thiệu dịch vụ công chứng.', {
        info: '20 giây · dọc 9:16 · Kling + VEO3',
        character: 'NOTARY: a 45-year-old Vietnamese man, suit.',
        scenes: [
          sc('0–5s', 'HOOK', 'Kling', 'A tidy notary office with a reception counter.'),
          sc('5–14s', 'DỊCH VỤ', 'Kling', 'Clients sign documents, stamps applied.'),
          sc('14–20s', 'KẾT', 'VEO3', `NOTARY faces the camera. ${N}`, 'Công chứng viên: "Làm việc cả thứ Bảy, hỗ trợ công chứng ngoài trụ sở."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Giờ làm việc · địa chỉ.',
        cta: '"Đặt lịch công chứng."',
      }),
      v('Luật giao thông mới – điều cần biết', 'VEO3', 'Video kiến thức phổ thông, tăng chia sẻ.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 34-year-old Vietnamese male lawyer, standing at a street corner.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER at an intersection. ${N}`, 'Luật sư: "3 lỗi giao thông nhiều người hay mắc!"'),
          sc('4–24s', 'NỘI DUNG', 'VEO3', `LAWYER points at traffic lights and helmets. ${N}`, '"Vượt đèn vàng, dùng điện thoại khi lái xe, không đội mũ bảo hiểm đúng cách."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER nods. ${N}`, '"Mức phạt cụ thể, xem quy định hiện hành nhé."'),
        ],
        audio: 'tiếng phố, nhạc nhẹ.',
        text: '"Kiểm tra mức phạt theo quy định mới nhất".',
        cta: '"Chia sẻ để cùng an toàn."',
      }),
      v('Hợp đồng thuê nhà – điều khoản cần có', 'VEO3', 'Video kiến thức cho người thuê / cho thuê.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 37-year-old Vietnamese female lawyer, black blazer.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `LAWYER holds a contract. ${N}`, 'Luật sư: "Hợp đồng thuê nhà phải có 4 điều khoản này!"'),
          sc('4–24s', 'ĐIỀU KHOẢN', 'VEO3', `LAWYER points at the contract. ${N}`, '"Giá thuê, tiền cọc, thời hạn, và điều kiện chấm dứt trước hạn."'),
          sc('24–30s', 'KẾT', 'VEO3', `LAWYER smiles. ${N}`, '"Cần rà soát hợp đồng, inbox nhé."'),
        ],
        audio: 'nhạc nhẹ.',
        text: '4 điều khoản.',
        cta: '"Dịch vụ rà soát hợp đồng."',
      }),
      v('Khởi nghiệp – chọn loại hình doanh nghiệp', 'VEO3', 'Video kiến thức cho người mới kinh doanh.', {
        info: '35 giây · dọc 9:16 · VEO3',
        character: 'CONSULTANT: a 32-year-old Vietnamese man, smart casual.',
        scenes: [
          sc('0–4s', 'HOOK', 'VEO3', `CONSULTANT in a co-working space. ${N}`, 'Tư vấn: "Hộ kinh doanh hay công ty TNHH?"'),
          sc('4–28s', 'SO SÁNH', 'VEO3', `CONSULTANT explains with hand gestures. ${N}`, '"Hộ kinh doanh đơn giản, phù hợp quy mô nhỏ; công ty TNHH giới hạn trách nhiệm, dễ mở rộng và gọi vốn."'),
          sc('28–35s', 'KẾT', 'VEO3', `CONSULTANT smiles. ${N}`, '"Inbox để chọn mô hình phù hợp."'),
        ],
        audio: 'nhạc nhẹ.',
        text: 'Bảng so sánh ngắn · "Thông tin tham khảo".',
        cta: '"Nhận tư vấn thành lập."',
      }),
      v('Giải đáp pháp luật cho người cao tuổi', 'VEO3', 'Video ấm áp, dễ hiểu cho người lớn tuổi.', {
        info: '30 giây · dọc 9:16 · VEO3',
        character: 'LAWYER: a 40-year-old Vietnamese female lawyer, warm. ELDER: a 70-year-old Vietnamese man.',
        scenes: [
          sc('0–6s', 'HOOK', 'VEO3', `ELDER asks LAWYER at a community center. ${N}`, 'Cụ ông: "Tôi muốn cho con mảnh đất, làm sao cho đúng?"'),
          sc('6–24s', 'GIẢI ĐÁP', 'VEO3', `LAWYER explains patiently. ${N}`, 'Luật sư: "Bác có thể làm hợp đồng tặng cho, công chứng và đăng ký sang tên."'),
          sc('24–30s', 'KẾT', 'VEO3', `ELDER nods and smiles. ${N}`, '"Cảm ơn cô."'),
        ],
        audio: 'nhạc ấm.',
        text: '"Thông tin tham khảo".',
        cta: '"Tư vấn miễn phí cho người cao tuổi."',
      }),
    ],
  },
];
