// Prompt tạo video AI theo ngành – phần 2.
const { script, director } = require('./format');

const NO_TEXT = 'No subtitles, no text on screen.';

module.exports = [
  {
    name: 'Nội thất & Xây dựng', color: '#B45309', from: [],
    prompts: [
      {
        title: 'Prompt đạo diễn: video nội thất, thiết kế, xây dựng',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video giới thiệu công trình, phong cách nội thất, dịch vụ thi công.',
        content: director({
          role: 'đạo diễn video kiến trúc – nội thất',
          product: '[dịch vụ: thiết kế / thi công / đồ nội thất; phong cách; công trình tiêu biểu; khu vực phục vụ]',
          audience: '[ví dụ: gia đình trẻ mới nhận nhà, chủ quán cần thiết kế không gian]',
          goals: 'khách thấy được tay nghề, tin tưởng và đặt lịch tư vấn',
          styles: '[biến hình trước–sau / walkthrough công trình / timelapse thi công / KTS tư vấn]',
          notes: 'cảnh phối cảnh AI phải ghi "hình ảnh minh họa"; công trình thật dùng ảnh / video thật làm tham chiếu.',
        }),
      },
      {
        title: 'Biến hình phòng trống → hoàn thiện',
        tool: 'Kling',
        description: 'Từ phòng bê tông thô thành không gian sống hoàn chỉnh trong vài giây.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling (start frame + end frame)',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: '[Ảnh phòng thô thật] An empty raw concrete room with bare walls and a window, dusty, flat light. Static wide shot.' },
            { time: '3–11s', label: 'BIẾN HÌNH', prompt: 'Start frame: empty concrete room. End frame: finished [phong cách: Japandi] living room. Wooden flooring rolls out, walls turn warm white, a sofa, rug, plants and pendant lights appear one by one, sunlight warms the room. Smooth satisfying transformation, static camera.' },
            { time: '11–15s', label: 'HOÀN THIỆN', prompt: 'Slow gimbal push into the finished living room, warm afternoon light, cozy details: linen cushions, oak table, ceramic vase.' },
          ],
          audio: 'nhạc lo-fi / piano nhẹ; SFX: whoosh, "click" khi đồ xuất hiện.',
          text: '"Từ phòng thô…" → "…đến tổ ấm" · diện tích · thời gian thi công.',
          cta: '"Nhận phối cảnh 3D miễn phí – nhắn tin ngay."',
        }),
      },
      {
        title: 'Timelapse thi công công trình',
        tool: 'Kling, VEO3',
        description: 'Thể hiện quy trình chuyên nghiệp, đúng tiến độ – tăng niềm tin.',
        content: script({
          info: '25 giây · dọc 9:16 · Kling + VEO3',
          character: 'ENGINEER: a 38-year-old Vietnamese construction engineer, white safety helmet, orange vest, holding a tablet.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'Timelapse of a townhouse construction site: foundation to frame to finished facade, clouds racing, day to night, static wide shot.' },
            { time: '5–12s', label: 'QUY TRÌNH', tool: 'Kling', prompt: 'Close-up sequence: workers tying steel rebar, pouring concrete, laying bricks, all wearing helmets and safety gear. Handheld, documentary.' },
            { time: '12–20s', label: 'KỸ SƯ', tool: 'VEO3', prompt: `ENGINEER stands in front of the finished house, checks his tablet and speaks to the camera. Daylight. ${NO_TEXT}`, voice: 'Kỹ sư: "Cam kết đúng tiến độ, báo cáo hình ảnh cho chủ nhà mỗi ngày."' },
            { time: '20–25s', label: 'BÀN GIAO', tool: 'Kling', prompt: 'A happy Vietnamese family receives house keys at the gate of the new house, shaking hands, golden light.' },
          ],
          audio: 'nhạc mạnh mẽ truyền cảm hứng; SFX: máy trộn bê tông, búa.',
          text: '"Xây trọn gói" · số năm kinh nghiệm · số công trình (đúng thực tế).',
          cta: '"Nhận báo giá xây nhà trọn gói – gọi [số điện thoại]."',
        }),
      },
      {
        title: 'Giới thiệu sofa / đồ nội thất',
        tool: 'Kling, VEO3',
        description: 'Video sản phẩm nội thất nhấn chất liệu, độ êm và cảm giác sử dụng.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling (sản phẩm từ ảnh thật)',
          character: 'USER: a 28-year-old Vietnamese woman in comfy loungewear, long hair.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: 'Extreme close-up: a hand presses into a soft boucle fabric cushion, it slowly springs back. Warm light, macro.' },
            { time: '4–10s', label: 'SẢN PHẨM', prompt: '[Dùng ảnh sofa thật] Slow orbit around the sofa in a bright minimalist living room, soft daylight. Keep the sofa shape, color and fabric exactly the same as the input image.' },
            { time: '10–16s', label: 'TRẢI NGHIỆM', prompt: 'USER drops onto the sofa with a book and a cup of tea, sinks in comfortably and smiles. Medium shot, cozy.' },
            { time: '16–20s', label: 'KẾT', prompt: 'Top-down shot of the sofa with cushions and a throw blanket, camera slowly rises.' },
          ],
          audio: 'nhạc thư giãn; SFX: tiếng đệm lún nhẹ.',
          text: 'Chất liệu · kích thước · bảo hành · giá.',
          cta: '"Ghé showroom ngồi thử hoặc đặt online – giao lắp miễn phí [khu vực]."',
        }),
      },
      {
        title: 'Kiến trúc sư tư vấn 3 lỗi thiết kế',
        tool: 'VEO3',
        description: 'Video kiến thức xây thương hiệu chuyên gia cho công ty thiết kế.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3',
          character: 'ARCHITECT: a 34-year-old Vietnamese female architect, black-framed glasses, short hair, beige blazer, holding a rolled blueprint.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `ARCHITECT stands in an unfinished apartment, points at the camera. Medium shot, daylight. ${NO_TEXT}`, voice: 'KTS: "3 lỗi khiến nhà nhỏ trông chật hơn – số 3 ai cũng mắc!"' },
            { time: '4–12s', label: 'LỖI 1', prompt: `ARCHITECT gestures at a dark corner of a room. ${NO_TEXT}`, voice: '"Một: dùng quá nhiều màu tối – hãy chọn tông sáng để mở rộng không gian."' },
            { time: '12–20s', label: 'LỖI 2', prompt: `ARCHITECT touches a bulky wardrobe. ${NO_TEXT}`, voice: '"Hai: đồ nội thất quá to – ưu tiên đồ có chân, gọn và đa năng."' },
            { time: '20–30s', label: 'LỖI 3 + CTA', prompt: `ARCHITECT opens curtains, sunlight floods in, she smiles at the camera. ${NO_TEXT}`, voice: '"Ba: che hết ánh sáng tự nhiên. Muốn tụi mình xem giúp nhà bạn? Comment nhé!"' },
          ],
          audio: 'nhạc nhẹ; SFX: "ding" mỗi lỗi.',
          text: 'Lỗi 1 · Lỗi 2 · Lỗi 3.',
          cta: '"Gửi mặt bằng nhà bạn để được tư vấn miễn phí."',
        }),
      },
      {
        title: '3 phong cách nội thất cho cùng 1 phòng',
        tool: 'Kling, Midjourney',
        description: 'So sánh phong cách giúp khách chọn hướng thiết kế.',
        content: script({
          info: '20 giây · dọc 9:16 · tạo 3 ảnh phối cảnh (Midjourney) → Kling chuyển động',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: 'The same empty bedroom with a large window, neutral light, static wide shot.', voice: 'Lời kể: "Cùng một căn phòng – bạn chọn phong cách nào?"' },
            { time: '3–9s', label: 'JAPANDI', prompt: 'Japandi bedroom: low oak bed, linen bedding, paper lamp, bonsai, warm neutral tones. Slow push in, soft daylight.' },
            { time: '9–15s', label: 'INDOCHINE', prompt: 'Indochine bedroom: dark wood, rattan headboard, patterned encaustic tiles, green plants, warm lantern light. Slow push in.' },
            { time: '15–20s', label: 'HIỆN ĐẠI', prompt: 'Modern minimalist bedroom: white walls, grey upholstered bed, black metal accents, LED strip lighting. Slow push in.' },
          ],
          audio: 'nhạc nhẹ; SFX: whoosh khi chuyển phong cách.',
          text: '1. Japandi · 2. Indochine · 3. Hiện đại · "Hình ảnh minh họa".',
          cta: '"Comment 1–2–3 phong cách bạn thích, tụi mình gửi bảng giá thiết kế."',
        }),
      },
    ],
  },

  {
    name: 'Giáo dục & Đào tạo', color: '#4F46E5', from: ['Giáo dục'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video giáo dục, trung tâm đào tạo',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video tuyển sinh, video kiến thức ngắn, câu chuyện học viên.',
        content: director({
          role: 'đạo diễn video giáo dục và tuyển sinh',
          product: '[trung tâm / khóa học, môn học, lứa tuổi, điểm khác biệt, học phí, ưu đãi]',
          audience: '[ví dụ: phụ huynh có con 6–12 tuổi / sinh viên muốn học IELTS / người đi làm]',
          goals: 'người xem hiểu giá trị khóa học và đăng ký học thử',
          styles: '[giải thích kiến thức bằng hoạt hình / câu chuyện học viên / giáo viên nói trước camera / không khí lớp học]',
          notes: 'không cam kết điểm số tuyệt đối; nếu dùng câu chuyện học viên thật cần sự đồng ý.',
        }),
      },
      {
        title: 'Quảng cáo trung tâm tiếng Anh',
        tool: 'VEO3, Kling',
        description: 'Video tuyển sinh nêu nỗi sợ nói tiếng Anh → môi trường học → kết quả.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3 + Kling',
          character: 'STUDENT: a 20-year-old Vietnamese university student, short black hair, glasses, navy hoodie. TEACHER: a friendly 28-year-old Vietnamese female teacher, ponytail, white shirt.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'VEO3', prompt: `STUDENT freezes in front of a foreign customer at a café counter, nervous, sweating. Medium shot, comedic tension. ${NO_TEXT}`, voice: 'Sinh viên (nghĩ thầm): "Biết từ vựng mà sao nói không ra…"' },
            { time: '4–12s', label: 'LỚP HỌC', tool: 'Kling', prompt: 'Bright modern classroom, small group of students role-playing conversations in pairs, TEACHER walks around encouraging them, laughter. Tracking shot.' },
            { time: '12–20s', label: 'GIÁO VIÊN', tool: 'VEO3', prompt: `TEACHER faces the camera in the classroom. ${NO_TEXT}`, voice: 'Giáo viên: "Ở đây em nói 70% thời gian, sai thì sửa ngay, không ai cười em cả."' },
            { time: '20–27s', label: 'KẾT QUẢ', tool: 'VEO3', prompt: `STUDENT confidently chats in English with a foreign customer at the same café, both laughing. ${NO_TEXT}`, voice: 'Sinh viên: "Hi! Can I get an iced latte, please?"' },
            { time: '27–30s', label: 'CTA', tool: 'Kling', prompt: 'Exterior of the language center with its sign, students walking in, bright daylight.' },
          ],
          audio: 'nhạc tươi vui truyền cảm hứng; SFX: tiếng tim đập (cảnh 1), tiếng cười.',
          text: '"Lớp tối đa [x] học viên" · "Học thử miễn phí".',
          cta: '"Đăng ký buổi học thử miễn phí – link ở bio."',
        }),
      },
      {
        title: 'Video kiến thức ngắn (hoạt hình giải thích)',
        tool: 'Kling, VEO3, ElevenLabs',
        description: 'Giải thích 1 khái niệm trong 45 giây bằng hình minh họa 3D.',
        content: script({
          info: '45 giây · dọc 9:16 · Kling (hình minh họa) + lời kể ElevenLabs',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: '3D animated illustration: a giant question mark made of glowing clouds above a small city. Pixar-like style, bright colors.', voice: 'Lời kể: "Tại sao trời lại có màu xanh? Câu trả lời nằm ở ánh nắng."' },
            { time: '5–18s', label: 'GIẢI THÍCH 1', prompt: '3D animation: a beam of white sunlight enters Earth\'s atmosphere and splits into rainbow colors, tiny glowing particles representing air molecules. Smooth camera follow.', voice: '"Ánh nắng trắng thật ra gồm đủ bảy màu. Khi đi vào bầu khí quyển, nó va vào các phân tử khí."' },
            { time: '18–32s', label: 'GIẢI THÍCH 2', prompt: '3D animation: blue light rays bounce in all directions between molecules while red rays travel straight, the sky gradually fills with blue. Clear, educational.', voice: '"Ánh sáng xanh có bước sóng ngắn nên bị tán xạ mạnh nhất – bắn ra khắp bầu trời."' },
            { time: '32–45s', label: 'TÓM TẮT', prompt: '3D animation: a child looks up at a blue sky, then the scene shifts to an orange sunset. Warm, satisfying.', voice: '"Còn lúc hoàng hôn, ánh sáng đi xa hơn nên trời chuyển cam đỏ. Thú vị đúng không?"' },
          ],
          audio: 'nhạc khám phá nhẹ; SFX: "ting", whoosh.',
          text: 'Từ khóa: "tán xạ ánh sáng" · câu hỏi cuối video.',
          cta: '"Bạn muốn giải thích hiện tượng nào tiếp theo? Comment nhé!"',
        }),
      },
      {
        title: 'Câu chuyện học viên thành công',
        tool: 'VEO3, Kling',
        description: 'Testimonial dạng kể chuyện: trước – trong – sau khi học.',
        content: script({
          info: '40 giây · dọc 9:16 · VEO3 + Kling',
          character: 'NAM: a 24-year-old Vietnamese man, short hair, casual shirt, sincere smile.',
          scenes: [
            { time: '0–6s', label: 'HOOK', tool: 'VEO3', prompt: `NAM sits in a cozy café, speaks honestly to the camera. Medium close-up, soft light. ${NO_TEXT}`, voice: 'Nam: "Một năm trước, mình bị loại ở vòng phỏng vấn vì không nói được tiếng Anh."' },
            { time: '6–16s', label: 'KHÓ KHĂN', tool: 'Kling', prompt: 'NAM sits alone at night in a small room, looking at a rejection email on his laptop, disappointed. Cool blue light, slow push in.' },
            { time: '16–28s', label: 'NỖ LỰC', tool: 'Kling', prompt: 'Montage: NAM studying in class, practicing speaking with classmates, recording himself on the phone, early mornings with notebooks. Warm, hopeful.' },
            { time: '28–40s', label: 'THÀNH QUẢ', tool: 'VEO3', prompt: `NAM in a smart shirt in a modern office, shakes hands with a foreign manager, then smiles at the camera. ${NO_TEXT}`, voice: '"Giờ mình làm ở công ty nước ngoài. Nếu mình làm được, bạn cũng làm được!"' },
          ],
          audio: 'nhạc truyền cảm hứng dâng dần.',
          text: 'Tên học viên (đã đồng ý) · khóa học đã tham gia.',
          cta: '"Bắt đầu hành trình của bạn – đăng ký tư vấn lộ trình miễn phí."',
        }),
      },
      {
        title: 'Giới thiệu khóa học online & giảng viên',
        tool: 'VEO3, HeyGen',
        description: 'Video giới thiệu khóa học trực tuyến: giảng viên, nội dung, kết quả nhận được.',
        content: script({
          info: '30 giây · dọc 9:16 hoặc ngang 16:9 · VEO3 (hoặc avatar HeyGen)',
          character: 'INSTRUCTOR: a 35-year-old Vietnamese man, neat beard, dark green shirt, sitting in a studio with warm bokeh lights.',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: `INSTRUCTOR looks into the camera. Medium shot, studio. ${NO_TEXT}`, voice: 'Giảng viên: "Bạn có thể làm video bằng AI trong 30 ngày – kể cả khi chưa biết gì."' },
            { time: '5–15s', label: 'NỘI DUNG', prompt: 'Over-the-shoulder shot of INSTRUCTOR\'s laptop showing an AI video editing interface, his hands typing prompts, video clips appearing. Modern, clean.' , voice: '"Khóa học gồm [số] bài: viết kịch bản, tạo ảnh, tạo video, lồng tiếng và dựng hoàn chỉnh."' },
            { time: '15–25s', label: 'KẾT QUẢ', prompt: 'Split-screen montage of finished AI videos playing on a phone: product ad, storytelling, educational animation.', voice: '"Học xong, bạn tự làm được video quảng cáo, kể chuyện, giáo dục."' },
            { time: '25–30s', label: 'CTA', prompt: `INSTRUCTOR smiles and gestures toward the camera. ${NO_TEXT}`, voice: '"Đăng ký ngay hôm nay, hẹn gặp bạn trong bài đầu tiên!"' },
          ],
          audio: 'nhạc công nghệ nhẹ.',
          text: 'Tên khóa học · số bài · ưu đãi.',
          cta: '"Bấm link để xem bài học thử miễn phí."',
        }),
      },
      {
        title: 'Tuyển sinh trường mầm non',
        tool: 'Kling, VEO3',
        description: 'Video ấm áp cho phụ huynh: an toàn, vui chơi, dinh dưỡng, giáo viên tận tâm.',
        content: script({
          info: '30 giây · dọc 9:16 · Kling + VEO3',
          character: 'TEACHER: a gentle 26-year-old Vietnamese female preschool teacher, pastel uniform, hair tied back. KIDS: 4–5 year old Vietnamese children in colorful uniforms.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'A small child holds a parent\'s hand at the colorful school gate, TEACHER kneels down and welcomes the child with a hug. Morning light.' },
            { time: '5–13s', label: 'VUI CHƠI', tool: 'Kling', prompt: 'KIDS play in a bright playground with soft flooring, slides and sandbox, laughing. Slow motion, warm.' },
            { time: '13–20s', label: 'HỌC TẬP', tool: 'Kling', prompt: 'KIDS painting and singing in a bright classroom with TEACHER, art on the walls. Handheld, joyful.' },
            { time: '20–27s', label: 'BỮA ĂN', tool: 'Kling', prompt: 'KIDS eat a colorful healthy lunch at small tables, TEACHER helps them. Clean, bright.' },
            { time: '27–30s', label: 'CTA', tool: 'VEO3', prompt: `TEACHER waves with the KIDS at the camera. ${NO_TEXT}`, voice: 'Cô và các bé: "Hẹn gặp bé ở trường nha!"' },
          ],
          audio: 'nhạc thiếu nhi ấm áp; SFX: trẻ em cười.',
          text: 'Tên trường · độ tuổi nhận · camera giám sát · thực đơn dinh dưỡng.',
          cta: '"Đăng ký tham quan trường và học thử 1 ngày miễn phí."',
        }),
      },
    ],
  },

  {
    name: 'Du lịch & Khách sạn', color: '#0891B2', from: ['Du lịch & Khách sạn'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video du lịch, resort, homestay',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video quảng bá điểm đến, tour, khách sạn kèm prompt từng cảnh.',
        content: director({
          role: 'đạo diễn video du lịch (travel film)',
          product: '[điểm đến / tour / resort / homestay, trải nghiệm nổi bật, giá, ưu đãi]',
          audience: '[ví dụ: cặp đôi trẻ, gia đình có con nhỏ, nhóm bạn thích khám phá]',
          goals: 'người xem muốn đi ngay và đặt phòng / tour',
          styles: '[drone điện ảnh / vlog trải nghiệm / một ngày nghỉ dưỡng / ẩm thực địa phương]',
          notes: 'cảnh nơi lưu trú nên dùng ảnh thật làm tham chiếu; không phóng đại tiện ích.',
        }),
      },
      {
        title: 'Quảng bá điểm đến (travel film)',
        tool: 'VEO3, Kling',
        description: 'Video điện ảnh khơi gợi mong muốn du lịch, nhịp dựng theo nhạc.',
        content: script({
          info: '30 giây · ngang 16:9 hoặc dọc 9:16 · VEO3 / Kling',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: 'Aerial drone flying over Ha Long Bay at sunrise, limestone islands emerging from mist, golden light. Epic cinematic.' },
            { time: '5–12s', label: 'TRẢI NGHIỆM 1', prompt: 'A cruise ship glides between islands, tourists on the deck with coffee, gentle breeze. Smooth tracking.' },
            { time: '12–19s', label: 'TRẢI NGHIỆM 2', prompt: 'Two friends kayak through a calm lagoon under a rock arch, laughing, turquoise water. Low tracking shot.' },
            { time: '19–25s', label: 'TRẢI NGHIỆM 3', prompt: 'Sunset on a beach, a couple watches from a cliff, silhouettes against an orange sky.' },
            { time: '25–30s', label: 'KẾT', prompt: 'Drone rises high revealing the whole bay at dusk, lights of boats twinkling.' },
          ],
          audio: 'nhạc điện ảnh hứng khởi; SFX: sóng, gió, tiếng mái chèo.',
          text: 'Tên điểm đến · "3N2Đ từ [giá]".',
          cta: '"Đặt tour ngay – giữ chỗ chỉ với [số tiền]."',
        }),
      },
      {
        title: 'Resort – một ngày nghỉ dưỡng',
        tool: 'Kling, VEO3',
        description: 'Từ sáng đến tối tại resort: phòng, hồ bơi, spa, ăn tối.',
        content: script({
          info: '30 giây · dọc 9:16 · Kling (ảnh resort thật) + VEO3',
          character: 'GUEST: a 29-year-old Vietnamese woman, wavy long hair, white linen dress, straw hat.',
          scenes: [
            { time: '0–5s', label: 'SÁNG', tool: 'Kling', prompt: '[Ảnh phòng thật] GUEST opens white curtains revealing an ocean view balcony, morning sun floods the room. Slow push in.' },
            { time: '5–12s', label: 'HỒ BƠI', tool: 'Kling', prompt: 'GUEST relaxes in an infinity pool overlooking the sea, sipping a coconut, palm trees swaying. Drone pulls back.' },
            { time: '12–19s', label: 'SPA', tool: 'Kling', prompt: 'GUEST receives a massage in an open-air spa pavilion surrounded by tropical plants, calm.' },
            { time: '19–26s', label: 'TỐI', tool: 'VEO3', prompt: `GUEST dines on a candlelit beach table at sunset, waiter serves seafood, she smiles at the camera. ${NO_TEXT}`, voice: 'Khách: "Đây đúng là kỳ nghỉ mình cần."' },
            { time: '26–30s', label: 'KẾT', tool: 'Kling', prompt: 'Night view of the resort with glowing lanterns and pool lights, stars above.' },
          ],
          audio: 'nhạc chill tropical; SFX: sóng, chim.',
          text: 'Tên resort · gói nghỉ dưỡng · giá ưu đãi.',
          cta: '"Đặt phòng trực tiếp nhận ưu đãi [x]%."',
        }),
      },
      {
        title: 'Vlog tour trải nghiệm',
        tool: 'VEO3',
        description: 'Người dẫn kể trải nghiệm tour như vlog cá nhân, chân thật.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3',
          character: 'GUIDE: a 27-year-old Vietnamese male travel vlogger, tanned, backwards cap, olive T-shirt, small backpack.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `Selfie vlog shot, GUIDE walks on a mountain trail in Ha Giang with rice terraces behind. Handheld. ${NO_TEXT}`, voice: 'Hướng dẫn viên: "Đây là cung đường đẹp nhất Việt Nam, và hôm nay mình dẫn các bạn đi!"' },
            { time: '4–12s', label: 'CUNG ĐƯỜNG', prompt: 'POV from a motorbike riding along the Ma Pi Leng pass, deep green valley and river below, sunny.' },
            { time: '12–20s', label: 'VĂN HÓA', prompt: 'GUIDE sits with a local H\'Mong family drinking corn wine, laughing together in a wooden house. Warm light.' },
            { time: '20–30s', label: 'KẾT', prompt: `GUIDE on a cliff at sunset, turns to the camera. ${NO_TEXT}`, voice: '"Tour 3 ngày, có người dẫn đường, an toàn tuyệt đối. Đi cùng mình nhé!"' },
          ],
          audio: 'nhạc dân tộc hiện đại; SFX: tiếng xe máy, gió núi.',
          text: 'Lịch trình 3N2Đ · giá · ngày khởi hành.',
          cta: '"Nhắn tin để giữ chỗ chuyến gần nhất."',
        }),
      },
      {
        title: 'Homestay chill',
        tool: 'Kling, VEO3',
        description: 'Giới thiệu homestay với không khí ấm cúng, góc check-in đẹp.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling (ảnh homestay thật)',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: '[Ảnh thật] Morning fog over pine hills in Da Lat seen from a wooden balcony, a cup of coffee steaming on the railing.' },
            { time: '4–10s', label: 'PHÒNG', prompt: '[Ảnh thật] Slow pan across a cozy wooden bedroom with a big window, white bedding, fairy lights, warm.' },
            { time: '10–16s', label: 'KHÔNG GIAN CHUNG', prompt: 'Friends sit around a campfire in the homestay garden at night, grilling and playing guitar, fairy lights above.' },
            { time: '16–20s', label: 'KẾT', prompt: 'Wide shot of the homestay at blue hour, warm windows glowing among pine trees.' },
          ],
          audio: 'guitar acoustic; SFX: lửa tí tách, tiếng côn trùng đêm.',
          text: 'Tên homestay · giá/đêm · "Cách trung tâm [x] km".',
          cta: '"Đặt phòng cuối tuần – inbox ngay kẻo hết phòng."',
        }),
      },
      {
        title: 'Ẩm thực địa phương',
        tool: 'Kling, VEO3',
        description: 'Video món ngon địa phương – kéo khách du lịch và quảng bá tour ẩm thực.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling + VEO3',
          character: 'FOODIE: a 25-year-old Vietnamese woman, bob haircut, yellow T-shirt, enthusiastic.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'Kling', prompt: 'Close-up of sizzling bánh xèo being flipped in a cast-iron pan over charcoal, bright yellow, steam rising. Macro.' },
            { time: '4–10s', label: 'MÓN 1', tool: 'VEO3', prompt: `FOODIE wraps bánh xèo in mustard leaves and dips it in sauce, takes a crunchy bite. Close-up. ${NO_TEXT}`, voice: 'Foodie: "Giòn rụm! Đúng vị miền Tây luôn!"' },
            { time: '10–16s', label: 'MÓN 2', tool: 'Kling', prompt: 'Bowls of steaming hủ tiếu at a floating market, vendor passing a bowl from a boat. Bright morning.' },
            { time: '16–20s', label: 'KẾT', tool: 'Kling', prompt: 'Top-down shot of a table full of local dishes, hands reaching in.' },
          ],
          audio: 'nhạc vui; ASMR: xèo xèo, giòn rụm.',
          text: 'Tên món · địa chỉ · giá.',
          cta: '"Lưu lại cho chuyến đi sắp tới!"',
        }),
      },
    ],
  },

  {
    name: 'Gym & Thể hình', color: '#DC2626', from: ['Gym & Thể hình'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video phòng gym, PT, yoga',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video tuyển hội viên, hướng dẫn bài tập, truyền động lực.',
        content: director({
          role: 'đạo diễn video thể thao – fitness',
          product: '[phòng tập / dịch vụ PT / lớp yoga; điểm nổi bật; ưu đãi]',
          audience: '[ví dụ: người mới tập, dân văn phòng muốn giảm mỡ, mẹ sau sinh]',
          goals: 'người xem có động lực và đăng ký tập thử',
          styles: '[TVC động lực / hướng dẫn kỹ thuật / hành trình thay đổi / không khí lớp tập]',
          notes: 'không cam kết giảm cân cụ thể; nhắc người có bệnh lý hỏi ý kiến chuyên gia.',
        }),
      },
      {
        title: 'TVC động lực tập luyện',
        tool: 'Kling, VEO3',
        description: 'Video kịch tính kiểu Nike: mồ hôi, quyết tâm, slow motion.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling',
          character: 'ATHLETE: a determined 27-year-old Vietnamese woman, high ponytail, black sports bra and leggings, toned.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: 'Extreme close-up of ATHLETE tying her shoelaces in a dark gym, breath visible, dramatic rim light.' },
            { time: '4–10s', label: 'NỖ LỰC', prompt: 'ATHLETE slams battle ropes, sweat flying in slow motion, spotlight from above, high contrast.' },
            { time: '10–16s', label: 'VƯỢT QUA', prompt: 'ATHLETE struggles on the last rep of a squat, then pushes up powerfully. Low angle, slow motion.' },
            { time: '16–20s', label: 'KẾT', prompt: 'ATHLETE stands still, breathing hard, looks straight into the camera with a confident smile.' },
          ],
          audio: 'beat mạnh, nhịp tim; SFX: thở mạnh, dây thừng đập sàn.',
          text: '"Không ai thấy bạn lúc 5 giờ sáng. Nhưng ai cũng sẽ thấy kết quả."',
          cta: '"Tập thử miễn phí 3 buổi tại [tên phòng tập]."',
        }),
      },
      {
        title: 'Hướng dẫn kỹ thuật 1 bài tập',
        tool: 'VEO3',
        description: 'PT hướng dẫn đúng kỹ thuật squat, kèm lỗi sai thường gặp.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3',
          character: 'COACH: a fit 30-year-old Vietnamese male personal trainer, short hair, black gym T-shirt with logo, friendly.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `COACH faces the camera in a bright gym. ${NO_TEXT}`, voice: 'HLV: "Squat sai cách là đau gối ngay – xem kỹ 3 điểm này!"' },
            { time: '4–12s', label: 'ĐIỂM 1', prompt: `Side view, COACH demonstrates feet shoulder-width apart, toes slightly out. ${NO_TEXT}`, voice: '"Một: chân rộng bằng vai, mũi chân hơi mở."' },
            { time: '12–20s', label: 'ĐIỂM 2', prompt: `Side view, COACH squats down slowly pushing hips back, chest up. ${NO_TEXT}`, voice: '"Hai: đẩy hông ra sau như ngồi ghế, ngực luôn mở."' },
            { time: '20–30s', label: 'ĐIỂM 3 + CTA', prompt: `Front view, COACH shows knees tracking over toes, then smiles at the camera. ${NO_TEXT}`, voice: '"Ba: đầu gối đi theo hướng mũi chân. Lưu lại để tập đúng nha!"' },
          ],
          audio: 'nhạc gym nhẹ; SFX: "ding" từng điểm.',
          text: '✔ Chân rộng bằng vai · ✔ Đẩy hông ra sau · ✔ Gối theo mũi chân.',
          cta: '"Cần PT kèm 1-1? Nhắn tin để được tư vấn."',
        }),
      },
      {
        title: 'Hành trình thay đổi 30 ngày',
        tool: 'Kling, VEO3',
        description: 'Câu chuyện hội viên thay đổi lối sống (không cam kết con số).',
        content: script({
          info: '30 giây · dọc 9:16 · Kling + VEO3',
          character: 'TUAN: a 32-year-old Vietnamese office worker, slightly overweight, short hair, grey T-shirt.',
          scenes: [
            { time: '0–5s', label: 'NGÀY 1', tool: 'VEO3', prompt: `TUAN stands in front of a mirror at home, sighs, then looks at the camera. ${NO_TEXT}`, voice: 'Tuấn: "Leo 3 tầng cầu thang là thở dốc. Hôm nay mình bắt đầu."' },
            { time: '5–18s', label: 'QUÁ TRÌNH', tool: 'Kling', prompt: 'Montage: TUAN jogging at dawn, lifting weights with a coach, preparing a healthy lunch box, drinking water, tired but smiling.' },
            { time: '18–26s', label: 'NGÀY 30', tool: 'VEO3', prompt: `TUAN runs up stairs easily, reaches the top and smiles. Energetic. ${NO_TEXT}`, voice: '"30 ngày sau: khỏe hơn, ngủ ngon hơn, tự tin hơn."' },
            { time: '26–30s', label: 'CTA', tool: 'Kling', prompt: 'TUAN high-fives his coach in the gym.' },
          ],
          audio: 'nhạc truyền cảm hứng.',
          text: 'Ngày 1 → Ngày 30 · "Kết quả mỗi người khác nhau".',
          cta: '"Bắt đầu hành trình của bạn – đăng ký thử thách 30 ngày."',
        }),
      },
      {
        title: 'Ưu đãi tuyển hội viên',
        tool: 'Kling, VEO3',
        description: 'Video ngắn khoe cơ sở vật chất + ưu đãi có thời hạn.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling + VEO3',
          character: 'RECEPTIONIST: a friendly 24-year-old Vietnamese woman, sporty polo with gym logo, ponytail.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'Kling', prompt: 'Fast FPV-style fly-through of a modern gym: rows of machines, free weights, a group class, bright LED lights.' },
            { time: '4–10s', label: 'TIỆN ÍCH', tool: 'Kling', prompt: 'Quick shots: sauna room, clean locker room, yoga studio with mirrors.' },
            { time: '10–15s', label: 'ƯU ĐÃI', tool: 'VEO3', prompt: `RECEPTIONIST at the front desk smiles at the camera. ${NO_TEXT}`, voice: 'Lễ tân: "Đăng ký tuần này giảm 40% gói 12 tháng!"' },
          ],
          audio: 'EDM sôi động.',
          text: '"Giảm 40% – đến [ngày]" · địa chỉ.',
          cta: '"Inbox để giữ ưu đãi."',
        }),
      },
      {
        title: 'Lớp yoga thư giãn',
        tool: 'Kling',
        description: 'Video nhẹ nhàng cho studio yoga / thiền.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling',
          character: 'YOGI: a calm 30-year-old Vietnamese woman, hair in a low bun, sage green yoga set.',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: 'Soft morning light enters a wooden yoga studio with plants, YOGI unrolls a mat. Slow, peaceful.' },
            { time: '5–12s', label: 'TƯ THẾ', prompt: 'YOGI flows from downward dog into warrior pose, slow graceful movement, side view.' },
            { time: '12–17s', label: 'THIỀN', prompt: 'YOGI sits cross-legged, eyes closed, breathing slowly, camera slowly orbits.' },
            { time: '17–20s', label: 'KẾT', prompt: 'Close-up of a candle flame and incense smoke in the studio.' },
          ],
          audio: 'nhạc thiền; SFX: chuông xoay, hơi thở.',
          text: 'Lịch lớp · "Lớp thử miễn phí".',
          cta: '"Đặt chỗ lớp thử miễn phí cuối tuần."',
        }),
      },
    ],
  },

  {
    name: 'Y tế & Nha khoa', color: '#0E7490', from: [],
    prompts: [
      {
        title: 'Prompt đạo diễn: video phòng khám, nha khoa (tuân thủ quy định)',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video y tế an toàn: thông tin dễ hiểu, không cam kết kết quả.',
        content: director({
          role: 'đạo diễn video truyền thông y tế',
          product: '[phòng khám / nha khoa, dịch vụ, đội ngũ bác sĩ, trang thiết bị, địa chỉ]',
          audience: '[ví dụ: người lớn 25–45 tuổi quan tâm sức khỏe răng miệng]',
          goals: 'tạo niềm tin và đặt lịch thăm khám',
          styles: '[giới thiệu phòng khám / kiến thức sức khỏe hoạt hình / bác sĩ giải đáp / hành trình khách hàng]',
          notes: 'không cam kết khỏi bệnh / kết quả tuyệt đối; không chẩn đoán qua video; khuyến khích thăm khám trực tiếp; tuân thủ quy định quảng cáo dịch vụ y tế.',
        }),
      },
      {
        title: 'Giới thiệu phòng khám nha khoa',
        tool: 'Kling, VEO3',
        description: 'Không gian sạch, thiết bị hiện đại, bác sĩ thân thiện.',
        content: script({
          info: '25 giây · dọc 9:16 · Kling (ảnh phòng khám thật) + VEO3',
          character: 'DENTIST: a 38-year-old Vietnamese female dentist, white coat, surgical cap, warm smile.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: '[Ảnh thật] Smooth glide through a bright, spotless dental clinic lobby with plants and comfortable chairs.' },
            { time: '5–12s', label: 'THIẾT BỊ', tool: 'Kling', prompt: '[Ảnh thật] Slow pan across a modern dental treatment room, sterilized tools, digital X-ray screen.' },
            { time: '12–20s', label: 'BÁC SĨ', tool: 'VEO3', prompt: `DENTIST sits beside a patient chair, speaks kindly to the camera. ${NO_TEXT}`, voice: 'Bác sĩ: "Ở đây, mỗi ca điều trị đều được thăm khám và giải thích kỹ trước khi làm."' },
            { time: '20–25s', label: 'KẾT', tool: 'Kling', prompt: 'A relaxed patient smiles in the dental chair, DENTIST gives a thumbs up. Bright clean light.' },
          ],
          audio: 'nhạc nhẹ nhàng tích cực.',
          text: 'Tên phòng khám · giờ làm việc · địa chỉ · số giấy phép hoạt động.',
          cta: '"Đặt lịch khám và tư vấn – nhắn tin cho phòng khám."',
        }),
      },
      {
        title: 'Kiến thức sức khỏe (hoạt hình 3D)',
        tool: 'Kling, ElevenLabs',
        description: 'Giải thích 1 vấn đề sức khỏe phổ biến bằng hình minh họa dễ hiểu.',
        content: script({
          info: '40 giây · dọc 9:16 · Kling (hình 3D) + lời kể',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: '3D animation: a cute cartoon tooth character looks worried, a tiny cavity appears. Bright Pixar-like style.', voice: 'Lời kể: "Vì sao chải răng mỗi ngày vẫn bị sâu răng?"' },
            { time: '5–18s', label: 'NGUYÊN NHÂN', prompt: '3D animation: tiny bacteria characters gather in the gaps between teeth after eating sweets, forming plaque. Educational, clear.', voice: '"Mảng bám ở kẽ răng – nơi bàn chải khó chạm tới – là nơi vi khuẩn phát triển."' },
            { time: '18–32s', label: 'CÁCH PHÒNG', prompt: '3D animation: dental floss slides between teeth sweeping away bacteria, then a toothbrush brushing at a 45-degree angle.', voice: '"Hãy dùng chỉ nha khoa, chải răng đúng góc 45 độ, và khám răng định kỳ 6 tháng."' },
            { time: '32–40s', label: 'KẾT', prompt: '3D animation: the tooth character is shiny and happy, giving a thumbs up.', voice: '"Nếu răng ê buốt, hãy đến nha sĩ để được thăm khám."' },
          ],
          audio: 'nhạc vui nhẹ; SFX: "ting".',
          text: '3 thói quen bảo vệ răng · "Thông tin tham khảo – hãy thăm khám để được tư vấn".',
          cta: '"Theo dõi để xem thêm mẹo chăm sóc răng miệng."',
        }),
      },
      {
        title: 'Bác sĩ giải đáp câu hỏi thường gặp',
        tool: 'VEO3',
        description: 'Format hỏi – đáp ngắn, xây dựng chuyên môn và niềm tin.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3',
          character: 'DOCTOR: a 45-year-old Vietnamese male doctor, white coat, stethoscope, glasses, calm and kind.',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: `DOCTOR in a bright consultation room reads a question card, then looks at the camera. ${NO_TEXT}`, voice: 'Bác sĩ: "Câu hỏi hôm nay: uống nước bao nhiêu mỗi ngày là đủ?"' },
            { time: '5–20s', label: 'GIẢI ĐÁP', prompt: `DOCTOR explains with simple hand gestures, holding a glass of water. Medium shot. ${NO_TEXT}`, voice: '"Người trưởng thành thường cần khoảng 1,5–2 lít, tùy cân nặng, thời tiết và mức vận động."' },
            { time: '20–30s', label: 'LƯU Ý + CTA', prompt: `DOCTOR smiles at the camera. ${NO_TEXT}`, voice: '"Người có bệnh tim, thận nên hỏi ý kiến bác sĩ. Bạn muốn hỏi gì tiếp, comment nhé!"' },
          ],
          audio: 'nhạc nền rất nhẹ.',
          text: 'Câu hỏi + câu trả lời ngắn · "Thông tin tham khảo".',
          cta: '"Đặt lịch khám tổng quát tại [phòng khám]."',
        }),
      },
      {
        title: 'Hành trình khách hàng niềng răng',
        tool: 'VEO3, Kling',
        description: 'Kể trải nghiệm thật của khách (đã đồng ý), tránh before-after phóng đại.',
        content: script({
          info: '35 giây · dọc 9:16 · VEO3 + Kling',
          character: 'TRANG: a 22-year-old Vietnamese woman, long black hair, cream sweater, shy then confident smile.',
          scenes: [
            { time: '0–6s', label: 'HOOK', tool: 'VEO3', prompt: `TRANG covers her mouth while laughing with friends at a café, then looks at the camera. ${NO_TEXT}`, voice: 'Trang: "Mình từng ngại cười vì răng khấp khểnh."' },
            { time: '6–16s', label: 'TƯ VẤN', tool: 'Kling', prompt: 'TRANG at a dental clinic, the dentist shows her a 3D scan of her teeth on a screen, explaining the plan.' },
            { time: '16–26s', label: 'QUÁ TRÌNH', tool: 'Kling', prompt: 'Montage: TRANG with clear aligners, follow-up visits, smiling more each month, calendar pages turning.' },
            { time: '26–35s', label: 'HIỆN TẠI', tool: 'VEO3', prompt: `TRANG laughs freely with friends, then smiles confidently at the camera. ${NO_TEXT}`, voice: '"Giờ mình tự tin cười thật tươi rồi!"' },
          ],
          audio: 'nhạc ấm áp.',
          text: '"Kết quả có thể khác nhau tùy tình trạng răng" · thời gian điều trị thực tế.',
          cta: '"Đặt lịch chụp phim và tư vấn niềng răng."',
        }),
      },
      {
        title: 'Gói khám sức khỏe tổng quát',
        tool: 'Kling, VEO3',
        description: 'Giới thiệu quy trình khám nhanh, gọn, có kết quả trong ngày.',
        content: script({
          info: '25 giây · dọc 9:16 · Kling + VEO3',
          character: 'PATIENT: a 40-year-old Vietnamese man, short hair, light blue shirt. NURSE: a Vietnamese female nurse in a light blue uniform.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'VEO3', prompt: `PATIENT at his office desk rubs his neck, tired, looks at the camera. ${NO_TEXT}`, voice: 'Bệnh nhân: "Lần cuối mình đi khám sức khỏe là… 3 năm trước."' },
            { time: '5–15s', label: 'QUY TRÌNH', tool: 'Kling', prompt: 'Quick clean shots: NURSE measures blood pressure, blood test, ultrasound room, all in a bright modern clinic.' },
            { time: '15–22s', label: 'KẾT QUẢ', tool: 'Kling', prompt: 'A doctor reviews results on a tablet with PATIENT, both nodding, reassuring.' },
            { time: '22–25s', label: 'CTA', tool: 'Kling', prompt: 'Exterior of the clinic with its sign, people walking in.' },
          ],
          audio: 'nhạc nhẹ tích cực.',
          text: 'Gói khám · số hạng mục · giá · "Có kết quả trong ngày" (đúng thực tế).',
          cta: '"Đặt lịch khám sức khỏe định kỳ."',
        }),
      },
    ],
  },

  {
    name: 'Ô tô & Xe máy', color: '#475569', from: ['Ô tô & Xe máy'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video ô tô, xe máy, garage',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video giới thiệu xe, showroom, dịch vụ bảo dưỡng.',
        content: director({
          role: 'đạo diễn quảng cáo ô tô – xe máy',
          product: '[mẫu xe / showroom / garage, tính năng nổi bật, giá, ưu đãi]',
          audience: '[ví dụ: gia đình trẻ mua xe đầu tiên / người đi làm cần xe máy điện]',
          goals: 'khách quan tâm và đặt lịch lái thử / bảo dưỡng',
          styles: '[TVC lái xe điện ảnh / showroom giới thiệu tính năng / review lái thử / dịch vụ garage]',
          notes: 'dùng ảnh xe thật làm khung đầu để giữ đúng thiết kế; thông số kỹ thuật phải đúng với hãng.',
        }),
      },
      {
        title: 'TVC xe chạy cung đường đèo',
        tool: 'Kling, VEO3',
        description: 'Video điện ảnh xe vượt đèo lúc hoàng hôn.',
        content: script({
          info: '20 giây · ngang 16:9 hoặc dọc 9:16 · Kling (ảnh xe thật)',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: '[Ảnh xe thật] Close-up of the car\'s headlights turning on at dusk, rain droplets on the hood. Keep the car design exactly the same as the input image.' },
            { time: '5–12s', label: 'VẬN HÀNH', prompt: 'Drone chase shot of the car driving along a winding mountain pass in Ha Giang at sunset, smooth curves, golden light reflecting on the body.' },
            { time: '12–17s', label: 'CHI TIẾT', prompt: 'Low tracking shot of the wheel spinning on the road, then interior shot of hands on the steering wheel.' },
            { time: '17–20s', label: 'KẾT', prompt: 'The car parks on a cliff edge overlooking the valley, camera slowly orbits.' },
          ],
          audio: 'nhạc hùng tráng; SFX: tiếng động cơ, lốp, gió.',
          text: 'Tên mẫu xe · giá lăn bánh tham khảo · ưu đãi.',
          cta: '"Đặt lịch lái thử tại showroom gần nhất."',
        }),
      },
      {
        title: 'Showroom giới thiệu tính năng',
        tool: 'VEO3, Kling',
        description: 'Tư vấn viên giới thiệu 3 tính năng nổi bật của mẫu xe.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3 + Kling',
          character: 'ADVISOR: a 29-year-old Vietnamese male sales advisor, slim black suit, white shirt, name badge.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'VEO3', prompt: `ADVISOR stands next to the car in a bright showroom, smiles at the camera. ${NO_TEXT}`, voice: 'Tư vấn viên: "3 lý do mẫu xe này đang bán chạy nhất tháng!"' },
            { time: '4–12s', label: 'TÍNH NĂNG 1', tool: 'Kling', prompt: '[Ảnh thật] Interior close-up: a large touchscreen lights up, ambient lighting glows.', voice: '"Một: màn hình [x] inch, kết nối điện thoại không dây."' },
            { time: '12–20s', label: 'TÍNH NĂNG 2', tool: 'Kling', prompt: '[Ảnh thật] Rear seats folding flat, large trunk space with luggage.', voice: '"Hai: khoang hành lý rộng, gập ghế linh hoạt."' },
            { time: '20–30s', label: 'TÍNH NĂNG 3 + CTA', tool: 'VEO3', prompt: `ADVISOR opens the driver door and invites the viewer in. ${NO_TEXT}`, voice: '"Ba: [trang bị an toàn]. Mời anh chị đến lái thử!"' },
          ],
          audio: 'nhạc nền hiện đại.',
          text: 'Tính năng 1–2–3 (đúng thông số của hãng).',
          cta: '"Nhắn tin nhận báo giá + ưu đãi tháng này."',
        }),
      },
      {
        title: 'Garage bảo dưỡng chuyên nghiệp',
        tool: 'Kling, VEO3',
        description: 'Video dịch vụ: quy trình kiểm tra, minh bạch, sạch sẽ.',
        content: script({
          info: '25 giây · dọc 9:16 · Kling + VEO3',
          character: 'MECHANIC: a 35-year-old Vietnamese mechanic, navy uniform with logo, gloves, short hair.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'A car rolls into a clean, bright garage bay, lift raises the car. Wide shot.' },
            { time: '5–14s', label: 'KIỂM TRA', tool: 'Kling', prompt: 'MECHANIC checks brakes, oil, tires with a diagnostic tablet, close-up shots, professional.' },
            { time: '14–21s', label: 'MINH BẠCH', tool: 'VEO3', prompt: `MECHANIC shows a customer the old brake pad and explains. ${NO_TEXT}`, voice: 'Kỹ thuật viên: "Má phanh mòn rồi anh, em báo giá trước, anh đồng ý mới thay."' },
            { time: '21–25s', label: 'BÀN GIAO', tool: 'Kling', prompt: 'The washed car gleams under lights, customer receives keys and smiles.' },
          ],
          audio: 'nhạc nhịp vừa; SFX: tiếng cờ lê, máy nâng.',
          text: '"Báo giá trước – làm sau" · gói bảo dưỡng · giá.',
          cta: '"Đặt lịch bảo dưỡng – miễn phí rửa xe."',
        }),
      },
      {
        title: 'Xe máy điện đi phố',
        tool: 'Kling, VEO3',
        description: 'Lifestyle trẻ trung: tiết kiệm, êm ái, sạc tại nhà.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling + VEO3',
          character: 'RIDER: a 23-year-old Vietnamese woman, white helmet, denim jacket, tote bag.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'Kling', prompt: '[Ảnh xe thật] RIDER silently rides the electric scooter through a tree-lined Hanoi street in the morning. Keep the scooter design exactly the same as the input image.' },
            { time: '4–10s', label: 'ĐI PHỐ', tool: 'Kling', prompt: 'RIDER weaves easily through city traffic, stops at a café, parks easily.' },
            { time: '10–16s', label: 'SẠC', tool: 'VEO3', prompt: `At home, RIDER plugs the charger into a wall socket, smiles at the camera. ${NO_TEXT}`, voice: 'Cô gái: "Sạc qua đêm, đi cả tuần, không lo giá xăng."' },
            { time: '16–20s', label: 'KẾT', tool: 'Kling', prompt: 'RIDER rides off into golden sunset.' },
          ],
          audio: 'nhạc chill; SFX: tiếng xe rất êm.',
          text: 'Quãng đường/1 lần sạc · giá · ưu đãi (đúng thông số).',
          cta: '"Đến cửa hàng lái thử miễn phí."',
        }),
      },
      {
        title: 'Review lái thử kiểu UGC',
        tool: 'VEO3',
        description: 'Khách hàng lái thử chia sẻ cảm nhận thật.',
        content: script({
          info: '25 giây · dọc 9:16 · VEO3',
          character: 'DRIVER: a 34-year-old Vietnamese man, short hair, light grey polo shirt, sunglasses on head.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `Selfie shot inside the car, DRIVER in the driver seat. Phone mounted on dashboard. ${NO_TEXT}`, voice: 'Tài xế: "Lái thử 30 phút, nói thật cảm nhận của mình nha."' },
            { time: '4–14s', label: 'ĐÁNH GIÁ', prompt: `DRIVER drives on a city road, talks while driving calmly. ${NO_TEXT}`, voice: '"Cách âm tốt, vô lăng nhẹ, đi phố rất thoải mái."' },
            { time: '14–25s', label: 'KẾT', prompt: `DRIVER parks, turns to the camera with a thumbs up. ${NO_TEXT}`, voice: '"Hợp gia đình nhỏ như mình. Ai cần thông tin, comment nhé!"' },
          ],
          audio: 'tiếng xe êm, nhạc nhẹ.',
          text: 'Ưu điểm chính · "Cảm nhận cá nhân".',
          cta: '"Đặt lịch lái thử miễn phí."',
        }),
      },
    ],
  },
];
