// Prompt tạo video AI theo ngành – phần 1.
const { script, director } = require('./format');

const NO_TEXT = 'No subtitles, no text on screen.';

module.exports = [
  {
    name: 'Giải trí & Kể chuyện', color: '#E11D48', from: ['Làm video AI'],
    prompts: [
      {
        title: 'Prompt đạo diễn: viết kịch bản video giải trí viral',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Dán vào ChatGPT/Gemini để có kịch bản video hài, kể chuyện, series nhân vật kèm prompt từng cảnh.',
        content: director({
          role: 'biên kịch video giải trí viral trên TikTok/Reels',
          product: '[chủ đề / tình huống: ví dụ "khi mẹ gọi về ăn cơm", "một ngày của chú mèo tinh nghịch"]',
          audience: '[độ tuổi, sở thích, ví dụ: Gen Z 18–25 thích nội dung hài đời thường]',
          goals: 'giữ người xem đến giây cuối, tăng chia sẻ và bình luận',
          styles: '[hài tình huống / cảm động / kinh dị nhẹ / hoạt hình 3D Pixar / vlog động vật biết nói]',
          notes: 'có "twist" bất ngờ ở 3–5 giây cuối; lời thoại ngắn, đời thường, đúng văn nói người Việt.',
        }),
      },
      {
        title: 'Hài tình huống: "Mẹ gọi về ăn cơm"',
        tool: 'VEO3',
        description: 'Video hài 25 giây, 2 nhân vật, có thoại tiếng Việt và cú twist cuối.',
        content: script({
          info: '25 giây · dọc 9:16 · VEO3 (có thoại)',
          character: 'SON: a 22-year-old Vietnamese guy, messy black hair, oversized grey hoodie, headphones around neck. MOM: a 50-year-old Vietnamese mother, short permed hair, floral house clothes, holding a ladle.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'VEO3', prompt: `Medium shot, SON sits at a gaming desk in a dim bedroom lit by RGB lights, fully focused on the screen, tapping keys fast. From outside the door, MOM shouts. Handheld, slight push in. ${NO_TEXT}`, voice: 'Mẹ (ngoài cửa): "Con ơi xuống ăn cơm!" – Con: "Dạ 5 phút nữa con xuống!"' },
            { time: '4–9s', label: 'LẶP LẠI', tool: 'VEO3', prompt: `Same bedroom, a wall clock in the foreground jumps forward 30 minutes, SON still gaming, yawning. MOM's voice louder from outside. Static wide shot, comedic timing. ${NO_TEXT}`, voice: 'Mẹ: "5 phút của con là 30 phút rồi đó!"' },
            { time: '9–16s', label: 'CAO TRÀO', tool: 'VEO3', prompt: `The door slowly creaks open, MOM stands in the doorway holding a ladle like a sword, dramatic backlight from the hallway, smoke-like steam behind her. Low angle on MOM, then quick cut to SON's terrified face. Epic movie style. ${NO_TEXT}`, voice: 'Mẹ (bình tĩnh đáng sợ): "Con chọn đi: xuống ăn cơm… hay mẹ rút dây mạng?"' },
            { time: '16–22s', label: 'TWIST', tool: 'VEO3', prompt: `Dining table with a warm family dinner, SON eats happily with big bites, MOM smiles. Then SON secretly glances at his phone under the table showing the game. Medium shot, warm tungsten light, comedic. ${NO_TEXT}`, voice: 'Con: "Cơm mẹ nấu là số một!" (mắt vẫn liếc điện thoại)' },
            { time: '22–25s', label: 'KẾT', tool: 'VEO3', prompt: `Close-up on MOM, she calmly pulls out the Wi-Fi router from behind her back and raises an eyebrow at the camera. Freeze-frame feel. ${NO_TEXT}`, voice: 'Mẹ: "Mẹ biết hết nha."' },
          ],
          audio: 'nhạc hài nhẹ kiểu sitcom; SFX: tiếng gõ phím, "tích tắc" đồng hồ, cửa kẽo kẹt, tiếng "dun dun dun" kịch tính, record scratch ở cảnh cuối.',
          text: '"5 phút nữa" (cảnh 1) · "30 phút sau…" (cảnh 2)',
          cta: '"Tag đứa bạn hay nói 5 phút nữa!" – kêu gọi bình luận, theo dõi để xem phần 2.',
        }),
      },
      {
        title: 'Kể chuyện cảm động: Ông cụ bán bánh mì',
        tool: 'VEO3, Kling, ElevenLabs',
        description: 'Phim ngắn 45 giây có lời kể, cấu trúc 3 hồi, kết thúc ấm lòng.',
        content: script({
          info: '45 giây · dọc 9:16 · VEO3 / Kling + lời kể (ElevenLabs hoặc VEO3)',
          character: 'OLD MAN: a 75-year-old Vietnamese street vendor, kind wrinkled face, white stubble, faded blue shirt, conical hat, pushes a small wooden bánh mì cart.',
          scenes: [
            { time: '0–6s', label: 'MỞ ĐẦU', tool: 'Kling', prompt: 'Cinematic side tracking shot of OLD MAN pushing his bánh mì cart along a quiet Saigon alley at dawn, warm haze, film grain, slow and peaceful.', voice: 'Lời kể: "Suốt 30 năm, ông Tư bán bánh mì ở đầu con hẻm này, mỗi ổ chỉ 10 nghìn."' },
            { time: '6–16s', label: 'KHÓ KHĂN', tool: 'Kling', prompt: 'OLD MAN sits alone on a small plastic stool under heavy rain beside his cart, no customers, holding an old family photo. Slow push in to his face, cold desaturated light, emotional drama.', voice: '"Rồi quán xá mọc lên khắp nơi. Có ngày, ông chẳng bán nổi một ổ."' },
            { time: '16–30s', label: 'BƯỚC NGOẶT', tool: 'VEO3', prompt: `A group of Vietnamese students in white school uniforms run through the rain toward OLD MAN, holding umbrellas over him and smiling; one girl hands him a handwritten card. Wide shot pushing in, then close-up of his teary eyes. Warm streetlight, slow motion. ${NO_TEXT}`, voice: 'Học sinh: "Ông ơi, tụi con lớn lên nhờ bánh mì của ông đó!"' },
            { time: '30–42s', label: 'KẾT ẤM LÒNG', tool: 'Kling', prompt: 'Next morning, a long line of happy customers in front of OLD MAN\'s cart, he laughs while making sandwiches, golden sunlight fills the alley. Slow crane up revealing the lively alley.', voice: '"Có những điều tử tế, chỉ cần một người bắt đầu."' },
            { time: '42–45s', label: 'KHÉP LẠI', tool: 'Kling', prompt: 'Close-up of the handwritten card pinned on the cart, fluttering in the breeze, soft focus, warm light.' },
          ],
          audio: 'piano nhẹ → cello buồn (cảnh mưa) → nhạc dâng hy vọng; SFX: mưa, xe máy xa, tiếng cười.',
          text: 'Câu kết: "Bạn đã ghé hàng quen nào gần nhà chưa?"',
          cta: 'Kêu gọi chia sẻ video cho một người bán hàng quen; theo dõi kênh để xem câu chuyện tiếp theo.',
        }),
      },
      {
        title: 'Vlog động vật biết nói (mèo cam)',
        tool: 'VEO3',
        description: 'Định dạng viral: thú cưng nói chuyện, kể "một ngày của tôi", giọng hài.',
        content: script({
          info: '20 giây · dọc 9:16 · VEO3 (thoại giọng hoạt hình)',
          character: 'MILO: a chubby orange tabby cat with big green eyes, a tiny blue collar with a bell, very expressive face.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `Close-up selfie-style shot, MILO looks straight into the camera on a sofa, mouth moving as if talking, cute and sassy expression. Realistic cat, natural daylight. ${NO_TEXT}`, voice: 'Milo: "Chào cả nhà, hôm nay em sẽ cho mọi người xem em làm việc chăm chỉ thế nào."' },
            { time: '4–9s', label: '"LÀM VIỆC"', prompt: 'MILO lies on a laptop keyboard in a home office, pushing a pen off the desk with his paw while looking at the camera. Static medium shot, comedic.', voice: '"9 giờ: kiểm tra laptop của sen. Kết luận: ấm, rất ấm."' },
            { time: '9–15s', label: 'GIỜ ĂN', prompt: 'MILO sits next to an empty food bowl, staring dramatically at the camera, then flops onto his back. Low angle, warm kitchen light.', voice: '"12 giờ: bát trống. Đây là ngược đãi. Em sẽ kiện."' },
            { time: '15–20s', label: 'TWIST', prompt: 'Owner\'s hand pours cat food into the bowl, MILO instantly jumps up and eats happily, then winks at the camera. Close-up, playful.', voice: '"…Thôi, em rút đơn kiện."' },
          ],
          audio: 'nhạc lo-fi vui; SFX: tiếng chuông cổ, "pop" hoạt hình, tiếng hạt đổ vào bát.',
          cta: '"Mèo nhà bạn có hay \'kiện\' không? Bình luận nhé!"',
        }),
      },
      {
        title: 'Phỏng vấn đường phố nhân vật lịch sử',
        tool: 'VEO3',
        description: 'Format "street interview" vui với nhân vật lịch sử / nghề xưa, vừa giải trí vừa kiến thức.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3 (có thoại 2 người)',
          character: 'REPORTER: a 25-year-old Vietnamese woman, short bob hair, denim jacket, holding a microphone. SCHOLAR: a Vietnamese Confucian scholar from the Ly dynasty, long black beard, traditional dark blue robe, black scholar hat.',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: `Handheld street-interview shot in front of the Temple of Literature in Hanoi, REPORTER walks up to SCHOLAR and holds the microphone toward him. Realistic, vlog style, daylight. ${NO_TEXT}`, voice: 'Phóng viên: "Ông ơi, cho con hỏi thời của ông đi thi khó cỡ nào ạ?"' },
            { time: '5–14s', label: 'TRẢ LỜI', prompt: `Medium close-up of SCHOLAR stroking his beard, answering calmly with a proud expression, tourists blurred in the background. ${NO_TEXT}`, voice: 'Nho sĩ: "Thi ba vòng, mỗi vòng cả ngày, không có máy lạnh, không có… ChatGPT."' },
            { time: '14–22s', label: 'TƯƠNG TÁC', prompt: `REPORTER shows SCHOLAR her smartphone screen; he squints, surprised, leaning in. Two-shot, handheld, comedic. ${NO_TEXT}`, voice: 'Phóng viên: "Giờ hỏi gì máy cũng trả lời đó ông." – Nho sĩ: "Vậy… máy có đi thi Trạng nguyên không?"' },
            { time: '22–30s', label: 'KẾT + KIẾN THỨC', prompt: `SCHOLAR laughs and points at the stone stelae of doctors in the courtyard, camera pans to the stelae. ${NO_TEXT}`, voice: 'Nho sĩ: "Tên ai đỗ đạt đều được khắc bia ở đây đó con, 82 tấm bia còn lại tới bây giờ!"' },
          ],
          audio: 'tiếng phố, nhạc nền dân gian hiện đại nhẹ; SFX: "ding" khi nêu kiến thức.',
          text: 'Chú thích kiến thức: "82 bia Tiến sĩ – Văn Miếu Quốc Tử Giám" (kiểm tra lại số liệu trước khi đăng).',
          cta: '"Muốn phỏng vấn nhân vật lịch sử nào tiếp theo? Bình luận nhé!"',
        }),
      },
      {
        title: 'Series hoạt hình 3D – Tập 1',
        tool: 'Kling, VEO3',
        description: 'Mở đầu series nhân vật hoạt hình 3D phong cách Pixar cho thiếu nhi / gia đình.',
        content: script({
          info: '40 giây · dọc 9:16 hoặc ngang 16:9 · Kling (chuyển động) + VEO3 (thoại)',
          character: 'BI: a 6-year-old Vietnamese boy in 3D Pixar style, round face, big brown eyes, spiky black hair, yellow T-shirt with a star, red sneakers. LU: his small white robot friend with round blue LED eyes.',
          scenes: [
            { time: '0–6s', label: 'MỞ ĐẦU', tool: 'Kling', prompt: '3D Pixar-style animation, BI runs out of a colorful house into a sunny garden full of giant flowers, LU flying behind him. Smooth tracking shot, vibrant colors, soft global illumination.' },
            { time: '6–16s', label: 'VẤN ĐỀ', tool: 'VEO3', prompt: `3D Pixar-style animation, BI kneels next to a small wilted sunflower, looking sad, LU beeps beside him. Close-up, warm light. ${NO_TEXT}`, voice: 'Bi: "Lu ơi, sao bông hoa của tớ héo rồi?" – Lu: "Bíp! Cây cần nước và ánh nắng đó!"' },
            { time: '16–28s', label: 'HÀNH ĐỘNG', tool: 'Kling', prompt: '3D Pixar-style animation, BI carries a small blue watering can and waters the sunflower, LU opens a tiny umbrella-shaped solar panel to reflect sunlight on it. Playful bouncy motion, sparkles.' },
            { time: '28–36s', label: 'KẾT QUẢ', tool: 'Kling', prompt: '3D Pixar-style animation, the sunflower slowly rises and blooms brightly, BI jumps with joy and hugs LU. Slow push in, magical light particles.' },
            { time: '36–40s', label: 'BÀI HỌC', tool: 'VEO3', prompt: `3D Pixar-style animation, BI faces the camera and smiles, LU beside him. Medium shot. ${NO_TEXT}`, voice: 'Bi: "Chăm cây mỗi ngày, cây sẽ lớn thật nhanh! Hẹn gặp lại các bạn ở tập sau nha!"' },
          ],
          audio: 'nhạc thiếu nhi vui tươi; SFX: tiếng bíp robot, nước tưới, "ting" lấp lánh.',
          text: 'Tên series ở đầu video: "Bi và Lu – Tập 1: Bông hoa héo"',
          cta: 'Theo dõi để xem Tập 2; gợi ý phụ huynh cho bé xem cùng.',
        }),
      },
    ],
  },

  {
    name: 'Bán hàng online & TMĐT', color: '#0D9488', from: ['Bán hàng online'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video bán hàng TikTok Shop / Shopee',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Tạo kịch bản video bán hàng ra đơn kèm prompt từng cảnh cho bất kỳ sản phẩm nào.',
        content: director({
          role: 'đạo diễn video bán hàng chuyên ra đơn trên TikTok Shop và Shopee Video',
          product: '[tên sản phẩm, giá, 3 điểm nổi bật, ưu đãi đang chạy]',
          audience: '[ví dụ: nữ 22–40 tuổi, nội trợ / dân văn phòng, quan tâm tiện lợi và giá tốt]',
          goals: 'người xem bấm giỏ hàng trong 15–30 giây',
          styles: '[UGC chân thật / review / unbox ASMR / problem → solution / so sánh A vs B]',
          notes: 'nếu có ảnh sản phẩm thật, các cảnh sản phẩm dùng Kling image-to-video và ghi "keep the product, label and logo exactly the same as the input image"; không hứa hẹn sai công dụng.',
        }),
      },
      {
        title: 'Review gia dụng kiểu UGC (máy xay mini)',
        tool: 'VEO3, Kling',
        description: 'Review chân thật như khách thật quay điện thoại, 20 giây, có CTA giỏ hàng.',
        content: script({
          info: '20 giây · dọc 9:16 · VEO3 (thoại) + Kling (cảnh sản phẩm từ ảnh thật)',
          character: 'LAN: a 30-year-old Vietnamese woman, natural makeup, hair in a messy bun, pastel home T-shirt.',
          scenes: [
            { time: '0–3s', label: 'HOOK', tool: 'VEO3', prompt: `Selfie-style vertical video shot on iPhone, LAN stands in her small bright kitchen holding a [màu] mini portable blender toward the camera, surprised face. Handheld, natural window light. ${NO_TEXT}`, voice: 'Lan: "Mua thử 199 nghìn mà xài sướng hơn máy xay to ở nhà!"' },
            { time: '3–9s', label: 'DEMO', tool: 'Kling', prompt: '[Dùng ảnh sản phẩm thật] Close-up: banana and milk inside the portable blender, the blades spin and blend smoothly into a creamy smoothie. Static camera, bright kitchen light. Keep the product shape and logo exactly the same as the input image.', voice: '"Bỏ chuối với sữa vô, bấm một nút, 20 giây là xong."' },
            { time: '9–15s', label: 'LỢI ÍCH', tool: 'VEO3', prompt: `Medium shot, LAN unscrews the blender cup and drinks directly from it, then puts it into her handbag. Natural, handheld. ${NO_TEXT}`, voice: '"Uống luôn bằng cốc, sạc USB, bỏ túi mang đi làm."' },
            { time: '15–20s', label: 'CTA', tool: 'VEO3', prompt: `LAN points down toward the bottom of the frame and smiles at the camera, kitchen background. Leave empty space at the bottom for price text. ${NO_TEXT}`, voice: '"Đang giảm giá trong giỏ hàng nha, nhanh tay kẻo hết!"' },
          ],
          audio: 'nhạc trend vui nhộn nhỏ; SFX: tiếng máy xay, "ting" khi hiện giá.',
          text: '"Chỉ 199K" · "Sạc USB – mang đi mọi nơi" · mũi tên chỉ giỏ hàng.',
          cta: '"Bấm giỏ hàng góc trái màn hình để đặt ngay."',
        }),
      },
      {
        title: 'Unbox ASMR (không thoại)',
        tool: 'Kling, VEO3',
        description: 'Video mở hộp đã tai, góc từ trên xuống – hợp mỹ phẩm, đồ công nghệ, quà tặng.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling / VEO3 (âm thanh ASMR, không thoại)',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `Top-down shot of a pastel gift box with a ribbon on a clean white desk next to a small plant; two hands slowly pull the ribbon. Soft daylight, aesthetic. ASMR ribbon sound. ${NO_TEXT}` },
            { time: '4–8s', label: 'MỞ HỘP', prompt: 'Top-down, hands lift the lid and peel back tissue paper, revealing [sản phẩm] nestled inside. Slow, satisfying movements, ASMR paper rustling.' },
            { time: '8–12s', label: 'KHOE SẢN PHẨM', prompt: '[Dùng ảnh sản phẩm thật] Hands lift [sản phẩm] toward the camera and slowly rotate it to show details, soft reflections. Keep the product exactly the same as the input image.' },
            { time: '12–15s', label: 'KẾT', prompt: 'Final flat lay: product placed beside its box and accessories, neat composition, camera slowly rises. Clean, premium.' },
          ],
          audio: 'không nhạc hoặc lo-fi rất nhỏ; ASMR: băng keo, giấy sột soạt, nắp hộp "pop".',
          text: 'Tên sản phẩm + giá ở cảnh cuối (chèn bằng CapCut).',
          cta: '"Link trong giỏ hàng" + mũi tên.',
        }),
      },
      {
        title: 'Problem → Solution (máy hút bụi cầm tay)',
        tool: 'VEO3, Kling',
        description: 'Nêu nỗi đau → giải pháp → chứng minh → CTA. Công thức ra đơn mạnh nhất.',
        content: script({
          info: '25 giây · dọc 9:16 · VEO3 + Kling',
          character: 'HUNG: a 35-year-old Vietnamese father, short hair, glasses, casual polo shirt.',
          scenes: [
            { time: '0–4s', label: 'VẤN ĐỀ', tool: 'VEO3', prompt: `Medium shot, HUNG sighs looking at cookie crumbs and cat hair all over a dark sofa in a living room, his toddler giggling in the background. Slightly desaturated, flat light. ${NO_TEXT}`, voice: 'Hưng: "Ngày nào cũng một bãi chiến trường thế này…"' },
            { time: '4–8s', label: 'KHUẤY ĐỘNG', tool: 'VEO3', prompt: `HUNG drags out a big heavy vacuum cleaner, the cord tangles around his foot, he almost trips. Comedic, handheld. ${NO_TEXT}`, voice: '"Lôi máy to ra thì mất 10 phút…"' },
            { time: '8–16s', label: 'GIẢI PHÁP', tool: 'Kling', prompt: '[Dùng ảnh sản phẩm thật] Close-up of a cordless handheld vacuum cleaning crumbs and cat hair from the sofa in one smooth pass, the area becomes perfectly clean. Bright warm light. Keep the product exactly the same as the input image.', voice: '"Giờ cầm em này lên, 30 giây sạch bong."' },
            { time: '16–21s', label: 'CHỨNG MINH', tool: 'Kling', prompt: 'Close-up of the transparent dust bin full of crumbs and hair being emptied into a trash can with one click. Satisfying, static camera.', voice: '"Lực hút mạnh, đổ rác một chạm, sạc một lần dùng cả tuần."' },
            { time: '21–25s', label: 'CTA', tool: 'VEO3', prompt: `HUNG relaxes on the clean sofa with his toddler, gives a thumbs up to the camera. Warm light. ${NO_TEXT}`, voice: '"Bấm giỏ hàng đi, đang có quà tặng kèm đó!"' },
          ],
          audio: 'đầu video nhạc trầm, từ cảnh 3 chuyển nhạc tươi; SFX: tiếng máy hút, "click" đổ rác.',
          text: '"Trước" / "Sau" · "Sạc 1 lần – dùng 7 ngày" (đúng thông số thật).',
          cta: '"Giảm [x]% + tặng đầu hút phụ – chỉ hôm nay."',
        }),
      },
      {
        title: 'Flash sale ngày đôi (10.10, 11.11…)',
        tool: 'VEO3, Kling',
        description: 'Video đếm ngược tạo cảm giác khẩn cấp cho chương trình sale.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling + VEO3',
          character: 'HOST: a cheerful 25-year-old Vietnamese woman, long wavy hair, bright red blazer, holding a smartphone.',
          scenes: [
            { time: '0–3s', label: 'HOOK', tool: 'Kling', prompt: 'Dynamic shot: giant glowing numbers "[ngày sale]" made of neon lights explode with confetti in a dark studio, camera fast push in. Energetic, vibrant.' },
            { time: '3–8s', label: 'ƯU ĐÃI', tool: 'VEO3', prompt: `HOST stands in a colorful studio with shopping boxes flying around her, speaks excitedly to the camera. Medium shot, bright lights. ${NO_TEXT}`, voice: 'Host: "Đúng 0 giờ đêm nay, toàn bộ shop giảm tới [x]%!"' },
            { time: '8–12s', label: 'SẢN PHẨM', tool: 'Kling', prompt: '[Dùng ảnh 3 sản phẩm bán chạy] Products pop onto a turntable one after another with sparkle effects, quick and rhythmic.' },
            { time: '12–15s', label: 'ĐẾM NGƯỢC', tool: 'VEO3', prompt: `HOST taps her phone and points at the camera, confetti falling. ${NO_TEXT}`, voice: '"Đặt nhắc lịch ngay kẻo lỡ nha!"' },
          ],
          audio: 'nhạc EDM sôi động; SFX: tiếng nổ confetti, "cha-ching", tiếng đồng hồ đếm ngược.',
          text: '"[ngày sale] – SALE TỚI [x]%" · "Freeship toàn quốc" · đồng hồ đếm ngược.',
          cta: '"Bấm theo dõi shop + đặt nhắc lịch Live 0h."',
        }),
      },
      {
        title: 'So sánh A vs B (chia đôi màn hình)',
        tool: 'Kling',
        description: 'So sánh sản phẩm thường với sản phẩm của bạn – trực quan, dễ hiểu.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling (2 clip ghép chia đôi màn hình trong CapCut)',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: 'Two identical white shirts with a red wine stain laid side by side on a table, top-down view, bright laundry room light.', voice: 'Lời kể: "Cùng một vết rượu vang, hai loại nước giặt…"' },
            { time: '3–10s', label: 'SO SÁNH', prompt: 'LEFT clip: a regular detergent scrubbed on the stain, the stain fades only slightly. RIGHT clip: [sản phẩm] applied, the stain dissolves completely after a gentle rub. Identical framing, static close-up.' },
            { time: '10–15s', label: 'KẾT QUẢ', prompt: 'Both shirts held up side by side: left still stained, right spotless white. Bright natural light, slow push in on the clean shirt.', voice: '"Kết quả tự nói lên tất cả."' },
          ],
          audio: 'nhạc hồi hộp nhẹ → "ting"; SFX: tiếng chà vải, nước.',
          text: 'Nhãn "Loại thường" / "[Tên sản phẩm]" trên hai nửa màn hình. Chỉ so sánh trung thực, không nêu tên thương hiệu đối thủ.',
          cta: '"Thử ngay – link trong giỏ hàng."',
        }),
      },
    ],
  },

  {
    name: 'Mỹ phẩm & Làm đẹp', color: '#DB2777', from: ['Y tế & Làm đẹp'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video mỹ phẩm, spa, thẩm mỹ',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video quảng cáo mỹ phẩm / spa tuân thủ quy định, kèm prompt từng cảnh.',
        content: director({
          role: 'đạo diễn quảng cáo ngành làm đẹp (mỹ phẩm, spa, thẩm mỹ)',
          product: '[tên sản phẩm / dịch vụ, thành phần chính, công dụng đã được công bố, giá, ưu đãi]',
          audience: '[ví dụ: nữ 22–35 tuổi, da dầu mụn, quan tâm thành phần lành tính]',
          goals: 'tăng niềm tin và đặt mua / đặt lịch',
          styles: '[TVC sang trọng / GRWM UGC / quy trình skincare / trải nghiệm spa]',
          notes: 'không cam kết "100%", "vĩnh viễn", "trị dứt điểm"; ghi chú "kết quả tùy cơ địa"; không dùng hình ảnh trước–sau chỉnh sửa sai sự thật.',
        }),
      },
      {
        title: 'TVC serum sang trọng 15 giây',
        tool: 'Kling, VEO3',
        description: 'Quảng cáo không thoại, slow motion, ánh sáng cao cấp – phong cách thương hiệu lớn.',
        content: script({
          info: '15 giây · dọc 9:16 hoặc 4:5 · Kling (sản phẩm từ ảnh thật) + VEO3 (người mẫu)',
          character: 'MODEL: a 26-year-old Vietnamese woman, glowing dewy skin, slicked-back black hair, minimal makeup, bare shoulders.',
          scenes: [
            { time: '0–3s', label: 'HOOK', tool: 'Kling', prompt: 'Extreme macro slow motion: a single golden serum drop falls from a glass dropper and splashes onto a smooth surface of water, creating perfect ripples. Dark emerald background, glossy highlights.' },
            { time: '3–7s', label: 'SẢN PHẨM', tool: 'Kling', prompt: '[Dùng ảnh chai serum thật] The serum bottle stands on wet black stone surrounded by white orchid petals, soft mist drifts across, slow orbit camera, luxury lighting. Keep the bottle and label exactly the same as the input image.' },
            { time: '7–12s', label: 'TRẢI NGHIỆM', tool: 'VEO3', prompt: `Close-up beauty shot, MODEL gently pats serum onto her cheek with fingertips, eyes closed, serene expression, skin glowing under soft golden light. Slow motion, shallow depth of field. ${NO_TEXT}` },
            { time: '12–15s', label: 'PACKSHOT', tool: 'Kling', prompt: 'Final packshot: the bottle alone on a dark reflective surface under a single spotlight, a soft glow around it, camera very slowly pushes in.' },
          ],
          audio: 'nhạc ambient sang trọng (piano + dây); SFX: giọt nước "tách", tiếng gió nhẹ.',
          text: 'Tên sản phẩm + 1 câu slogan ngắn + "Kết quả có thể khác nhau tùy cơ địa".',
          cta: '"Khám phá tại [kênh bán] – ưu đãi ra mắt [ưu đãi]."',
        }),
      },
      {
        title: 'Get Ready With Me (GRWM) – UGC',
        tool: 'VEO3',
        description: 'Trang điểm buổi sáng tự nhiên, lồng sản phẩm khéo léo như chia sẻ cá nhân.',
        content: script({
          info: '25 giây · dọc 9:16 · VEO3',
          character: 'MAI: a 22-year-old Vietnamese university student, shoulder-length black hair with a claw clip, oversized white T-shirt, fresh face.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `UGC vertical video, phone propped on a messy vanity table, MAI sits down in her bedroom in the morning and talks to the camera. Soft window light, shot on iPhone. ${NO_TEXT}`, voice: 'Mai: "Trễ học rồi, make up 5 phút thôi nha mọi người!"' },
            { time: '4–12s', label: 'BƯỚC 1–2', prompt: `MAI applies [sản phẩm: cushion / kem chống nắng] with a puff on her face, quick and natural, chatting. Medium close-up, natural. ${NO_TEXT}`, voice: '"Bước một là em này nè, mỏng nhẹ mà che được thâm mụn luôn."' },
            { time: '12–19s', label: 'BƯỚC 3', prompt: `MAI swipes a [màu] lip tint on her lips and presses them together, smiles at the camera. Close-up, soft light. ${NO_TEXT}`, voice: '"Thêm chút son là xong, tươi tỉnh liền."' },
            { time: '19–25s', label: 'KẾT', prompt: `MAI grabs her backpack and waves at the camera while walking out of the room. Handheld, cheerful. ${NO_TEXT}`, voice: '"Đồ mình dùng để trong giỏ hàng nha, đi học đây!"' },
          ],
          audio: 'nhạc lo-fi buổi sáng; SFX: tiếng mở nắp cushion "tách".',
          text: '"5-minute make up" · tên sản phẩm ở từng bước.',
          cta: '"Sản phẩm trong giỏ hàng – mã giảm cho bạn mới."',
        }),
      },
      {
        title: 'Quy trình skincare 3 bước buổi tối',
        tool: 'VEO3, Kling',
        description: 'Video giáo dục + bán hàng: hướng dẫn quy trình chăm da dễ làm theo.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3 (thoại) + Kling (cận cảnh kết cấu)',
          character: 'LINH: a 28-year-old Vietnamese woman, hair wrapped in a white towel, clean face, soft pink pajamas.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'VEO3', prompt: `LINH sits in front of a bathroom mirror at night, looks at the camera. Warm soft light. ${NO_TEXT}`, voice: 'Linh: "Da dầu mụn thì tối chỉ cần đúng 3 bước này thôi."' },
            { time: '4–12s', label: 'BƯỚC 1 – LÀM SẠCH', tool: 'Kling', prompt: 'Macro close-up of rich white foam cleanser lathered between hands, then gently massaged on the cheek. Bubbles visible, soft light.', voice: '"Một: rửa mặt dịu nhẹ, massage 60 giây."' },
            { time: '12–20s', label: 'BƯỚC 2 – ĐẶC TRỊ', tool: 'Kling', prompt: '[Dùng ảnh sản phẩm thật] Close-up: a clear serum drop on fingertips, lightly patted onto skin, glossy texture. Keep the bottle exactly the same as the input image.', voice: '"Hai: serum [thành phần], chấm nhẹ vùng có mụn."' },
            { time: '20–26s', label: 'BƯỚC 3 – DƯỠNG ẨM', tool: 'Kling', prompt: 'Close-up of a light gel moisturizer scooped and spread on the cheek, skin looks hydrated and calm.', voice: '"Ba: kem dưỡng mỏng nhẹ để khóa ẩm."' },
            { time: '26–30s', label: 'CTA', tool: 'VEO3', prompt: `LINH smiles at the camera holding the three products. ${NO_TEXT}`, voice: '"Combo 3 bước mình để trong giỏ hàng nha. Nhớ kiên trì nhé!"' },
          ],
          audio: 'nhạc thư giãn; SFX: nước chảy, "pop" khi hiện tên bước.',
          text: 'Bước 1 – Làm sạch · Bước 2 – Đặc trị · Bước 3 – Dưỡng ẩm · "Kết quả tùy cơ địa".',
          cta: '"Mua combo tiết kiệm [x]% trong giỏ hàng."',
        }),
      },
      {
        title: 'Trải nghiệm spa thư giãn',
        tool: 'Kling, VEO3',
        description: 'Video giới thiệu spa / liệu trình chăm sóc da, nhấn vào cảm giác thư giãn.',
        content: script({
          info: '30 giây · dọc 9:16 · Kling + VEO3',
          character: 'GUEST: a 30-year-old Vietnamese woman in a white spa robe. THERAPIST: a Vietnamese woman in a beige spa uniform, hair in a neat bun.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'Slow dolly through a calm spa entrance with candles, orchids and flowing water, warm dim light, steam in the air. Luxury wellness.' },
            { time: '5–13s', label: 'ĐÓN KHÁCH', tool: 'VEO3', prompt: `THERAPIST welcomes GUEST with a cup of herbal tea in a quiet lounge, both smiling. Medium shot, soft warm light. ${NO_TEXT}`, voice: 'Kỹ thuật viên: "Chào chị, hôm nay mình thư giãn với liệu trình [tên liệu trình] nha."' },
            { time: '13–22s', label: 'LIỆU TRÌNH', tool: 'Kling', prompt: 'GUEST lies on a treatment bed, eyes closed, THERAPIST gently applies a green herbal mask with a brush. Slow push in, candlelight, serene.' },
            { time: '22–30s', label: 'KẾT', tool: 'VEO3', prompt: `GUEST sits up refreshed, touches her cheek and smiles at the mirror. Close-up, warm soft light. ${NO_TEXT}`, voice: 'Khách: "Đúng là 60 phút được sống chậm lại."' },
          ],
          audio: 'nhạc thiền / tiếng nước chảy, chuông gió.',
          text: 'Tên liệu trình · thời lượng · giá ưu đãi khách mới · địa chỉ.',
          cta: '"Nhắn tin để đặt lịch – tặng [ưu đãi] cho khách lần đầu."',
        }),
      },
      {
        title: 'Swatch son – khoe màu trên môi',
        tool: 'Kling, VEO3',
        description: 'Video ngắn khoe bảng màu son trên nhiều tông da, rất hợp TikTok Shop.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: '[Dùng ảnh thỏi son thật] A lipstick bullet slowly twists up out of its case, macro close-up, glossy reflections, dark velvet background.' },
            { time: '3–11s', label: 'SWATCH', prompt: 'Quick sequence of extreme close-ups of lips (different Vietnamese skin tones: fair, medium, tan) each swiping the lipstick in a different shade [màu 1, màu 2, màu 3], smooth even color. Soft beauty light.' },
            { time: '11–15s', label: 'KẾT', prompt: 'All lipsticks arranged in a fan shape on a marble surface, camera slowly rises. Clean, premium.' },
          ],
          audio: 'nhạc trend; SFX: "click" mỗi lần đổi màu.',
          text: 'Tên mã màu trên từng cảnh · "Lì – nhẹ môi – lâu trôi" (đúng đặc tính thật).',
          cta: '"Bạn hợp màu nào? Comment số 1–2–3!"',
        }),
      },
    ],
  },

  {
    name: 'Thời trang', color: '#C026D3', from: ['Thời trang'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video thời trang',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản lookbook, phối đồ, try-on, ra mắt bộ sưu tập kèm prompt từng cảnh.',
        content: director({
          role: 'đạo diễn video thời trang cho shop online và thương hiệu',
          product: '[sản phẩm / bộ sưu tập, chất liệu, màu, form dáng, giá]',
          audience: '[ví dụ: nữ 20–30 tuổi, phong cách tối giản, đi làm và dạo phố]',
          goals: 'khách thấy đẹp, hình dung được khi mặc và bấm mua',
          styles: '[lookbook điện ảnh / 1 món nhiều cách phối / try-on chuyển cảnh / câu chuyện chất liệu]',
          notes: 'dùng ảnh sản phẩm thật làm tham chiếu để AI giữ đúng màu, họa tiết, form; ghi rõ "keep the outfit exactly the same as the reference".',
        }),
      },
      {
        title: 'Lookbook bộ sưu tập mới',
        tool: 'Kling, VEO3',
        description: 'Video ra mắt BST phong cách phim thời trang, người mẫu dạo phố.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling (ảnh người mẫu mặc đồ thật → video)',
          character: 'MODEL: a tall 24-year-old Vietnamese female model, long straight black hair, natural makeup, wearing [sản phẩm: a beige linen shirt dress with wooden buttons].',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: 'Close-up of linen fabric moving in the wind, sunlight passing through the weave, shallow depth of field, film grain.' },
            { time: '4–10s', label: 'DẠO PHỐ', prompt: 'MODEL walks confidently along a sunny yellow-walled street in Hoi An, the dress flowing with each step. Slow motion tracking shot, golden hour, fashion film. Keep the outfit exactly the same as the reference image.' },
            { time: '10–16s', label: 'CHI TIẾT', prompt: 'MODEL turns and looks over her shoulder, smiles softly; quick close-ups of the wooden buttons and the waist tie. Handheld, dreamy.' },
            { time: '16–20s', label: 'KẾT', prompt: 'MODEL stands still in the middle of the street as petals fall around her, camera slowly pulls back. Cinematic.' },
          ],
          audio: 'nhạc indie / lo-fi nhẹ nhàng; SFX: gió, tiếng vải.',
          text: 'Tên BST · chất liệu · bảng màu · ngày mở bán.',
          cta: '"BST [tên] mở bán [ngày] – lưu video để không bỏ lỡ."',
        }),
      },
      {
        title: '1 chiếc áo – 3 cách phối',
        tool: 'Kling, VEO3',
        description: 'Định dạng phối đồ cực hiệu quả cho shop: chuyển cảnh nhanh theo nhịp nhạc.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling / VEO3 (3 clip chuyển cảnh)',
          character: 'HA: a 25-year-old Vietnamese woman, medium-length brown hair, slim figure, friendly smile.',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: `HA holds up [sản phẩm: a white oversized shirt] to the camera in a bright minimalist bedroom. Medium shot. ${NO_TEXT}`, voice: 'Hà: "Một chiếc sơ mi trắng, ba kiểu khác nhau!"' },
            { time: '3–8s', label: 'SET 1 – ĐI LÀM', prompt: 'HA wears the white shirt tucked into black wide-leg trousers with loafers, walks toward the camera in a modern office lobby. Full body tracking.' },
            { time: '8–13s', label: 'SET 2 – DẠO PHỐ', prompt: 'HA wears the same shirt open over a white tank top with denim shorts and sneakers, spins around on a sunny street. Playful, full body.' },
            { time: '13–18s', label: 'SET 3 – HẸN HÒ', prompt: 'HA wears the same shirt knotted at the waist with a satin midi skirt and small heels, in a cozy café at golden hour. Elegant, slow motion.' },
            { time: '18–20s', label: 'CTA', prompt: `HA winks at the camera and points down. ${NO_TEXT}`, voice: '"Bạn thích set nào? Áo trong giỏ hàng nha!"' },
          ],
          audio: 'nhạc trend nhịp nhanh; SFX: búng tay / whoosh mỗi lần đổi set.',
          text: 'Set 1: Đi làm · Set 2: Dạo phố · Set 3: Hẹn hò.',
          cta: '"Comment 1–2–3 set bạn thích!"',
        }),
      },
      {
        title: 'Try-on chuyển cảnh (che camera)',
        tool: 'Kling',
        description: 'Hiệu ứng thay đồ "thần tốc" quen thuộc trên TikTok, dùng khung đầu – khung cuối.',
        content: script({
          info: '12 giây · dọc 9:16 · Kling (start frame + end frame)',
          character: 'KHOA: a 23-year-old Vietnamese man, short textured black hair, slim build.',
          scenes: [
            { time: '0–4s', label: 'TRƯỚC', prompt: 'KHOA in a plain grey home T-shirt stands in front of a mirror in his room, shrugs at the camera. Phone-camera style.' },
            { time: '4–6s', label: 'CHUYỂN CẢNH', prompt: 'Start frame: KHOA in grey T-shirt. End frame: KHOA in [sản phẩm: a navy bomber jacket, white tee, black jeans]. KHOA throws a jacket toward the camera, covering the lens, then reveals the new outfit. Fast, smooth transition.' },
            { time: '6–12s', label: 'SAU', prompt: 'KHOA in the new outfit adjusts his collar, turns to show the back, confident smile, room lights now cooler and stylish. Full body, slight slow motion.' },
          ],
          audio: 'beat drop đúng lúc chuyển cảnh; SFX: whoosh.',
          text: 'Giá + size có sẵn.',
          cta: '"Lên đồ trong 1 giây – link ở giỏ hàng."',
        }),
      },
      {
        title: 'Câu chuyện chất liệu & xưởng may',
        tool: 'Kling, VEO3',
        description: 'Video thương hiệu tăng giá trị sản phẩm qua quy trình thủ công.',
        content: script({
          info: '40 giây · dọc 9:16 hoặc ngang 16:9 · Kling + VEO3 (lời kể)',
          character: 'OWNER: a 40-year-old Vietnamese female designer, short hair, black linen apron, measuring tape around her neck.',
          scenes: [
            { time: '0–6s', label: 'MỞ ĐẦU', tool: 'Kling', prompt: 'Macro close-up of natural linen threads on a loom, warm sunlight through a workshop window, dust particles floating. Documentary style.' },
            { time: '6–16s', label: 'QUY TRÌNH', tool: 'Kling', prompt: 'Sequence in a small Vietnamese tailoring workshop: hands cutting fabric with big scissors, a sewing machine stitching a seam, hands ironing a finished collar. Handheld close-ups, warm light.' },
            { time: '16–30s', label: 'NGƯỜI SÁNG LẬP', tool: 'VEO3', prompt: `OWNER sits at a wooden table with fabric swatches, speaks to the camera with a calm smile. Medium shot, soft window light. ${NO_TEXT}`, voice: 'Chủ thương hiệu: "Mỗi chiếc áo ở đây được may tay bởi những người thợ đã gắn bó hơn 10 năm."' },
            { time: '30–40s', label: 'KẾT', tool: 'Kling', prompt: 'A finished garment folded with tissue paper and placed into a kraft box with a handwritten thank-you card. Top-down, slow.' },
          ],
          audio: 'piano / guitar mộc; SFX: máy may, tiếng kéo cắt vải.',
          text: 'Tên thương hiệu · "Made in Vietnam" · chất liệu.',
          cta: '"Theo dõi để xem hành trình tạo nên từng thiết kế."',
        }),
      },
      {
        title: 'Áo dài Tết – chiến dịch mùa lễ',
        tool: 'Kling, VEO3',
        description: 'Video mùa Tết rực rỡ, cảm xúc gia đình, khoe áo dài.',
        content: script({
          info: '25 giây · dọc 9:16 · Kling + VEO3',
          character: 'GIRL: a 20-year-old Vietnamese woman with long black hair, wearing [sản phẩm: a red silk áo dài with golden plum blossom embroidery].',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'Peach blossom branches swaying, petals falling in slow motion in front of a traditional Vietnamese house, warm spring sunlight.' },
            { time: '5–13s', label: 'KHOE ÁO DÀI', tool: 'Kling', prompt: 'GIRL walks through a yellow apricot blossom garden, the áo dài flaps flowing elegantly, she turns and smiles. Slow motion, golden light. Keep the áo dài exactly the same as the reference image.' },
            { time: '13–21s', label: 'GIA ĐÌNH', tool: 'VEO3', prompt: `GIRL gives her grandmother a red envelope and hugs her in a cozy living room with a Tet altar, family laughing around. Warm light. ${NO_TEXT}`, voice: 'Cô gái: "Con chúc bà năm mới thật nhiều sức khỏe!"' },
            { time: '21–25s', label: 'KẾT', tool: 'Kling', prompt: 'Close-up of the golden embroidery on the áo dài sleeve, petals falling, camera slowly pulls back.' },
          ],
          audio: 'nhạc Tết hiện đại nhẹ nhàng; SFX: pháo hoa xa, tiếng cười.',
          text: '"Áo dài Tết [năm]" · nhận may đo / đặt trước đến [ngày].',
          cta: '"Đặt áo dài Tết trước [ngày] – tặng [quà]."',
        }),
      },
    ],
  },

  {
    name: 'Nhà hàng & F&B', color: '#CA8A04', from: ['Nhà hàng & F&B'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video quán ăn, cà phê, đồ uống',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video ẩm thực ngon mắt, kéo khách đến quán / đặt món online.',
        content: director({
          role: 'đạo diễn video ẩm thực (food commercial) cho nhà hàng, quán cà phê, thương hiệu đồ uống',
          product: '[tên quán / món signature, nguyên liệu nổi bật, giá, địa chỉ, ưu đãi]',
          audience: '[ví dụ: dân văn phòng quận 1, nhóm bạn trẻ thích check-in]',
          goals: 'người xem thèm món, lưu địa chỉ và đến quán / đặt giao hàng',
          styles: '[cận cảnh món bốc khói ASMR / không gian quán / hậu trường bếp / review của khách]',
          notes: 'ưu tiên cảnh macro, slow motion, âm thanh xèo xèo, giòn rụm; mô tả món chính xác như thực tế.',
        }),
      },
      {
        title: 'Món signature bốc khói (food ASMR)',
        tool: 'Kling, VEO3',
        description: 'Video món ăn ngon mắt, chỉ âm thanh – định dạng giữ chân mạnh nhất ngành F&B.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling / VEO3 (âm thanh ASMR)',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: 'Extreme close-up: chopsticks lift glossy rare beef slices from a steaming bowl of Vietnamese pho, steam rising, broth dripping. Slow motion, warm side light. Sizzling and slurping ASMR sound.' },
            { time: '3–7s', label: 'NẤU', prompt: 'Close-up of a chef ladling boiling clear broth over raw beef slices in a bowl, the beef turning pink instantly, steam bursting. Macro lens.' },
            { time: '7–11s', label: 'HOÀN THIỆN', prompt: 'Hands add fresh basil, lime and chili on top of the pho bowl, top-down shot, rustic wooden table, appetizing light.' },
            { time: '11–15s', label: 'THƯỞNG THỨC', prompt: 'A customer takes a big satisfying bite of noodles, slurping, smiles. Close-up, warm restaurant light, background softly blurred.' },
          ],
          audio: 'không nhạc / nhạc rất nhỏ; ASMR: nước dùng sôi, xèo xèo, húp mì.',
          text: 'Tên món · giá · "Mở cửa 6h–22h" · địa chỉ.',
          cta: '"Lưu lại để ghé – đặt giao hàng qua [app]."',
        }),
      },
      {
        title: 'Không gian quán cà phê (check-in)',
        tool: 'Kling, VEO3',
        description: 'Giới thiệu không gian quán, góc chụp ảnh đẹp, menu nổi bật.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling',
          character: 'GUEST: a 23-year-old Vietnamese girl in a cream knit sweater, long wavy hair, holding a film camera.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: 'Slow push through a wooden door into a cozy vintage café with plants, warm tungsten lights and morning sun beams through windows. Cinematic.' },
            { time: '4–10s', label: 'ĐỒ UỐNG', prompt: 'Close-up of a barista slowly pouring [đồ uống: Vietnamese egg coffee] into a ceramic cup, creamy foam, steam rising. Macro, warm light.' },
            { time: '10–16s', label: 'GÓC CHECK-IN', prompt: 'GUEST sits by a window corner with hanging plants, takes a photo of her drink with her film camera, smiles. Handheld, soft light, aesthetic.' },
            { time: '16–20s', label: 'KẾT', prompt: 'Slow pull back revealing the whole café at golden hour, people chatting softly.' },
          ],
          audio: 'nhạc acoustic / jazz nhẹ; SFX: máy pha cà phê, tiếng cốc chạm.',
          text: 'Tên quán · 3 món nên thử · giờ mở cửa · địa chỉ.',
          cta: '"Tag người bạn muốn rủ đi cà phê cuối tuần này!"',
        }),
      },
      {
        title: 'Hậu trường bếp – món được làm thế nào',
        tool: 'Kling, VEO3',
        description: 'Tăng niềm tin bằng sự sạch sẽ, nguyên liệu tươi, tay nghề đầu bếp.',
        content: script({
          info: '30 giây · dọc 9:16 · Kling + VEO3 (lời đầu bếp)',
          character: 'CHEF: a 45-year-old Vietnamese male chef, white chef jacket, black apron, short grey hair, warm smile.',
          scenes: [
            { time: '0–5s', label: 'HOOK', tool: 'Kling', prompt: 'Early morning at a local market, hands selecting fresh vegetables and herbs, morning light, documentary handheld.' },
            { time: '5–15s', label: 'SƠ CHẾ & NẤU', tool: 'Kling', prompt: 'Clean stainless-steel kitchen, CHEF chops herbs quickly, flames burst from a wok as he tosses [món], steam and fire, dynamic slow motion.' },
            { time: '15–24s', label: 'CHIA SẺ', tool: 'VEO3', prompt: `CHEF faces the camera in the kitchen, wiping his hands on a towel. Medium shot, bright clean light. ${NO_TEXT}`, voice: 'Đầu bếp: "Nước dùng ở đây hầm 12 tiếng, rau mua mới mỗi sáng."' },
            { time: '24–30s', label: 'PHỤC VỤ', tool: 'Kling', prompt: 'CHEF places the finished dish on the pass, a server picks it up, camera follows to a happy customer table.' },
          ],
          audio: 'nhạc nhịp nhanh; SFX: dao thớt, lửa, chảo xèo.',
          text: '"Hầm 12 tiếng" · "Nguyên liệu tươi mỗi ngày" (đúng thực tế quán).',
          cta: '"Ghé thử để cảm nhận – đặt bàn qua [số điện thoại]."',
        }),
      },
      {
        title: 'Khai trương quán mới',
        tool: 'Kling, VEO3',
        description: 'Video thông báo khai trương có ưu đãi, tạo không khí náo nhiệt.',
        content: script({
          info: '20 giây · dọc 9:16 · Kling + VEO3',
          character: 'OWNER: a 32-year-old Vietnamese man, neat short hair, black polo shirt with the shop logo, cheerful.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'Kling', prompt: 'A red ribbon in front of a new shop entrance is cut with golden scissors, confetti bursts, slow motion, festive daylight.' },
            { time: '4–10s', label: 'GIỚI THIỆU', tool: 'VEO3', prompt: `OWNER stands in front of the decorated shop with flower stands, speaks excitedly to the camera. ${NO_TEXT}`, voice: 'Chủ quán: "Quán [tên] chính thức khai trương rồi! Ba ngày đầu giảm 50% toàn menu!"' },
            { time: '10–16s', label: 'MÓN & KHÁCH', tool: 'Kling', prompt: 'Busy happy customers inside the new shop, staff serving signature dishes, quick lively handheld shots.' },
            { time: '16–20s', label: 'KẾT', tool: 'Kling', prompt: 'Exterior shot of the shop sign lighting up at dusk, camera slowly pulls back to show the street.' },
          ],
          audio: 'nhạc sôi động; SFX: tiếng pháo giấy, tiếng vỗ tay.',
          text: '"KHAI TRƯƠNG – GIẢM 50%" · ngày · địa chỉ · bản đồ.',
          cta: '"Check-in tại quán nhận thêm quà – hẹn gặp bạn!"',
        }),
      },
      {
        title: 'Ra mắt đồ uống mới (trà sữa / trà trái cây)',
        tool: 'Kling',
        description: 'Video sản phẩm đồ uống bắt mắt, slow motion, màu sắc rực rỡ.',
        content: script({
          info: '12 giây · dọc 9:16 · Kling',
          scenes: [
            { time: '0–3s', label: 'HOOK', prompt: 'Fresh [trái cây: passion fruit and strawberries] fall into a tall clear cup in slow motion, splashing. Bright pastel background.' },
            { time: '3–7s', label: 'PHA CHẾ', prompt: 'Iced tea pours into the cup, colors layering beautifully, ice cubes clinking, macro slow motion, glossy highlights.' },
            { time: '7–10s', label: 'HOÀN THIỆN', prompt: '[Dùng ảnh ly thật có logo] The cup is sealed and a straw is pierced through, the cup rotates slowly, condensation drops. Keep the cup design and logo exactly the same as the input image.' },
            { time: '10–12s', label: 'KẾT', prompt: 'A hand lifts the drink toward the sunny sky, refreshing feel, lens flare.' },
          ],
          audio: 'nhạc tươi vui; SFX: đá viên, rót nước, "pop" ống hút.',
          text: 'Tên món mới · giá · "Mua 1 tặng 1 [ngày]".',
          cta: '"Thử ngay hôm nay tại [chi nhánh] / đặt qua [app]."',
        }),
      },
    ],
  },

  {
    name: 'Bất động sản', color: '#0EA5E9', from: ['Bất động sản'],
    prompts: [
      {
        title: 'Prompt đạo diễn: video bất động sản',
        tool: 'ChatGPT, Gemini → VEO3, Kling',
        description: 'Kịch bản video giới thiệu căn hộ, dự án, nhà phố kèm prompt từng cảnh.',
        content: director({
          role: 'đạo diễn video bất động sản cao cấp',
          product: '[loại BĐS, vị trí, diện tích, số phòng, view, tiện ích, pháp lý, giá tham khảo]',
          audience: '[ví dụ: gia đình trẻ mua ở thực / nhà đầu tư cho thuê]',
          goals: 'khách hình dung được cuộc sống tại đây và để lại thông tin / đặt lịch xem nhà',
          styles: '[dẫn tham quan (walkthrough) / drone tiện ích / môi giới nói trước camera / một ngày sống tại dự án]',
          notes: 'ghi chú "hình ảnh minh họa" với cảnh tạo bằng AI; không cam kết lợi nhuận, thông tin giá và pháp lý đúng thực tế.',
        }),
      },
      {
        title: 'Dẫn tham quan căn hộ (walkthrough)',
        tool: 'Kling, VEO3',
        description: 'Đi qua từng không gian như người xem đang bước vào nhà.',
        content: script({
          info: '30 giây · dọc 9:16 · Kling (từ ảnh chụp căn hộ thật) + VEO3 (lời dẫn)',
          character: 'AGENT: a 30-year-old Vietnamese female realtor, neat low bun, navy blazer, white blouse, name badge.',
          scenes: [
            { time: '0–4s', label: 'HOOK', tool: 'VEO3', prompt: `AGENT opens the apartment door and gestures inside, smiling at the camera. Bright hallway. ${NO_TEXT}`, voice: 'Môi giới: "Căn 2 phòng ngủ view sông, mời anh chị vào xem!"' },
            { time: '4–12s', label: 'PHÒNG KHÁCH', tool: 'Kling', prompt: '[Dùng ảnh phòng khách thật] Smooth gimbal walkthrough into a bright open living room with floor-to-ceiling windows, river and city view, warm afternoon light. Wide 16mm lens.' },
            { time: '12–18s', label: 'BẾP', tool: 'Kling', prompt: '[Dùng ảnh bếp thật] Slow pan across a modern kitchen with an island counter, soft daylight, clean and minimal.' },
            { time: '18–24s', label: 'PHÒNG NGỦ', tool: 'Kling', prompt: '[Dùng ảnh phòng ngủ thật] Gentle push into a master bedroom, curtains moving slightly, sunlight on the bed, cozy.' },
            { time: '24–30s', label: 'BAN CÔNG + CTA', tool: 'VEO3', prompt: `AGENT stands on the balcony at sunset with the river behind her, speaks to the camera. ${NO_TEXT}`, voice: '"Sổ hồng sẵn, giá [giá]. Inbox để em gửi bảng giá và đặt lịch xem nhà nha."' },
          ],
          audio: 'piano thanh lịch; SFX: tiếng cửa mở, gió nhẹ ở ban công.',
          text: 'Diện tích · số phòng · hướng · giá · "Hình ảnh minh họa" (nếu có cảnh AI).',
          cta: '"Để lại số điện thoại / nhắn tin để nhận bảng giá."',
        }),
      },
      {
        title: 'Drone tiện ích dự án',
        tool: 'Kling, VEO3',
        description: 'Khoe vị trí và tiện ích nội khu: hồ bơi, công viên, trường học.',
        content: script({
          info: '20 giây · ngang 16:9 hoặc dọc 9:16 · Kling / VEO3',
          scenes: [
            { time: '0–5s', label: 'HOOK', prompt: 'Aerial drone shot rising over a modern residential complex beside a river at golden hour, revealing the city skyline. Cinematic, smooth.' },
            { time: '5–10s', label: 'HỒ BƠI', prompt: 'Drone glides low over an infinity rooftop pool with residents relaxing, sparkling water, sunset reflection.' },
            { time: '10–15s', label: 'CÔNG VIÊN', prompt: 'Tracking shot through a green internal park, families walking, kids playing on a playground, joggers. Warm light.' },
            { time: '15–20s', label: 'KẾT NỐI', prompt: 'High aerial view showing the main road, a nearby school and shopping mall, light trails of traffic at dusk.' },
          ],
          audio: 'nhạc điện ảnh hùng tráng nhẹ; SFX: gió, tiếng trẻ em vui đùa xa.',
          text: '"5 phút đến trung tâm" · "Hồ bơi tràn bờ" · "Công viên 2ha" (đúng thông tin dự án) · "Hình ảnh minh họa".',
          cta: '"Đăng ký tham quan nhà mẫu cuối tuần này."',
        }),
      },
      {
        title: 'Môi giới tư vấn trước camera',
        tool: 'VEO3',
        description: 'Xây dựng thương hiệu cá nhân môi giới với lời khuyên hữu ích.',
        content: script({
          info: '30 giây · dọc 9:16 · VEO3',
          character: 'BROKER: a 35-year-old Vietnamese male realtor, short neat hair, light blue shirt, confident and friendly.',
          scenes: [
            { time: '0–4s', label: 'HOOK', prompt: `BROKER walks toward the camera on a city sidewalk with apartment towers behind. Medium shot, handheld. ${NO_TEXT}`, voice: 'Môi giới: "3 điều phải kiểm tra trước khi xuống tiền mua căn hộ!"' },
            { time: '4–12s', label: 'ĐIỀU 1', prompt: `BROKER holds up one finger, standing in a bright lobby. ${NO_TEXT}`, voice: '"Một: pháp lý – sổ hồng hay hợp đồng mua bán, kiểm tra kỹ chủ đầu tư."' },
            { time: '12–20s', label: 'ĐIỀU 2', prompt: `BROKER points at the view from a high window. ${NO_TEXT}`, voice: '"Hai: hướng nhà và view – ảnh hưởng nắng, gió và giá bán lại."' },
            { time: '20–30s', label: 'ĐIỀU 3 + CTA', prompt: `BROKER sits at a café table with a document folder, smiles at the camera. ${NO_TEXT}`, voice: '"Ba: phí quản lý và tiện ích thực tế. Cần em kiểm tra giúp căn nào, comment nhé!"' },
          ],
          audio: 'nhạc nền nhẹ; SFX: "ding" mỗi điều.',
          text: '1. Pháp lý · 2. Hướng & view · 3. Phí quản lý.',
          cta: '"Theo dõi để xem thêm kinh nghiệm mua nhà."',
        }),
      },
      {
        title: 'Cải tạo nhà cũ: trước & sau',
        tool: 'Kling',
        description: 'Hiệu ứng biến hình căn nhà cũ thành mới – rất hút xem.',
        content: script({
          info: '15 giây · dọc 9:16 · Kling (start frame ảnh cũ + end frame ảnh mới / ảnh phối cảnh)',
          scenes: [
            { time: '0–4s', label: 'TRƯỚC', prompt: '[Ảnh căn nhà cũ thật] An old dim living room with peeling walls and old furniture, flickering light. Static wide shot.' },
            { time: '4–10s', label: 'BIẾN HÌNH', prompt: 'Start frame: old living room. End frame: renovated bright modern living room. Walls repaint themselves, old furniture slides away, new sofa and lights appear, sunlight floods in. Smooth magical transformation.' },
            { time: '10–15s', label: 'SAU', prompt: '[Ảnh sau cải tạo / phối cảnh] Slow gimbal move through the renovated room, warm light, cozy and modern.' },
          ],
          audio: 'nhạc dâng; SFX: whoosh, lấp lánh.',
          text: '"Trước" / "Sau" · thời gian thi công · chi phí tham khảo.',
          cta: '"Nhận tư vấn cải tạo miễn phí – nhắn tin ngay."',
        }),
      },
      {
        title: 'Một ngày sống tại dự án',
        tool: 'Kling, VEO3',
        description: 'Kể chuyện cuộc sống gia đình trẻ để bán phong cách sống.',
        content: script({
          info: '35 giây · dọc 9:16 · Kling + VEO3',
          character: 'FAMILY: a young Vietnamese couple in their early 30s (husband in a white T-shirt, wife in a light green dress) and their 5-year-old daughter with pigtails.',
          scenes: [
            { time: '0–6s', label: 'BUỔI SÁNG', tool: 'Kling', prompt: 'The FAMILY has breakfast by a large window with a river view, morning sun, laughing. Warm, cozy, slow push in.' },
            { time: '6–14s', label: 'ĐI HỌC', tool: 'Kling', prompt: 'The mother walks the daughter through a tree-lined internal street to a kindergarten inside the complex, waving goodbye.' },
            { time: '14–24s', label: 'CHIỀU', tool: 'Kling', prompt: 'The father and daughter swim in the community pool at sunset, splashing and laughing. Golden hour.' },
            { time: '24–35s', label: 'BUỔI TỐI', tool: 'VEO3', prompt: `The FAMILY sits on the balcony at night with city lights below, the daughter falls asleep on her mother's lap. ${NO_TEXT}`, voice: 'Người vợ (lời kể): "Nhà không chỉ là nơi để ở, mà là nơi mỗi ngày đều thấy bình yên."' },
          ],
          audio: 'nhạc ấm áp acoustic; SFX: tiếng nước, trẻ em cười.',
          text: 'Tên dự án · tiện ích · "Hình ảnh minh họa".',
          cta: '"Đặt lịch tham quan căn hộ mẫu."',
        }),
      },
    ],
  },
];
