// Chương trình học Video AI: mỗi module là một khóa học, mỗi mục là một bài học.
module.exports = [
  {
    code: '00', title: 'Bắt đầu làm Video AI', level: 'Cơ bản', category: 'Nền tảng', color: '#E11D48',
    description: 'Nắm quy trình làm một video AI từ A–Z, các công cụ sẽ dùng trong khóa học và cách học nhanh nhất.',
    lessons: [
      'Quy trình làm một video AI từ A–Z',
      'Các công cụ sẽ dùng trong khóa học',
      'Cách học nhanh nhất',
      'Link công cụ & tài nguyên',
    ],
  },
  {
    code: '01', title: 'ChatGPT: Kịch bản & Prompt video', level: 'Cơ bản', category: 'Kịch bản & Prompt', color: '#10A37F',
    description: 'Dùng ChatGPT lên ý tưởng, viết hook, kịch bản 15–30–60 giây, chia scene và viết prompt ảnh/video. Kết quả: bạn có bộ kịch bản và prompt sẵn sàng để làm video.',
    lessons: [
      'Tạo tài khoản & làm quen giao diện',
      'Cách viết Prompt đơn giản, dễ hiểu',
      'Lên ý tưởng video',
      'Viết Hook',
      'Viết kịch bản 15–30–60 giây',
      'Chia kịch bản thành từng Scene',
      'Viết Prompt tạo ảnh cho từng Scene',
      'Viết Prompt tạo video cho từng Scene',
      'Sửa Prompt khi AI làm sai',
      'Thực hành: tạo kịch bản + Prompt hoàn chỉnh',
    ],
  },
  {
    code: '02', title: 'Gemini: Hỗ trợ tạo nội dung video', level: 'Cơ bản', category: 'Kịch bản & Prompt', color: '#4285F4',
    description: 'Dùng Gemini phân tích ảnh, sản phẩm và tài liệu để tạo kịch bản, chia scene, viết prompt ảnh và video – kết hợp cùng ChatGPT.',
    lessons: [
      'Tạo tài khoản & giao diện',
      'Phân tích ảnh để tạo Prompt',
      'Phân tích sản phẩm để lên ý tưởng video',
      'Tạo kịch bản từ hình ảnh / tài liệu',
      'Chia nội dung thành các Scene',
      'Viết Prompt ảnh và Prompt video',
      'Kết hợp Gemini + ChatGPT',
      'Thực hành',
    ],
  },
  {
    code: '03', title: 'AI tạo ảnh cho video', level: 'Trung cấp', category: 'Hình ảnh AI', color: '#F97316',
    description: 'Tạo nhân vật, người mẫu AI, ảnh sản phẩm và bối cảnh; giữ nhân vật nhất quán qua nhiều scene và chọn ảnh tốt để đưa sang VEO3/Kling.',
    lessons: [
      'Cách tạo ảnh đầu tiên',
      'Công thức Prompt tạo ảnh',
      'Tạo nhân vật',
      'Tạo người mẫu AI',
      'Tạo ảnh sản phẩm',
      'Tạo bối cảnh',
      'Các góc máy cơ bản',
      'Tạo nhiều Scene cùng phong cách',
      'Giữ nhân vật nhất quán',
      'Sửa ảnh lỗi',
      'Chọn ảnh tốt để đưa sang VEO3/Kling',
      'Thực hành: tạo bộ ảnh cho một video',
    ],
  },
  {
    code: '04', title: 'VEO3: Tạo video AI', level: 'Trung cấp', category: 'Video AI', color: '#4F46E5',
    description: 'Module trọng tâm: tạo video từ prompt và từ ảnh, nhân vật nói chuyện, video có lời thoại, video sản phẩm, quảng cáo, cinematic và nối nhiều scene thành một video.',
    lessons: [
      'Truy cập & làm quen giao diện',
      'Tạo video đầu tiên',
      'Công thức Prompt VEO3',
      'Nhân vật + hành động + bối cảnh',
      'Góc máy & chuyển động Camera',
      'Tạo Video từ Prompt',
      'Tạo Video từ ảnh',
      'Tạo nhân vật nói chuyện',
      'Tạo video có lời thoại',
      'Tạo video sản phẩm',
      'Tạo video quảng cáo',
      'Tạo Video Cinematic',
      'Giữ nhân vật nhất quán giữa các Scene',
      'Nối nhiều Scene thành một video',
      'Các lỗi thường gặp & cách sửa',
      'Thực hành: Video 30–60 giây',
    ],
  },
  {
    code: '05', title: 'Kling AI: Biến ảnh thành video', level: 'Trung cấp', category: 'Video AI', color: '#0EA5E9',
    description: 'Có ảnh → tạo chuyển động → thành video. Làm nhân vật và sản phẩm chuyển động, điều khiển camera, sửa lỗi chuyển động và biết khi nào dùng Kling hay VEO3.',
    lessons: [
      'Tạo tài khoản & giao diện',
      'Biến ảnh thành video đầu tiên',
      'Công thức Prompt chuyển động',
      'Làm nhân vật chuyển động',
      'Cho nhân vật cầm / sử dụng sản phẩm',
      'Camera Push / Pull / Orbit / Tracking',
      'Tạo Video người mẫu',
      'Tạo Video sản phẩm',
      'Tạo Video quảng cáo',
      'Giữ nhân vật & sản phẩm ổn định',
      'Fix lỗi chuyển động',
      'Kling và VEO3: dùng cái nào cho từng trường hợp?',
      'Thực hành: ảnh → Video',
    ],
  },
  {
    code: '06', title: 'Grok: Hỗ trợ làm video', level: 'Cơ bản', category: 'Kịch bản & Prompt', color: '#334155',
    description: 'Dùng Grok lên ý tưởng, viết hook, kịch bản, chia scene và viết prompt ảnh/video nhanh gọn.',
    lessons: [
      'Tạo tài khoản & giao diện',
      'Lên ý tưởng video',
      'Viết Hook',
      'Viết kịch bản',
      'Chia Scene',
      'Viết Prompt ảnh / Video',
      'Thực hành',
    ],
  },
  {
    code: '07', title: 'AI giọng nói cho video', level: 'Cơ bản', category: 'Âm thanh', color: '#7C3AED',
    description: 'Tạo giọng đọc AI tự nhiên cho quảng cáo, review và storytelling; chia voice theo từng scene và xuất file để ghép video.',
    lessons: [
      'Tạo Voice AI đầu tiên',
      'Chọn giọng phù hợp Video',
      'Giọng quảng cáo',
      'Giọng Review',
      'Giọng Storytelling',
      'Làm giọng đọc tự nhiên hơn',
      'Chia Voice theo từng Scene',
      'Xuất Voice để ghép Video',
      'Thực hành',
    ],
  },
  {
    code: '08', title: 'AI âm nhạc cho video', level: 'Cơ bản', category: 'Âm thanh', color: '#DB2777',
    description: 'Tạo nhạc nền và hiệu ứng âm thanh bằng AI cho video quảng cáo, cinematic và storytelling.',
    lessons: [
      'Tạo nhạc nền bằng AI',
      'Prompt tạo nhạc',
      'Nhạc quảng cáo',
      'Nhạc Cinematic',
      'Nhạc Storytelling',
      'Hiệu ứng âm thanh',
      'Chọn nhạc phù hợp Video',
      'Thực hành',
    ],
  },
  {
    code: '09', title: 'Ghép & hoàn thiện video', level: 'Trung cấp', category: 'Hậu kỳ', color: '#CA8A04',
    description: 'Phần bắt buộc với người mới: ghép scene, voice, nhạc, sound effect, caption, text/logo, chuyển cảnh và xuất video dọc 9:16 hoặc ngang 16:9.',
    lessons: [
      'Import các Scene',
      'Sắp xếp và cắt Video',
      'Ghép Voice',
      'Ghép nhạc nền',
      'Thêm Sound Effect',
      'Thêm Caption',
      'Thêm Text / Logo',
      'Chuyển cảnh',
      'Chỉnh âm lượng',
      'Video dọc 9:16 và ngang 16:9',
      'Xuất Video',
      'Thực hành hoàn thiện Video',
    ],
  },
  {
    code: '10', title: 'Quy trình làm Video AI từ A–Z', level: 'Nâng cao', category: 'Thực chiến', color: '#E11D48',
    description: 'Module quan trọng nhất: xem làm một video thật từ đầu đến cuối – Ý tưởng → Kịch bản → Chia scene → Prompt → Tạo ảnh → Tạo video bằng VEO3/Kling → Voice → Nhạc → Ghép video → Caption & hiệu ứng → Xuất video hoàn chỉnh.',
    lessons: [
      'Chọn ý tưởng',
      'Viết kịch bản',
      'Chia Scene',
      'Viết Prompt',
      'Tạo ảnh',
      'Tạo Video',
      'Tạo Voice',
      'Chọn nhạc',
      'Ghép Video',
      'Caption & hiệu ứng',
      'Fix lỗi',
      'Xuất Video hoàn chỉnh',
    ],
  },
  {
    code: '11', title: 'Video AI quảng cáo', level: 'Nâng cao', category: 'Thực chiến', color: '#F43F5E',
    description: 'Làm mẫu thực tế các dạng video quảng cáo bằng AI và hoàn thiện một video quảng cáo từ A–Z.',
    lessons: [
      'Video sản phẩm 15 giây',
      'Video quảng cáo 30 giây',
      'Video UGC AI',
      'Video Review sản phẩm',
      'Video Problem → Solution',
      'Video Cinematic sản phẩm',
      'Làm hoàn chỉnh 1 Video quảng cáo từ A–Z',
    ],
  },
  {
    code: '12', title: 'Video AI Affiliate', level: 'Nâng cao', category: 'Thực chiến', color: '#059669',
    description: 'Làm video tiếp thị liên kết bằng AI: tìm ý tưởng, hook, kịch bản, CTA, video review, UGC và tạo nhiều video từ một sản phẩm.',
    lessons: [
      'Tìm ý tưởng cho sản phẩm',
      'Viết Hook',
      'Viết kịch bản Affiliate',
      'Tạo ảnh',
      'Tạo Video',
      'Voice',
      'CTA',
      'Video Review',
      'Video Problem → Solution',
      'Video UGC Affiliate',
      'Từ 1 sản phẩm tạo nhiều Video',
      'Thực hành từ A–Z',
    ],
  },
  {
    code: '13', title: 'Video AI giải trí', level: 'Nâng cao', category: 'Thực chiến', color: '#F59E0B',
    description: 'Xây dựng nhân vật và làm video tình huống, hài, storytelling, cinematic và series nhân vật bằng AI.',
    lessons: [
      'Lên ý tưởng',
      'Viết kịch bản',
      'Xây dựng nhân vật',
      'Video tình huống',
      'Video hài',
      'Storytelling',
      'Cinematic',
      'Series nhân vật',
      'Thực hành từ A–Z',
    ],
  },
  {
    code: '14', title: 'Video AI giáo dục', level: 'Nâng cao', category: 'Thực chiến', color: '#2563EB',
    description: 'Làm video kiến thức ngắn và video giải thích bằng AI: chọn chủ đề, kịch bản, hình minh họa và voice thuyết minh.',
    lessons: [
      'Chọn chủ đề',
      'Viết kịch bản',
      'Chia Scene',
      'Tạo hình ảnh minh họa',
      'Tạo Video',
      'Tạo Voice thuyết minh',
      'Video kiến thức ngắn',
      'Video giải thích',
      'Thực hành từ A–Z',
    ],
  },
  {
    code: '15', title: 'Kho Prompt Video AI', level: 'Cơ bản', category: 'Tài nguyên', color: '#9333EA',
    description: 'Thư viện prompt để sao chép dùng ngay: ảnh, nhân vật, sản phẩm, VEO3, Kling, camera, quảng cáo, affiliate, UGC, cinematic, storytelling và theo ngành.',
    lessons: [
      'Prompt tạo ảnh',
      'Prompt nhân vật',
      'Prompt sản phẩm',
      'Prompt VEO3',
      'Prompt Kling',
      'Prompt Camera',
      'Prompt quảng cáo',
      'Prompt Affiliate',
      'Prompt UGC',
      'Prompt Cinematic',
      'Prompt Storytelling',
      'Prompt theo ngành',
    ],
  },
  {
    code: '16', title: 'Tài nguyên & cập nhật', level: 'Cơ bản', category: 'Tài nguyên', color: '#64748B',
    description: 'Link công cụ, prompt mới, công cụ video AI mới, sound effect, nhạc, font, template, checklist làm video AI và hướng dẫn bổ sung.',
    lessons: [
      'Link công cụ',
      'Prompt mới',
      'Công cụ Video AI mới',
      'Sound Effect',
      'Nhạc',
      'Font',
      'Template',
      'Checklist làm Video AI',
      'Hướng dẫn bổ sung',
    ],
  },
];
